### ISSUE TITLE
How publish a message?

### ISSUE THREAD

**Issue by bolognesi** [golevelup/nestjs#100]
Hello,
thanks for this library! I was wondering how it is possible write (i.e. publish) on the message bus.
Using the pubSubHandler I can receive the messages, but it is not clear to me how to write messages on an exchange.

Thanks, best wishes
Thomas

**Comment by WonderPanda** [comment]
Hey @bolognesi  thanks for your interest in the library. This part of the docs needs to be improved but sending messages is quite simple. Assuming you've included the RabbitMQModule in your application, you can simply inject the `AmqpConnection` into the controller/service from which you would like to publish messages and interact with the connection directly.

Here's an example from the integration tests of publishing a message:

https://github.com/golevelup/nestjs/blob/7b1a665fa7678575fda40dd9ca85ef6d0dd4d580/integration/rabbitmq/e2e/subscribe.e2e-spec.ts#L58

I'll try and make some much needed improvements to the docs in the coming week. Feel free to re-open if this doesn't get you up and running but I'm going to close this issue for now

**Comment by bolognesi** [comment]
Thanks for the quick reply! However, I am not able to import the AmqpConnection.
RabbitMQModule seems imported ok in the application, but when I try to AmqpConnection this error is shown:
Error: Nest can't resolve dependencies of the AppController (?). Please make sure that the argument AmqpConnection at index [0] is available in the AppModule context.
Potential solutions:
- If AmqpConnection is a provider, is it part of the current AppModule?
- If AmqpConnection is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing AmqpConnection */ ]
  })

Thank you very much for your help.
Thomas

**Comment by WonderPanda** [comment]
@bolognesi 

I've added a Table of Contents and new sections to the RabbitMQ docs to explain this better

https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#sending-messages

**Comment by bolognesi** [comment]
@WonderPanda Great job and great library.Thanks!

**Comment by dvirarad** [comment]
Hi
I have issue when I am trying to connect to 
This is my module that connects to RabbitMQ
`@Module({
  imports: [
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      useFactory: async (config: ConfigService) => {
        const exchanges = await getExchanges(config);
        return getRabbitMQConfig(exchanges, config);
      },
      inject: [ConfigService],
    }),
  ],
})
export class AmqpSubscribeModule {}`

When I have a module that I want to subscribe I'm just importing איק AmqpSubscribeModule module.

But when I am trying to use AmqpConnection in the service I am getting error  

`Nest can't resolve dependencies of the service (LoggerService, ConfigService, ?). Please make sure that the argument AmqpConnection at index [2] is available in the service context.
`
