### ISSUE TITLE
How send RPC message

### ISSUE THREAD

**Issue by narimanam** [golevelup/nestjs#101]
hi, thanks for this library.
I want to use AmqpConnection for call rpc. I can use publish function for broadcast messages,but for RPC I don't know how to do that. can you explain more about send messages

**Comment by WonderPanda** [comment]
Hey @nariman-amani thanks for your interest in @golevelup

I've added a Table of Contents and new sections to the RabbitMQ docs to explain this better

https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#sending-messages

**Comment by kdi-1** [comment]
You can see this in test

https://github.com/golevelup/nestjs/blob/7b1a665fa7678575fda40dd9ca85ef6d0dd4d580/integration/rabbitmq/e2e/rpc.e2e-spec.ts#L29

`  const response = await amqpConnection.request({
      exchange: 'exchange1',
      routingKey: 'rpc',
      payload: {
        request: 'val',
      },
    });`
