### ISSUE TITLE
DiscoveryService not resolving

### ISSUE THREAD

**Issue by Ponjimon** [golevelup/nestjs#103]
Hi, I'm trying to use the DiscoveryService in my GraphqlService inside `createGqlOptions`.

```typescript
async createGqlOptions(): Promise<GqlModuleOptions> {
        const costMap = await this.discoveryService
            .providersWithMetaAtKey(COST_MAP_METADATA);
        console.log(costMap); // never executed
        // ...
}
```

but the console.log is never executed as the promise is never resolved.

If I change it to this:

```typescript
async createGqlOptions(): Promise<GqlModuleOptions> {
        const costMap = this.discoveryService
            .providersWithMetaAtKey(COST_MAP_METADATA).then(console.log);
        // ...
}
```

The promise resolves, but if I wrap everything inside the `then` it again does not resolve. Any idea why?

**Comment by WonderPanda** [comment]
Hey @lookapanda I'm sorry this issue slipped past me. I've never run into this before and there's decent test coverage that runs for each build that covers this functionality. Any chance you can provide a repo that reproduces this issue so that I can take a look?

**Comment by WonderPanda** [comment]
PS cool name :stuck_out_tongue:

**Comment by WonderPanda** [comment]
Feel free to open this again if there's more information regarding the issue. I can't investigate it currently without a reproducible example
