### ISSUE TITLE
Issue with default exchange

### ISSUE THREAD

**Issue by mfcodeworks** [golevelup/nestjs#105]
Attempting to create a multi-queue listener with the following code 

```javascript
@Module({
    imports: [RabbitMQModule.forRoot(RabbitMQModule, { "uri": "amqp://guest:guest@localhost:5672" })],
    providers: [WorkerService],
    exports: [
        RabbitMQModule,
        WorkerService
    ]
})
export class WorkerModule {}
```

```javascript
@Injectable()
export class WorkerService {
    constructor(private queue: AmqpConnection) {}

    @RabbitSubscribe({
        exchange: '',
        routingKey: '',
        queue: 'test:first'
    })
    public async handleTestFirst(data: {}): Promise<void> {
        console.log('Received test:first message', data);
        this.queue.publish('', 'test:second', data);
    }

    @RabbitSubscribe({
        exchange: '',
        routingKey: '',
        queue: 'test:second'
    })
    public async handleTestSecond(data: {}): Promise<void> {
        console.log('Received test:second message', data);
    }
}
```

Every time I run the app I get the error `Error: Operation failed: QueueBind; 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - operation not permitted on the default exchange"`, what causes the error to occur?

I'd prefer to remain on the default exchange so I don't have to alter an existing RabbitMQ instance too much, it will be easier if I can use the default exchange and port some code to NestJS

**Comment by mfcodeworks** [comment]
**SOLVED** Publishing without an exchange string is fine, config without an exchanges array is fine, *but* any subscriber **requires** an exchange. The default for RabbitMQ is `amq.direct` so simply changing the subscriber exchange to `amq.direct` fixed all issues. 

This should probably be stated in the docs as it's the only place that absolutely requires an exchange to function.

Code
```typescript
import { Injectable, OnApplicationBootstrap } from '@nestjs/common';
import { RabbitSubscribe, AmqpConnection } from '@golevelup/nestjs-rabbitmq';

@Injectable()
export class WorkerService implements OnApplicationBootstrap {
    constructor(private queue: AmqpConnection) {}

    onApplicationBootstrap(): void {
        this.queue.publish('', 'test:first', { data: 'test payload' });
    }

    @RabbitSubscribe({
        exchange: 'amq.direct',
        routingKey: 'test:first',
        queue: 'test:first'
    })
    public async handleTestFirst(data: {}): Promise<void> {
        console.log('Received test:first message', data);
        this.queue.publish('', 'test:second', data);
    }

    @RabbitSubscribe({
        exchange: 'amq.direct',
        routingKey: 'test:second',
        queue: 'test:second'
    })
    public async handleTestSecond(data: {}): Promise<void> {
        console.log('Received test:second message', data);
    }
}
```

**EDIT** Default exchange also requires that `queue` and `routingKey` are **both** supplied and **both** identical

**Comment by WonderPanda** [comment]
Thanks for the detailed code snippets and information about how you resolved this issue. These are requirements for the way RabbitMQ and AMQP work so I've gone back and forth about how much "extra" information to include in the docs for this library that would be duplicating the better documentation effort from the RabbitMQ team.

I'll try and update the docs to help guide people towards the RabbitMQ docs and may include some specific notes about the issue you ran in to if it seems to be a common problem for users.
