### ISSUE TITLE
Unable to define handler decorators dynamically

### ISSUE THREAD

**Issue by sjmittal** [golevelup/nestjs#106]
Hi,
Firstly thanks for a great lib, very simple and intuitive to use.
In my case configs like exchange name and routing keys are picked from the configuration service.

So if I define a handler like:
```
@RabbitSubscribe({
    exchange: 'exchange',
    routingKey: 'key',
  })
  public async collectDataHandler(msg: FileUploadedEvent) {
 }
```
I don't want to hardcode the values, rather than get the values of `exchange` and `routingKey` picked from say a config service dynamically,

Is there a way to do this.

If I inject config service in the `MyService` like:
```
private static exchange: string;
constructor(
    private readonly amqpConnection: AmqpConnection,
    private readonly configService: ConfigService) {
      MyService.exchange = configService.get('ExchangeName' });
  }
```
Then I use my decorator as:
```
@RabbitSubscribe({
    exchange: MyService.exchange,
    routingKey: 'key',
  })
```
It gets picked up as `null`.

Is there a way to do this.

**Comment by WonderPanda** [comment]
@sjmittal Thanks for the kind words.

There is currently no way to do this using the Decorator approach. However, the Decorators just act as collectors of configuration info to ultimately construct some RPC or Subscribe listeners using the included Amqp lib. You could definitely hook up dyamic handlers yourself based on this approach.

Have a look at the `onModuleInit` lifecycle for the RabbitMQ Module which is where the handlers get glued together:

https://github.com/golevelup/nestjs/blob/c20ba1b67eb3855f4c2b10d3e625891eb7a14042/packages/rabbitmq/src/rabbitmq.module.ts#L131

**Comment by sjmittal** [comment]
I checked the class and I notice that config is ultimately derived from decorators itself using these line:
https://github.com/golevelup/nestjs/blob/c20ba1b67eb3855f4c2b10d3e625891eb7a14042/packages/rabbitmq/src/rabbitmq.module.ts#L101-L103

And for now in decorators one has to statically define the exchange and routing key. Is there any other way we can pass the config to Amqp lib which can be constructed dynamically by reading props from a config service.

Can we have this as an enhancement to be able to pass handlers config dynamically.

**Comment by WonderPanda** [comment]
@sjmittal Have you tried https://github.com/mozilla/node-convict? It would allow you to dynamically configure your decorators based on ENV variables or a .env file that you include in your application. It won't work if your config service comes through NestJS depedency injection but this (and other modules) let you do config outside of Nest which makes these scenarios much easier.

It is a current limitation of NestJS that it is impossible to solve this in any other way without a huge amount of effort so I don't plan to bring anything to the library at this time

**Comment by ahmednawazkhan** [comment]
this is a common use case. I solved it using `AmqpConnection` class with `OnModuleInit`

![image](https://user-images.githubusercontent.com/20334388/156347928-52b9dffe-132e-4db4-af3e-96ddbd1f8d41.png)

Hope this helps
