### ISSUE TITLE
Discovery Service Documentation

### ISSUE THREAD

**Issue by victordidenko** [golevelup/nestjs#13]
It would be great to have actual documentation for packages

**Comment by WonderPanda** [comment]
Thanks @victordidenko I agree. I've tried to make an effort with docs on the [@nestjs-plus/rabbitmq ](https://github.com/WonderPanda/nestjs-plus/blob/master/packages/rabbitmq/README.md) module but docs around the Discovery Module aren't the greatest at the moment. I have ensured that the public API for Discovery is completely covered with JsDoc so you should actually get decent docs in your IDE if you install the package. There are also unit test suites that demonstrate how to use Discovery to query your application's dependencies

I'll close this issue once I've added docs to GitHub regarding how best to consume the Discovery Service API. As part of this I may also move to a dedicated package (most likely @nestjs-plus/discovery) so stay tuned.

If you have any specific questions about the functionality of a package let me know and I'll do my best to answer.

**Comment by WonderPanda** [comment]
@victordidenko fixed with #14 and #15 

Please feel free to let me know if you have any further questions or need additional clarification beyond the docs I've provided
