### ISSUE TITLE
Cannot use this lib from a source

### ISSUE THREAD

**Issue by tadejgolobic** [golevelup/nestjs#136]
I am working an a work project, and I would like to check if I can implement some stuff for RMQ. So I have performed clone on your repo, ran ```npm install``` in all packages folder and then I ran build from root directory. Then I went to my project and tried to import it like this ```import { Nack, RabbitSubscribe } from '/home/tadejgolobic/github.com/golevelup/nestjs/packages/rabbitmq/'``` however, this was not ok, I got following error:

```ts
> queue@0.0.1 start /home/tadejgolobic/test/queue
> nest start

src/app.service.ts:17:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.
  Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'void | TypedPropertyDescriptor<(msg: {}) => Promise<Nack>>'.
    Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'TypedPropertyDescriptor<(msg: {}) => Promise<Nack>>'.
      Type 'unknown' is not assignable to type '(msg: {}) => Promise<Nack>'.
        Type '{}' provides no match for the signature '(msg: {}): Promise<Nack>'.

 17   @RabbitSubscribe({
      ~~~~~~~~~~~~~~~~~~
 18       exchange: 'amq.topic',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 20       queue: 'message'
    ~~~~~~~~~~~~~~~~~~~~~~
 21   })
    ~~~~

Found 1 error(s).
```

Apparently I am using it wrong? How should I use it so that I would get it to work?

And to describe what I want to do:  I want to implement custom ```onMessage``` callback for ```channel.consume``` method. Here is your implementation: https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L252

I would like to provider own onMessage callback, that would be defined in RabbitSubscribe decorator

**Comment by WonderPanda** [comment]
@tadejgolobic Hey sorry did you end up getting this working? Generally I'd suggest that you'd have an easier time including the NPM packages instead of pulling in the source directly. Are you trying to use the library in a non NestJS context?

**Comment by tadejgolobic** [comment]
@WonderPanda , yes, no problem. I was able to get it up and running. I have another issue, maybe you can take a look? #141
