### ISSUE TITLE
[RabbitMQ] Returns and empty object {} when connection.request Errors

### ISSUE THREAD

**Issue by saarikivit** [golevelup/nestjs#139]
Hey! I lately found out that if **this.amqpConnection.request** Errors it will return an empty object but not throw.

```
private async getProfileById(profileId: string) {
  const payload: IProfileGetPayload = {
    profileId
  };

  return this.amqpConnection.request<ProfileObject>({
    exchange: MQExchanges.GLOBAL,
    routingKey: MQRoutingKeys.PROFILE.GET_BY_ID,
    payload,
    timeout: 3000,
  });
}
```

Is there any way for me to check if an error occurred? expect something custom like:
```
const hasError = !Object.keys(result).length;
```

Thanks so much for your time! :pray: :smile_cat:

**Comment by WonderPanda** [comment]
Hey @saarikivit the library isn't super opinionated about this at the moment. Generally this is left open to the implementer to decide. Do you have control over the code for the RPC that you're calling? You could wrap it in a try catch in the remote service and send back whatever kind of error object you want to give context to the caller

**Comment by saarikivit** [comment]
Ok! I think I'll implement something like a graphql response: { data, error } 👍
Thanks!

**Comment by WonderPanda** [comment]
@saarikivit Nice I think that's a great approach!
