### ISSUE TITLE
 Failed to receive response within timeout of 10000ms

### ISSUE THREAD

**Issue by iampedii** [golevelup/nestjs#140]
Hi, 
I'm having frequent timeouts just because my operations are taking longer than 10seconds. 
` Failed to receive response within timeout of 10000ms`
I wonder if there is any way to change the timeout value?

**Comment by WonderPanda** [comment]
Is this happening when you're using RPC and the `request` method to get a response? If so you can set the desired timeout on each operation:

https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#requesting-data-from-an-rpc

**Comment by WonderPanda** [comment]
Closing this as support for custom timeouts is already built into the library. Feel free to reopen if you run into any problems where it doesn't seem to be working when you set a custom timeout
