### ISSUE TITLE
errorHandler is not being called 

### ISSUE THREAD

**Issue by iampedii** [golevelup/nestjs#144]
Hi 

I realised that there is a way to handle error whilst processing the incoming messages and updated the package to version `^1.15.0`. However, an exception cause an infinite re-queuing and the error handler will never log anything.

Here is how I use it, 
```
class TestMessenger {
  @RabbitSubscribe({
    exchange: "magento-integration",
    routingKey: "migrate-orders",
    queue: "magento-integration.migrate-orders",
    allowNonJsonMessages: true,
    errorHandler: this.errorHandler,
  })
  async receiver(data) {
    throw new RpcException("Should Throw");
  }
  private static errorHandler() {
        console.log("Here is an error!")
    }
}
```

**Comment by WonderPanda** [comment]
Hey @iampedi I'll have to take a look further into this to see what's up. Any chance you can share a link to a repo with a minimum reproducible example of this happening? 

My first thought is that it might be because you're referencing a class member as the errorHandler (even though it's static). Generally the intention is that error handling functions should be written as utility functions and not members of a class due to the way NestJS reflection and discovery works although I haven't tested this scenario specifically

**Comment by iampedii** [comment]
I have actually tested it with a utility function as well but unfortunately, I had no luck. I'll prepare the repo today.

Thank you @WonderPanda

**Comment by WonderPanda** [comment]
Hey @PedramMarandi were you able to create a reproduction of this issue that I can take a look at?

**Comment by iampedii** [comment]
@WonderPanda Sorry for my huge delay. I was trying to reproduce the bug but apparently I was mixing some paradigms here. 

I'd like to suggest better documentation for error handling. I'm really eager to contribute but I'm not feeling I know if good enough yet. 

What I could understand is `errorHandler` is only being called when it's a `RabbitSubscribe`. 

Here is my RPC implementation 
```typescript

@Injectable()
export class ReceiverService {
  @RabbitRPC({
    exchange: 'exchange',
    routingKey: 'exchange',
    queue: 'exchange',
    allowNonJsonMessages: true,
    // below is not being called using rpc
    // errorHandler: (exchange, msg, e) =>
    //   console.log('I am the error handler', e),
  })
  public received(params) {
    throw new RpcException('Here is the error');
  }

  private static errorHandler(channel, msg, error) {
    console.log('Error Handler ~> ', error);
  }
}
```

By throwing the RpcException, the sender will receive
```Received data  { error: 'Here is the error', message: 'Here is the error' }```

Thanks
