### ISSUE TITLE
[RabbitMq] Allow dynamic subscription to many topics in one subscribe

### ISSUE THREAD

**Issue by Hanawa02** [golevelup/nestjs#151]
I would like to be able to subscribe to many topics in one method, and also to change the topics subscribed to during run-time, is that possible?

![image](https://user-images.githubusercontent.com/11237366/82054463-480db800-96bf-11ea-940d-aa48c954f257.png)

**Comment by WonderPanda** [comment]
Hey @Hanawa02 currently it's possible to bind a handler to multiple routing keys but not multiple exchanges. I don't think it would be a big change to allow binding on multiple exchanges though so I can take a look at adding that in.

Dynamically changing subscriptions at runtime would be a much bigger undertaking, can you elaborate more as to your use case for this?

**Comment by Hanawa02** [comment]
Hey @WonderPanda , thanks in advance for taking a look into this issue.

In my scenario I have a message bus (RabbitMQ server), and its going to collect data from many sources (mainly IOT devices), and for each IOT device connected, it will have a different topic.

The user then will be able to extract some values from this data, for that he will use my app to define the JSON path to extract the value from the data, and (s)he will define from which topics should the data be extracted from.

As an example:
A system composed of:
- Weather sensor
- Luminosity Sensor

Each sensor has its own topic 'weather' and 'luminosity'

The weather sensor gives a JSON with the following data structure:
`{
   temperature: {
      value: 28, 
      scale: 'Celsius',
   },
   humidity: '38%'
}`

The luminosity sensor gives a JSON with the following data structure:
`{
   value: 30, 
   scale: 'watts',
}`

My user then creates a KPI to extract the humidity from the 'weather' topic, then I add 'weather' subscription to my system.
Later on the user decides to extract also the luminosity value, then I add 'luminosity ' subscription to my system.
Later on the user doesn't need the value from the weather, and deletes the extraction, then I should remove the 'weather' subscription from my system.

**Comment by Hanawa02** [comment]
I was able to create the subscriptions dynamically this way, but I am not sure if there is any way to remove the subscriptions.

![image](https://user-images.githubusercontent.com/11237366/82194332-eb94dd80-98f6-11ea-92bd-933910f59574.png)

**Comment by WonderPanda** [comment]
Hey @Hanawa02 thanks for the updated examples. A few things jump out to me here that I think are worth discussing. You are using the term exchange and topic interchangeably which isn't entirely correct. `Topic` is just one of the various types of exchanges and I definitely do not think you should create an exchange per IoT device in your system. A topic exchange can be subscribed to based on [dynamic components of it's routing keys](https://www.rabbitmq.com/tutorials/tutorial-five-javascript.html). 

Therefore, I think it would be a much better design to have a single `telemetry` (or similar name) exchange in your system which you would then have different subscriptions to based on the routing key. For example you might structure your routing key as `telemetry.{measurementType}.{deviceId}` eg. `telemetry.weather.1234` or `telemetry.luminosity.1234`. Alternatively you might also consider putting the deviceId ahead of the measurement depending on what makes the most sense for your message processing.

Does the user set KPI always based solely on the measurement type (luminosity, weather, etc) or do they also need the ability to turn off subscriptions based on individual devices or groups of devices? Based on the points listed above does it still make sense to you that you would actually want to subscribe to multiple distinct exchanges as opposed to portions of a topic?

**Comment by Hanawa02** [comment]
I see, we are going to use the Topic type of exchange in the project, maybe I got confused and mixed both words.

Actually the main problem is that my system by itself will not know about the topics, my app is just a component of a big system, so I don't know how many topics we will have, and which, but my app needs to be prepared in the case of many. I just used the temperature/luminosity data as an example.

I think of the unsubscription mainly for performances reason, since it could be a topic with many data inputs, for example a production line with many items per second, and I would be listening to it for no good reason.

**Comment by WonderPanda** [comment]
Hi @Hanawa02 sorry I missed the notification for your reply. I am still a little bit confused about what the desired use case here is. In the examples that you've provided you are creating subscriptions based on topics or exchanges in your decorators. That means that it can't really be dynamic in the first place since you would have to make code changes and redeploy your application in order to change your configuration.

In order to be fully dynamic in the way that I think you'd like all of this information would need to be derived at runtime. How will you be receiving information about which topics are necessary for you to subscribe to? Are you going to be doing a lookup in a database somewhere or making a call to another system? Will there be some kind of user interface that allows administrators to configure the app? Or do you intend to simply make the code changes and redeploy each time?

I think that dynamic subscriptions make a lot of sense as a more advanced feature but in this case it would probably need to be done without decorators at all in order for you to be able to dynamically add and remove them once the app is already running. Let me know what your thoughts are about this and I will consider what the best API would look like for truly dynamic configuration although it may be a bigger undertaking

**Comment by Hanawa02** [comment]
Hi @WonderPanda, no worries! 

So far I am able to subscribe dynamically like this, the topics will be retrieved by API from another System:

![image](https://user-images.githubusercontent.com/11237366/82784724-6adb6180-9e61-11ea-9484-ac64185fada8.png)

This is enough for me and its working as I need, when I added the request I didn't had enough knowledge about the way decorators are applied. I think adding the possibility to bind to multiple exchanges in the decorator could be something positive for your application, doing it dynamically through the handler is the best way for my use case. 

The only thing that I still couldn't figure out is the way to unsubscribe from the exchanges. Do you have any suggestions on how to do it?

PS: Thanks a lot for the support, keep up the good work!
