### ISSUE TITLE
Logger for incoming requests

### ISSUE THREAD

**Issue by narimanam** [golevelup/nestjs#157]
- [x] feature-request
thanks for this great project. 
Is there any way to add a logger to subscribers?
I want to log incoming requests in a default format for all subscribers
I think if an option exists on module configuration for enabling subscriber level logging that would be great.

**Comment by WonderPanda** [comment]
Hey @nariman-amani what information specifically are you hoping to log from the subscribers? I'd prefer to allow a user to plug in their own logger instead of building it directly into the module.

**Comment by narimanam** [comment]
@WonderPanda I need to log all of the requests received to my subscribers with information like routingKey or queue. something like morgan for express Rest requests.
I'm currently using my own logger in each subscriber function.
if a solution exists to add middleware to this library that'll be great.

**Comment by WonderPanda** [comment]
You should be able to use NestJS `Interceptors` to attach common functionality to your handlers. It might be possible for you to share your logging functionality through an interceptor that you apply to your service classes. I'll consider the possibility of adding logging directly to the library but I'm worried that it would be enforcing something too specific

**Comment by narimanam** [comment]
thanks. I used `Interceptors` to handle logging functionality

**Comment by WonderPanda** [comment]
Awesome! I'm going to close this for now, feel free to create a new issue if you run into any problems
