### ISSUE TITLE
Ability to set prefetchCount on a single subscription

### ISSUE THREAD

**Issue by rennenc** [golevelup/nestjs#158]
From reviewing the interfaces and configurations, you can set the `prefetchCount` only on the `RabbitMQConfig`.

I'd expect it to be available on `MessageHandlerOptions` as well so that we can control the prefetch for each subscription independently.

Is there a way to configure this on the message handler level?

**Comment by WonderPanda** [comment]
This needs some more investigation as this library is built against `amqplib` and RabbitMQ introduces it's own special handling for prefetch ontop of the AMQP spec:

https://www.squaremobius.net/amqp.node/channel_api.html#channel_prefetch
https://www.rabbitmq.com/consumer-prefetch.html

**Comment by WonderPanda** [comment]
We do not set the flag globally which means that currently the prefetch count limit is already independent per consumer. I don't see any way with RabbitMQ to be able to specify different values per consumer. If there was a concrete need to be able to do this it appears it would need to be done using multiple different connected channels each with their own prefetch

**Comment by WonderPanda** [comment]
@rennenc Do you have any experience setting up a prefetch count per consumer separate from the limitations listed above or was this more of a nice to have? I don't think it's particularly actionable at the moment other than we should probably expose an additional config option for the module that allows a consumer to specify whether they want the prefetch to be assigned globally or per consumer

**Comment by WonderPanda** [comment]
Closing this for now as it's not immediately actionable. Feel free to re-open if there's more information
