### ISSUE TITLE
Unable to receive from queue

### ISSUE THREAD

**Issue by erayalakese** [golevelup/nestjs#166]
Hi,

Imported the `RabbitMQModule` in my module like this:

```
RabbitMQModule.forRoot(RabbitMQModule, {
        exchanges: [
            {
                name: 'exchange1',
                type: 'direct'
            }
        ],
        uri: 'amqp://USER:PASS@URL:5672',
    })
```
And in one of my service files:

```
@RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'rpc-route',
    queue: 'rpc-queue',
  })
  public async rpcHandler(msg: {}) {
    return new Nack();
  }
```

The binding exists between `rpc-queue` queue and `exchange1` exchange with the routing key `rpc-route`. But it's never receiving messages from the queue. 

I can see the connection in Management plugin Web UI with "running" state, but the consumer list of the queue is empty. Looks like my connection is ok but something is wrong with RabbitRpc() configurations.

Sending a message works by the way. Can you please help me?

Thanks

**Comment by WonderPanda** [comment]
Hey @erayalakese can you please share an example of how you are sending the message?

**Comment by rushprint** [comment]
I have same issue. 
My question is should I create queue manually? or any options to make it automatically?
I think it would be better providing a working example with the library.

**Comment by WonderPanda** [comment]
@rushprint You do not need to create the queue manually. There are examples in the docs and in the integration tests for the library

@erayalakese closing this as no actionable information was provided about how the message is actually being sent. If you can provide more information or a small repro that demonstrates your issue feel free to open this again and I'll take a look
