### ISSUE TITLE
How to use .env variables in @RabbitSubscribe

### ISSUE THREAD

**Issue by Saro-DA** [golevelup/nestjs#169]
Greetings.

Thanks for this great library.

How can I use my .env variables such as queue name in the @RabbitSubscribe decorator?

**Comment by WonderPanda** [comment]
@Saro-DA You can use the `@golevelup/profiguration` package to easily consume ENV in a way that allows you to reference configuration values inside your decorators:

https://github.com/golevelup/ts-ecosystem/blob/master/libs/profiguration/README.md

**Comment by Saro-DA** [comment]
Sorry but the documentation is abstract. Is there any example?
