### ISSUE TITLE
Discovery service throws Exception if no classType property found on imported provider

### ISSUE THREAD

**Issue by michaelkrone** [golevelup/nestjs#17]
When starting an application that is using the DiscoveryService (e.g. by importing the RabbitMQModule or using the discovery package directly), and using a Provider that is not provided in a way so that a `classType` is available, the application fails at startup with the following exception:

```
TypeError
    at Object.getMetadata (/dev/reflect-metadata/node_modules/@nestjs/core/node_modules/reflect-metadata/Reflect.js:354:23)
    at component (/dev/reflect-metadata/node_modules/@nestjs-plus/discovery/lib/discovery.service.js:30:53)
    at filter.x (/dev/reflect-metadata/node_modules/@nestjs-plus/discovery/lib/discovery.service.js:52:65)
    at Array.filter (<anonymous>)
    at DiscoveryService.<anonymous> (/dev/reflect-metadata/node_modules/@nestjs-plus/discovery/lib/discovery.service.js:52:53)
```

This is caused by the `withMetaAtKey` function, which calls the `ReflectMetadata.getMetadata` method which will throw a `TypeError` if the passed target is not of type object.
In my case, importing the `TypeOrmModule` causes the method to throw, because its `TypeOrmModuleOptions` has a classType of `null`.

```
{ name: 'TypeOrmModuleOptions',
  instance:
   { ... },
  classType: null,
  parentModule:
   { name: 'TypeOrmCoreModule',
     instance:
      ...
```

As a workaround I wrap the calls to getMetadata in try/catch which works in my case but may not be an ideal solution: https://github.com/michaelkrone/nestjs-plus/blob/master/packages/discovery/src/discovery.service.ts#L24

**Comment by WonderPanda** [comment]
Interesting, I hadn't encountered any modules or providers in my testing yet that didn't provide a classType. Thanks for reporting this I'll try to publish a fix for it tonight.

@michaelkrone Are you able to share a code snippet or repo that demonstrates how you're registering TypeORM and it's ModuleOptions?

**Comment by WonderPanda** [comment]
https://github.com/WonderPanda/nestjs-plus/pull/18 should address this issue and adds more test coverage around the various different ways of including dynamic/custom providers in Nest Modules
