### ISSUE TITLE
Use Stripe EnabledEvent to restrict valid event types

### ISSUE THREAD

**Issue by bbangert** [golevelup/nestjs#170]
The StripeWebhookHandler allows an arbitrary string for the event type. Stripe doesn't expose a normal valid list type in my searches. I did find `Stripe.WebhookEndpointUpdateParams.EnabledEvent` which appears to be all the valid event types for webhooks (though it includes `*`, which isn't afaik, but maybe it'd be worth supporting that for methods to match all webhooks?).

I duped the StripeWebhookHandler decorator in my project and changed its `eventType` to this, and now appreciate type-checking of my event types. If this sounds good, I'll make a PR for it.

**Comment by WonderPanda** [comment]
@bbangert This sounds like it would be an awesome contribution. I'd definitely prefer to have type checked event names. If you want to create a PR I'd gladly get this merged
