### ISSUE TITLE
Package is not in the npm registry

### ISSUE THREAD

**Issue by caio-emidio** [golevelup/nestjs#171]
Hello,

Today I've try to install this pkg and receive this msg:

>npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nestjs-plus%2frabbitmq - Not found
> npm ERR! 404
> npm ERR! 404  '@nestjs-plus/rabbitmq@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

How i can solve it ?

**Comment by WonderPanda** [comment]
Hi @caio-emidio you should use the package [`@golevelup/nestjs-rabbitmq` ](https://www.npmjs.com/package/@golevelup/nestjs-rabbitmq). Packages that start with @nestjs-plus are old and no longer maintained since we switched to the golevelup organization
