### ISSUE TITLE
nestjs-rabbitmq: Is there any way to read headers & properties of message in consumer?

### ISSUE THREAD

**Issue by yogeshkathayat** [golevelup/nestjs#173]
nestjs-rabbitmq: Is there any way to read headers & properties of message in pubsub consumer ?

**Comment by WonderPanda** [comment]
Hi @yogeshkathayat, the raw message is passed to your consumer as a second argument. If you update the method signature of your consumer to accept `amqplib.ConsumeMessage` as a second argument you should be able to access all information that is available on the original message

**Comment by rennenc** [comment]
Would be great to have this appear in the documentation.
