### ISSUE TITLE
Question about message validation

### ISSUE THREAD

**Issue by jayleeman12** [golevelup/nestjs#174]
As specified [here](https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#type-inference) I understand message validation isn't a part of the built in functionalities. This might be the wrong place to ask (as this is a more of nestjs question), but I'm having trouble understanding how do I use `class-validator` and the nestjs `ValidationPipe` in a RabbitService class.

Any help or guiding would be widely appreciated, thanks in advance!

**Comment by dzanfardino** [comment]
I'm trying to figure this out too, @jayleeman12 have you made any progress?

**Comment by Moonnz** [comment]
Hello, i'm working on dto validation too, but ValidationPipe (like all pipes) work only inside controllers with Http methods or Microservices method (from official nestjs package microservices), i'm thinking of an equivalent interceptors or guards.

**Comment by jblyberg** [comment]
In assessing this package for our use, the inability to capture message patterns in a controller is a dealbreaker since we push all validation concerns to the microservice level. Understand that addressing this is in the roadmap so we'll keep an eye out for future changes.
