### ISSUE TITLE
@golevelup/nestjs-webhooks requires "body-parser" module but not present in deps

### ISSUE THREAD

**Issue by GavinRay97** [golevelup/nestjs#175]
Tiny issue, will just throw `module "body-parser" not found` when running until you install it yourself:

https://github.com/golevelup/nestjs/blob/9e256d12303bde74d3b0e81f57804cf05c3a18f1/packages/webhooks/src/webhooks.middleware.ts#L2

**Comment by WonderPanda** [comment]
Nice catch I'll get this listed as a peerDependency for this package so that you're alerted as part of yarn/npm install but I don't think I'll bundle it with the actual module
