### ISSUE TITLE
Type definition changes between Nest.js versions for `SetMetadata` breaks `@HasuraEventHandler()`

### ISSUE THREAD

**Issue by GavinRay97** [golevelup/nestjs#179]
The following definition from Nest `7.4.3` causes type errors:
```ts
export declare const SetMetadata: <K = string, V = any>(metadataKey: K, metadataValue: V) => CustomDecorator<K>;
```

In the version used internally for the `@golevelup` modules (`6.9.0`), the definition is:
```ts
export declare const SetMetadata: <K = any, V = any>(metadataKey: K, metadataValue: V) => (target: object, key?: any, descriptor?: any) => any;
```

Usage with updated types give the following signature:
```ts
HasuraEventHandler(config: HasuraEventHandlerConfig): (target: any, key: any, descriptor: any) => void | TypedPropertyDescriptor<unknown>
```

Which throws the errors:
```ts
Unable to resolve signature of method decorator when called as an expression.
  Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'void | TypedPropertyDescriptor<(payload: HasuraEvent) => Promise<custom_type | null>>'.
    Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'TypedPropertyDescriptor<(payload: HasuraEvent) => Promise<custom_type | null>>'.
      Types of property 'value' are incompatible.
        Type 'unknown' is not assignable to type '((payload: HasuraEvent) => Promise<custom_type | null>) | undefined'.
          Type 'unknown' is not assignable to type '(payload: HasuraEvent) => Promise<custom_type | null>'
```

This can be fixed by explicitly typing the return here:
```ts
export const HasuraEventHandler = (config: HasuraEventHandlerConfig) => (
  target,
  key,
  descriptor
) => SetMetadata(HASURA_EVENT_HANDLER, config)(target, key, descriptor) as TypedPropertyDescriptor<any>;
```
Either `any` or `TypedPropertyDescriptor` works (`any` is the current working type).

Demo:
![golevelup-set-metadata-type-bug](https://user-images.githubusercontent.com/26604994/91777729-a606d280-ebbe-11ea-982c-49e3af803777.gif)

**Comment by WonderPanda** [comment]
I need to actually start trying to set the repo up so I can properly test and attempt backwards compatibility against different major versions of NestJS... I'm tempted though to just update the dependencies to 7.x as a breaking change and end support for version 6.x though. Wish I had more stats on who was using these libraries in the wild.

Have you ever managed or know good examples of Typescript monorepos building against different version of an external dependency?

**Comment by GavinRay97** [comment]
> Have you ever managed or know good examples of Typescript monorepos building against different version of an external dependency?

Unfortunately not in practice. But in theory, I think you can do it like this with aliases:
```json
{
  "devDependencies": {
    "nestjs-core-7.4": "npm:@nestjs/core@7.4.0",
    "nestjs-core-6.9": "npm:@nestjs/core@6.9.0",
  },
}
```

```ts
import { } from 'nestjs-core-7.4'
import { } from 'nestjs-core-6.9'
```

And you may be able to use an environment variable to dynamically `require`/`import` the package names by version number, so like:
`NESTJS_VERSION="7.4" yarn test`

```ts
const version = process.env.NESTJS_VERSION
const { } = require(`nestjs-core-${version}`)
// etc etc
const { } = require(`nestjs-something-${version}`)
```
