### ISSUE TITLE
when i config errorBehavior = MessageHandlerErrorBehavior.ACK is invalid

### ISSUE THREAD

**Issue by hosea3000** [golevelup/nestjs#187]
because enum  MessageHandlerErrorBehavior.ACK value is 0

next code is not run as expect

![image](https://user-images.githubusercontent.com/12440083/93753986-99145680-fc33-11ea-933a-9c78dd9c0f68.png)

**Comment by WonderPanda** [comment]
@Syuusuke Thanks for reporting. Fix is available in `@golevelup/nestjs-rabbitmq@1.15.2`
