### ISSUE TITLE
question about comparing this package to the official nest- multiple exchange/queues

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#188]
I have 3 microservices, 

**service a**  should  publish to queue in exchange a  and listen to queue in exchange c
**service b**  should listen to routing key from the exchange like "log.*" and publish to exchange b
**service c**  should listen to exchange b and publish to exchange c.

1. can I achieve that in this package?  cause i see that in the current nestjs package i cant define multiple exchanges
2. does it supports nest 7+?

thanks

**Comment by WonderPanda** [comment]
@johnico Yes, you should be able to accomplish this scenario pretty easily. This package allows you to easily define as many exchanges and queues as you want and easily subscribe or publish to them across multiple NestJS apps/microservices.

The lack of flexibility from the official NestJS microservices RabbitMQ implementation is a big part of the reason why this library was created

**Comment by WonderPanda** [comment]
@johnico Perhaps you might find this recent StackOverflow useful as well as it talks about a similar setup: https://stackoverflow.com/questions/64203140/nestjs-microservices-have-one-clientproxy-to-publish-message-to-any-microservi/64249617#64249617

I'm going to close this for now but feel free to open another issue if you run into specific questions when it comes to implementation
