### ISSUE TITLE
wrapping the library in an private npm pacakge 

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#191]
hi 

I am trying to create local npm package lets say called - rabbit-package  ( I need to use it in 5-6 projects, this why I wanted to create a wrapper)

the purpose, for now, is:
1.  to create a Publisher service that will just expose a function to send a message;
2. use the RabbitSubscriber 

My issue now is that the app that uses the package wants also the **AMpqConnection**. and also if I inject it (which I don't want to do), 

my npm pacakage

1-  I created a RabbitModule like that :

```
@Module({})
export class RabModule implements OnModuleInit {
    onModuleInit() {
        console.log('hi')
    }
    static forRoot(
        options: RabbitMQConfig,
    ): DynamicModule {
        const imports = [
            RabbitMQModule.forRoot(RabbitMQModule,options)
        ];
        const providers = [PublisherService, AmqpConnection]
        const exports = [PublisherService]

        return {
            imports: imports,
            providers: providers,
            exports: exports,
            module: RabModule,
        };
    }
}

```
publisher service:

```
@Injectable()
export class PublisherService {

    constructor(private readonly amqp:AmqpConnection) {

    }

    async generate(msg): Promise<any> {
        return  await this.amqp.publish('exchange','route',{test:msg})
    }
}


```

and in my app, I use it as follows on my sharedModule :

```
@Module({
 imports: [RabModule.forRoot({
    exchanges: [
      {
        name: 'scans_update.exchange',
        type: 'topic',
      },
    ],
    uri: 'amqp://user:user@ip:5672'
  }),
],
 controllers: [],
 providers: [],
 exports: [],
})
export class SharedModule{}
```
    
and In my module that injects the shared module, I Have:

```
@Module({
  imports: [SharedModule],
  controllers: [AppController],
  providers: [AppService,PublisherService, AmqpConnection],
})

```

and Now I got the error :

TypeError: Cannot read property 'isConnected' of undefined

so my question i how to import the amqpConnection and expose to my app only the publisher servicer

2 - how to expose the decorator like : RabbitSubscriber

thanks

**Comment by WonderPanda** [comment]
Sorry I don't see how I can help with this, it is not an issue with this library. It doesn't make sense to me why you would need to wrap this library with basically identical functionality. If you need an offline version that isn't served over NPM feel free to take the source code from this repo and use it but I don't have the available time to help you diagnose this. Maybe ask a question on StackOverflow about NestJS
