### ISSUE TITLE
Expose isConnected for rabbitmq healthcheck ? 

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#192]
is it possible to get the isConnected method for healthcheck ?  for example via nest terminus ? 

thanks

**Comment by WonderPanda** [comment]
@johnico I like the idea of this. I'll take a look at modifying the library so that it will be easier to provide health style information unless you're interested in taking a crack at it?

**Comment by johnico** [comment]
@WonderPanda would love to, but I am not sure to find time to do that in a reasonable time :)

**Comment by ssilve1989** [comment]
I recently just created something like this to verify the health of the connection. It hasn't been thoroughly tested yet but seems to work thus far.

```typescript
import { AmqpConnection } from '@golevelup/nestjs-rabbitmq';
import { Injectable } from '@nestjs/common';
import { merge, fromEvent, of, Observable } from 'rxjs';
import { mapTo } from 'rxjs/operators';

@Injectable()
class RabbitMQHealthCheckService {
  constructor(private readonly amqpConnection: AmqpConnection) {}

  check(): boolean {
    return this.amqpConnection.managedConnection.isConnected();
  }

  watch(): Observable<boolean> {
    return merge(
      of(this.check()),
      fromEvent(this.amqpConnection.managedConnection, 'close').pipe(mapTo(false)),
      fromEvent(this.amqpConnection.managedConnection, 'error').pipe(mapTo(false)),
      fromEvent(this.amqpConnection.managedConnection, 'connect').pipe(mapTo(true))
    );
  }
}
```

**Comment by underfisk** [comment]
I'll be taking a look into exposing this to also be compatible with Terminus, @ssilve1989 thanks for also sharing your implementation

**Comment by manuschillerdev** [comment]
since this task i completed - is there an example how to do a health check with `terminus` and `golevelup/nestjs` available somewhere?

**Comment by underfisk** [comment]
> since this task i completed - is there an example how to do a health check with `terminus` and `golevelup/nestjs` available somewhere?

You can implement the one that @ssilve1989 posted, just convert to a terminus health checker and it will work

**Comment by yunicz** [comment]
> > since this task i completed - is there an example how to do a health check with `terminus` and `golevelup/nestjs` available somewhere?
> 
> You can implement the one that @ssilve1989 posted, just convert to a terminus health checker and it will work

Any suggestion how to convert that into a terminus health checker? I tried it using this code, but 
following line:

`const isHealthy = await lastValueFrom(this.watch()); `

resulted in promise that never resolved

```
  import { AmqpConnection } from '@golevelup/nestjs-rabbitmq';
  import { Injectable } from '@nestjs/common';
  import { HealthIndicatorResult } from '@nestjs/terminus';
  import { merge, fromEvent, of, Observable, lastValueFrom } from 'rxjs';
  import { map } from 'rxjs/operators';

  @Injectable()
  export class RabbitMQHealthService {
    constructor(private readonly amqpConnection: AmqpConnection) {}

    async statusCheck(): Promise<HealthIndicatorResult> {
      const isHealthy = await lastValueFrom(this.watch());

      if (isHealthy) {
        return {
          rabbitmq: { status: 'up' },
        };
      }

      return {
        rabbitmq: { status: 'down' },
      };
    }

    check(): boolean {
      return this.amqpConnection.managedConnection.isConnected();
    }

    watch(): Observable<boolean> {
      return merge(
        of(this.check()),
        fromEvent(this.amqpConnection.managedConnection, 'close').pipe(map(() => false)),
        fromEvent(this.amqpConnection.managedConnection, 'error').pipe(map(() => false)),
        fromEvent(this.amqpConnection.managedConnection, 'connect').pipe(map(() => true)),
      );
    }
  }
```

**Comment by jeremybradbury** [comment]
@yunicz perhaps I can help? not sure the rest of this snippet is correct, but I was able use a proprietary client library to check the connection and adding an "as" statement worked for me.

```
      if (isHealthy) {
        return {
          rabbitmq: { status: 'up' },
        } as HealthIndicatorResult
      }

      return {
        rabbitmq: { status: 'down', message: 'RabbitMQ is not connected' },
      } as HealthIndicatorResult;
```

**Comment by theocerutti** [comment]
@yunicz did you find a solution ? I have the same issue

**Comment by Lamarcke** [comment]
If anyone's still interested, here's my current implementation for `@nestjs/terminus`:
```typescript
@Injectable()
export class RabbitMQHealthCheckService extends HealthIndicator {
    constructor(private readonly amqpConnection: AmqpConnection) {
        super();
    }

    async check(): Promise<HealthIndicatorResult> {
        const isConnected = this.amqpConnection.managedConnection.isConnected();
        const status = this.getStatus("rabbitmq", isConnected);
        if (isConnected) {
            return status;
        }

        throw new HealthCheckError("RabbitMQ is not reachable", status);
    }
}
```
