### ISSUE TITLE
NestJS Lifecycle events support / Webpack HMR

### ISSUE THREAD

**Issue by mariotacke** [golevelup/nestjs#193]
I installed the `@golevelup/nestjs-rabbitmq` package and I'm trying to use it in conjunction with hot module replacement / HMR.

The issue I'm seeing is that the RabbitMQ connection and channel does not get terminated upon `app.close()`. This causes additional connections to be made after reload which results in lingering connections and channels.

Ideally, I'd like for the connection to terminate upon any of the lifecycle methods outlined in the NestJS docs: [Lifecycle events: Application Shutdown](https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown)

Any idea how this could be accomplished?

## My Setup

`main.ts`
```ts
import { ConfigService } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

declare const module: any;

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  // these are the relevant HMR lines
  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
}

bootstrap();
```

`app.module.ts`
```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { NewEmailReceivedConsumer } from './messaging/consumers/new-email-received.consumer';

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: 'inbox',
          type: 'topic',
        },
      ],
      uri: process.env.RABBITMQ_CONNECTION_STRING,
    }),
    AppModule,
  ],
  controllers: [AppController],
  providers: [
    AppService,
    NewEmailReceivedConsumer,
  ],
})
export class AppModule {}
```

`new-email-received.consumer.ts`
```ts
import { RabbitSubscribe } from '@golevelup/nestjs-rabbitmq';
import { Injectable } from '@nestjs/common';
import * as amqplib from 'amqplib';

@Injectable()
export class NewEmailReceivedConsumer {
  @RabbitSubscribe({
    exchange: 'inbox',
    routingKey: 'event.new-email-received',
    queue: 'inbox.new-email-received',
    allowNonJsonMessages: true,
  })
  public async handler(message, rawMessage: amqplib.ConsumeMessage) {
    if (!message) {
      return;
    }

    // code
  }
}

```

## References
- https://docs.nestjs.com/fundamentals/lifecycle-events
- https://docs.nestjs.com/recipes/hot-reload#hot-module-replacement

**Comment by mariotacke** [comment]
For anybody interested, I found a way to do it; probably not as clean as it could be, but it works.

I modified the `AppModule` from above by implementing `OnApplicationShutdown` and calling `close()` on the managed connection. Unfortunately, `AmqpConnection` does not expose the `close()` method from `amqp-connection-manager` (`AmqpConnectionManager`) so I had to resort to an `<any>` type override before accessing the `_managedConnection` (it is `private`) and calling close:

```ts
@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: 'inbox',
          type: 'topic',
        },
      ],
      uri: process.env.RABBITMQ_CONNECTION_STRING,
    }),
    AppModule,
  ],
  controllers: [AppController],
  providers: [
    AppService,
    NewEmailReceivedConsumer,
  ],
})
export class AppModule implements OnApplicationShutdown {
  private _amqpConnection: AmqpConnection = null;

  constructor(private readonly amqpConnection: AmqpConnection) {
    this._amqpConnection = amqpConnection;
  }

  onApplicationShutdown() {
    if (this._amqpConnection) {
      (<any>this._amqpConnection)._managedConnection.close();
    }
  }
}
```

**Comment by johnico** [comment]
@mariotacke hi, is it happen to you only with HMR?  cause as I can see when the app is closed/crashed (process.exit) the connection in the rabbit management are cleared

**Comment by WonderPanda** [comment]
@mariotacke I think this is a good addition. I'll look at integrating it directly into the RabbitMQ module so that you don't have to manually do it inside of a modified App Module or rely on private member variables

**Comment by mariotacke** [comment]
@johnico, correct, this only happens with HMR since it technically does not "restart" the application and instead hot-reloads the modules.

@WonderPanda, thank you, that would be wonderful!

**Comment by WonderPanda** [comment]
@mariotacke Out of curiosity what version of the library are you using? There has been a `getter` on managedConnection for quite some time now:

```
get managedConnection(): amqpcon.AmqpConnectionManager {
    return this._managedConnection;
  }
```

So you definitely shouldn't need to cast the connection as `any` in order to get your current solution to work. Either way I'll incorporate shutdown logic directly into the Rabbit module but just wanted to make sure you weren't running on a super outdated package

**Comment by mariotacke** [comment]
@WonderPanda, I'm on `1.15.2` and just checked: sure enough, I can use the exposed `managedConnection` instead. For some reason I did not notice the getter when I looked through the source. 🤷🏻‍♂️ Thanks for the tip!

Just for reference, this is what I am doing now:
```ts
export class MessagingModule implements OnApplicationShutdown {
  constructor(private readonly _amqpConnection: AmqpConnection) {}

  onApplicationShutdown() {
    if (this._amqpConnection) {
      this._amqpConnection.managedConnection.close();
    }
  }
}

```
