### ISSUE TITLE
How to ack message after writing to Database

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#194]
I have a subscribe that receive the message, then I need to write the message to the DB and then send another message to the queue

my question is how the ack the message after i finished with database actions

as far as I see in the docs the new Nack(true). is the smth I am looking for?

so if the database action has been failed, should I return new Nack(true). , for requeueing  ? 

thanks

**Comment by WonderPanda** [comment]
@johnico By default, the message will be acked as soon as your handler has finished executing. So assuming the DB operation succeeds you don't have to do anything. Under normal circumstances you do not need to manually ack. 

If you want to requeue on error you can just wrap your operation in a `try/catch` and return `Nack(true)` from the handler
