### ISSUE TITLE
Messages from web UI does not reach RabbitSubscribe

### ISSUE THREAD

**Issue by ArnonAfriat** [golevelup/nestjs#195]
I have a service with the simple handler configuration:
```
  @RabbitSubscribe({
    exchange: config.get('queues').consumers.gatewayQueue.exchange, // foo
    routingKey: config.get('queues').consumers.gatewayQueue.routingKey, //foo.bar.1
    queue: config.get('queues').consumers.gatewayQueue.bindingQueue,  //foo.queue
  })
  public pubSubHandler(msg: any): Promise<void> {
    console.log(`Received message: ${JSON.stringify(msg)}`);
    return;
  }
```

When the applications starts, I can see in the rabbitmq web interface:
1. New connection has been created
2. New exchange has beed created

I generate the expected queue manually in the ui and bind it properly to the exchange.
When publish message from the web interface, with the proper configurations, I see the data in the queue but, it does not invoke the callback in my app.

If I try to publish a message using the same configurations from the same application like so when publisherService is RabbitPublisher:
```
  public publish() {
    const options: AmqpPublishOptions = {
      exchange: 'foo',
      routingKey: 'foo.bar.1',
    };
    const queueMessage = {
      data: { key: 'string' },
      eventName: 'msg',
    } as QueueMessage;
    return this.publisherService.sendMessage(options, queueMessage);
  }
```

I can see:
1. Application call back works as expected and logs the message
2. Web interface queue shows the new published message along with the other messages that I published in the UI and didn't went thru.

The only visible difference I see when looking at the messages in the queue, is that messages sent in the web interface has a property `delivery_mode` with value 1 or 2 messages sent from the nest application does not have this property.

**Comment by WonderPanda** [comment]
What do the messages look like that you're publishing through the UI? Are they in JSON format? The default configuration for handlers expects that messages will be proper JSON payloads otherwise they will not be passed to the handler

**Comment by ArnonAfriat** [comment]
Yes it is proper JSON payload.

**Comment by WonderPanda** [comment]
> Yes it is proper JSON payload.

Can you please share the exact message contents that you are publishing through the RabbitMQ UI just so I can double check it?

**Comment by ArnonAfriat** [comment]
Update:
As part of debugging, I install pika package for python and wrote a simple script for consuming messages based on the rabbitmq manual.
connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
```
channel = connection.channel()

def callback(ch, method, properties, body):
    print(" [x] %r:%r" % (method.routing_key, body))

print(channel)

channel.basic_consume(queue='gateway.queue', on_message_callback=callback, auto_ack=True)
```
I accidentally ran this script before adding the 'channel.start_consume()' loop, and all of a sudden, everything is fine - messages sent from either Nest publisher or web ui, all arrive to the the nest listener, with or without strict json format (sending a plain "hello" works).

The only thing that I assume happened is that the python script initialise the 'auto_ack=True' which is not initialise in the Nest app explicitly.
