### ISSUE TITLE
Bug (?)- Rabbitmq restarting without throwing or log a message while publish to exchange that does not exist

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#198]
while trying to publish to an unknown exchange  I see a restarting message like :

```
[Nest] ..... [NestApplication] Nest application successfully started +22ms
[Nest] ..... [AmqpConnection] Successfully connected a RabbitMQ channel
```
 
and the rabbit lost his connection and connect again, 
I guess it is a good behavior but there is no error or error handling for that

code from my controller
```
@Get(':id')
  async test(
    @Param('id') id: string,
  ) {
         this.amqpConnection.publish('doesNotExist.exchange', 'routingKey', {data:"test"});
  }
```

even with Try/catch, i don't get any data/exception

**Comment by underfisk** [comment]
@johnico I would need a repro, if you can provide one i'll investigate this further
