### ISSUE TITLE
Improve Package Release Pipeline

### ISSUE THREAD

**Issue by WonderPanda** [golevelup/nestjs#20]
- [x] Integrate with Semantic Commits
- [x] Include Changelogs
- [ ] Investigate automatically publishing from CI/CD (Travis) on commits to master

Reference:
https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6

**Comment by underfisk** [comment]
I believe we'll be following Nx with Github actions in long term. I'm closing this because it looks outdated
