### ISSUE TITLE
rabbitmq - retries connection attempts 

### ISSUE THREAD

**Issue by johnico** [golevelup/nestjs#200]
HI 
is there an option to support retries connection?
means that the service will try to reconnect rabbit by config params for example:

`retryAttempts : 10`
`retryDelay : 10000` /ms

**Comment by underfisk** [comment]
I'll be working on this issue alongside what was proposed at #203

**Comment by Adi1231234** [comment]
Hey, does it exist today?

**Comment by mrsoneji** [comment]
BUMP
