### ISSUE TITLE
register RPC handler based on a condition

### ISSUE THREAD

**Issue by akalitenya** [golevelup/nestjs#201]
Thank you for this library!

I need a way to specify (through ENV variables) which RPC handlers to register for a specific app instance:
- Docker instance 1: handlerA, handlerB
- Docker instance 2: handlerB, handlerC 

I read about Conditional Handler Registration, but It seems like it can only register all handlers or none of them.

```
  @RabbitRPC({
    exchange: 'C',
    routingKey: 'c'
    queue: 'q1',
    register: false // a suggested way to indicate if a handler should be registered
  })
  async handlerC(request: any, context: any) {
   ...
  }
```

Maybe there is a way to create/import separate Service (that contain only required handlers) for a specific app instance?

**Comment by WonderPanda** [comment]
@akalitenya RPC and Subscribers will only be discovered if they are part of Services that are actually included in a module. You should be able to conditionally include your Services/Injectables in the `providers` array of your module configuration based on ENV. I think this would be the easiest way to accomplish what you're asking. 

Let me know if this will help your use case

**Comment by akalitenya** [comment]
Thank you! 
I will try this approach.

**Comment by akalitenya** [comment]
@WonderPanda  
It works!
