### ISSUE TITLE
Interceptors don't play nice with @RabbitSubscribe

### ISSUE THREAD

**Issue by chromey** [golevelup/nestjs#204]
I ran into the same issue as #53 and also created a small repo to demo the problem: https://github.com/chromey/rabbit-issue

Basically, when using global interceptors, they will intercept methods annotated with `@RabbitSubscribe` and mark the `ExecutionContext` as type `http`. `context.switchToHttp().getRequest()` and `getResponse()` even return objects, but they are lacking methods defined in the actual express objects.

Let me know if you need more details.

**Comment by WonderPanda** [comment]
Is the logging interceptor in your example indicative of the type of global interceptor you're using in your actual app? Can you add some custom code to simply skip the logic in the interceptor based on the nature of the handler?

**Comment by WonderPanda** [comment]
@chromey Does this fix your use case? You can easily add small conditional logic inside your Interceptor based on the handler so that HTTP request are treated separately from messages coming through RabbitMQ. Try updating the code in your Logging Interceptor to this:

```typescript
import { RABBIT_HANDLER } from '@golevelup/nestjs-rabbitmq';
import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
} from '@nestjs/common';
import { Response } from 'express';
import { Observable } from 'rxjs';

@Injectable()
export class LoggingInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const handler = context.getHandler();
    const meta = Reflect.getMetadataKeys(handler);

    if (meta.includes(RABBIT_HANDLER)) {
      return next.handle();
    }

    console.log('Context Type: ' + context.getType()); // says 'http'
    const res = context.switchToHttp().getResponse<Response>();
    console.log('Response: ' + res);
    res.setHeader('oops', 'does not work'); // TypeError: res.setHeader is not a function
    return next.handle();
  }
}
```

**Comment by WonderPanda** [comment]
Added a utility to the library so that you don't have to duplicate the logic above. Docs are here: https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#usage-with-interceptors

It is available in `@golevelup/nestjs-rabbitmq@1.16.0` on NPM

**Comment by chromey** [comment]
@WonderPanda Thanks a lot, that's just what I needed! I had another workaround in place that basically checked the prototype of the request object for the existence of certain HTTP methods, but this is a lot cleaner and more expressive. Thanks again.

**Comment by WonderPanda** [comment]
Awesome! Glad to hear that this helped you out

**Comment by rubiin** [comment]
@WonderPanda I having similar issue
