### ISSUE TITLE
"Killer" message causing the service to disconnect from rabbitmq while trying to process the message

### ISSUE THREAD

**Issue by rennenc** [golevelup/nestjs#207]
I'm using
"@golevelup/nestjs-rabbitmq": "^1.15.2"
"amqp-connection-manager": "^3.2.0",
"amqplib": "^0.5.5",

I am experiencing a phenomenon where particular large messages are causing my nestjs service to disconnect from rabbitmq. After a few seconds it then reconnects, fails again and disconnects, and so on forever.

I am sending messages from a python service to my NestJs service over rabbitmq. My NestJS service is subscribing using RabbitSubscribe decorator, specifying a custom error handler, so that even if the message is not a valid json, it would still ACK it.

I can see that some large messages (> 700 bytes), it's causing the nestjs to disconnect from rabbitmq and the consumers for that queue is dropping accordingly. The service is still up, tries to reconnects, and experiences the same issue over and over again. The error handler that I specified in the decorator is not being called at all. The message is a valid json string, and when using a python service - the python code can be easily process and parse it to a json object.

Here is a sample of such message:
https://drive.google.com/file/d/1ic8RIFciaDRgenTQaWlb2wf05-9hXL2N/view?usp=sharing

**Comment by rennenc** [comment]
Hi team,
I'm not sure what's the desired method to report issues. I find this to be a pretty critical one and would be happy to get an acknowledgement that this didn't go under your radar.

**Comment by WonderPanda** [comment]
Hi @rennenc
I apologize for not acknowledging this issue sooner. I could have done a better job in letting you know that it had been seen. Opening Github issues is definitely the preferred way of reaching out for this kind of thing.

That being said, there is currently no team behind this project. I'm a single developer maintaining all the packages in this repo and I have lots of obligations for my day job and in my own personal life that prevent me from being able to effectively tackle every issue that is raised in a timely manner.

Are you currently using `@golevelup/nestjs-rabbitmq` in a work/corporate setting? If so I'd be willing to to start considering priority bug support or the ability for people and organizations to directly influence the roadmap of things I'm working on in return for some kind of sponsorship or financial support.

I'll do my best to get to your issue but the RabbitMQ package is lower on my personal priority list at the moment as I have many new features and packages I'd like to work on as part of the broader NestJS ecosystem. I don't have any concrete timeline I can share right now as to when that will happen, especially with the holidays coming up.

Thanks for understanding

**Comment by WonderPanda** [comment]
@rennenc Can you please provide some additional information? Is your consumer using `@RabbitSubscribe` or is it using `@RabbitRPC` to return a response to the publisher of the message?

What type of workload is being performed when you receive the message? 

I just set up a quick app and published your killer message through it and it worked just fine without any errors. Maybe something is timing out in your handler?

Are you able to provide a code sample that reproduces this issue reliably? It's hard to do any further investigation without being able to reproduce the issue. There are a ton of unique conditions that are specific to your application and architecture

**Comment by WonderPanda** [comment]
@rennenc Happy new year! Hopefully you had the chance to rest and relax. Just wondering if there is any additional information that might be available to help deal with this issue?

**Comment by WonderPanda** [comment]
Feel free to open this back up again if there's any more information available to go off of. Right now it isn't actionable
