### ISSUE TITLE
how to configure mutilple connections(channel) from single consumer in @golevelup/nestjs-rabbitmq .i.e. set maxconcurrentConsumers and concurrentConsumers

### ISSUE THREAD

**Issue by ajayprasad1982** [golevelup/nestjs#208]
With current implementation ,we do not have option to configure maxConcurrentConsumers and concurrent Consumers for consumer.One consumer has only one connection in RabbitMQ as cited screen shot 
![image](https://user-images.githubusercontent.com/13506045/101851453-96196a00-3b81-11eb-8e8c-33e7cf05909d.png)
code snippet as  below 

```typescript
@RabbitSubscribe({
    exchange: Rabbitmq.TOPIC_EXCHANGE_NAME,
    routingKey: Rabbitmq.UPLOAD_DOC_ROUTING_KEY_NAME,
    queue: Rabbitmq.UPLOAD_DOC_QUEUE_NAME,
    queueOptions: {
      durable: true,
      exclusive: false,
      autoDelete: false,
    },
  })
  public async pubSubHandler(msg: {}) {
    console.log(`Received message: ${JSON.stringify(msg)}`);
  }
```

but the expected behavior would be able to set the concurrent consumers for a consumer, please find the screenshot for the expected behavior. The below screenshot shows one consumer has 4 (logical)connections
![image](https://user-images.githubusercontent.com/13506045/101851738-222b9180-3b82-11eb-92e5-e9de3112c2fc.png)

**Comment by underfisk** [comment]
@ajayprasad1982 This was implemented with the new channels options
