### ISSUE TITLE
ts-jest not working properly when mocking falsy values

### ISSUE THREAD

**Issue by micalevisk** [golevelup/nestjs#211]
Great lib!  
but I think the tests in `(2)` below should pass, right?

```typescript
interface TestInterface {
  someNum: number;
  someBool: boolean;
}

describe('Mocks', () => {
  it('should work with truthy values properties', () => {
    const mock = createMock<TestInterface>({
      someNum: 1,
      someBool: true
    });

    expect(mock.someNum).toBe(1);
    expect(mock.someBool).toBe(true);
  })

  it('should work with falsy values properties', () => { // (2)
    const mock = createMock<TestInterface>({
      someNum: 0,
      someBool: false
    });

    expect(mock.someNum).toBe(0);
    expect(mock.someBool).toBe(false);
  })
})
```

but I'm getting this error:
```
  Mocks
    ✓ should work with truthy values properties (2 ms)
    ✕ should work with falsy values properties (2 ms)

  ● Mocks › should work with falsy values properties

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: [Function mockConstructor]

      37 |     });
      38 | 
    > 39 |     expect(mock.someNum).toBe(0);
         |                          ^
      40 |     expect(mock.someBool).toBe(false); // (same error with this one)
      41 |   })
      42 | })
```

Note that if using methods that returns falsy values works as expected -- which could be a workaround for now I guess.

### Environment

```
jest: v26.6.3
@golevelup/ts-jest: v0.3.0
```

**Comment by micalevisk** [comment]
basically this happen due to the condition on L37 bellow:
https://github.com/golevelup/nestjs/blob/00b2fd231a6b8e883bf5f6b18d897f55d2d09a82/packages/testing/src/mocks.ts#L35-L43
because `checkProp ?` will be evaluated to `false` when `obj[prop]` is a falsy value. 

So if you change that to something like
```diff
const checkProp = obj[prop];

- const mockedProp = obj[prop]
+ const mockedProp = (prop in obj)
  ? typeof checkProp === 'function'
    ? jest.fn()
    : checkProp
  : propName === 'then'
  ? undefined
  : createRecursiveMockProxy(propName);
```
it works as expected :smile: 

the same applies to this snippet:
https://github.com/golevelup/nestjs/blob/00b2fd231a6b8e883bf5f6b18d897f55d2d09a82/packages/testing/src/mocks.ts#L84-L88

**Comment by Sinmson** [comment]
I don't think that this works "as expected".

Is there a reason to not change it like @micalevisk suggested?

**Comment by WonderPanda** [comment]
@micalevisk Thanks for catching this and for the clear repro

**Comment by WonderPanda** [comment]
This is fixed in the new package version:
`@golevelup/ts-jest@0.3.1`
