### ISSUE TITLE
RabbitMQ RPC nack doesn't reject the promise

### ISSUE THREAD

**Issue by akoidan** [golevelup/nestjs#217]
With nestJS rabbit MQ I use RPC from one server to another one. What I basically want is `await this.amqpConnection.request` to reject the promise when the consumer throw an error. As I understand from [this](https://www.rabbitmq.com/dlx.html) and [this](https://stackoverflow.com/a/28817796/3872976)  and [this](https://www.rabbitmq.com/amqp-0-9-1-quickref.html#basic.nack) documentation when you **NACK** (negative ack) the message it should put the RPC response to a corresponding queue with an error information which would be passed to a client.  Here's some code example:

```typescript
  try {
      const result = await this.amqpConnection.request({
        exchange: 'user',
        routingKey: 'test',
        queue: 'test',
        payload,
      });
      console.log(result);
    } catch (e) {
      console.error(e); // I expect this flow !!! 
    }
    
```
And consumer looks like:
```typescript
  @RabbitRPC({
    exchange: 'user',
    routingKey: 'test',
    queue: 'test',
    errorBehavior: MessageHandlerErrorBehavior.NACK
  })
  public async rpcHandler(msg: UserRmqDto): Promise<any> {
     throw Error("Error text that should be proxied to console.error"):
  }
  
```

But the message doesn't even return to the client. Client gets rejected after a timeout, rather because of an error during consumer processing. If my understanding is not correct I would like to know if there's a builtin mechanism with nestjs to reject the message w/o manually creating some response types for an error and handling it on a client.

**Comment by WonderPanda** [comment]
@akoidan None of the links that you've provided mention returning message for negative acknowledgement in an RPC scenario. You have the option to use a Dead Letter Queue for nacked messages, however this will be different from the direct reply queue which is used to handle RPC so it will not show up automatically back at the requester.

If you need to return error information from the consumer to the requester you should ack with a response that represents error information that is actionable (basically what you describe at the end of your issue).

However, this does seem to be a common request from the community so it is possible that a more opinionated error handling situation could be built for this library which could take care of some of the boilerplate.

What would the desired API look like in your opinion for this? Would you like to be able to throw specific Errors that map to common failure cases? This could be similar to the HTTP related exception classes that come with NestJS but designed to be sent back over RPC

**Comment by akoidan** [comment]
@WonderPanda what's is the common pattern when error is thrown on the consumer? I couldn't seem to find any information about RPC communication in this case. 

From my understanding when an error happens on the consumer. The provider should be always notified with this information. Waiting for another TIMEOUT_SECONDS should not be the case.

**Comment by WonderPanda** [comment]
I think there might be some confusion about how RPC is working under the hood. There is no persistent connection between the producer and the consumer. Think of it like a mail system. The producer sends out a message with a request for data. It doesn't maintain a connection waiting for a response, it just includes a return address where a response can be eventually sent to. If the consumer never returns a message then this is obviously a problem for the consumer.

Its up to you to send a message back to the producer of the original request. Just wrap your handler in the consumer in a try/catch and send back a message that indicates that there was some failure. The details of what the contents of that message are should be up to you and your application requirements.

This library is intentionally not opinionated with these kinds of situations because it varies considerably depending on your requirements. However, if you would like for there to be an opinionated built in functionality for this I'm open to considering it. Please share what you think that the API for this should look like

**Comment by akoidan** [comment]
@WonderPanda ok thank you for the answer. As I understand in rabbit RPC best practice it's not required to send a message. 

However with the RPC pattern usually means there's a forward and backwards communication. Despite implementation encapsulated under it doesn't maintain the persistent connection the RPC API provided to the end user should fully abstracted from it. When you send an http request over http3 you don't think that you need to confirm each UDP packet, right?

Closing this issue as I got the answer, which current implementation of RPCrabbitMQ doesn't support error handling. 

If someone require this in the future I end up with the following wrapper:

Client helper
```typescript
@Injectable()
export default class RmqRpcService {
  public constructor(
    private readonly amqpConnection: AmqpConnection,
  ) {
  }

  public async callRemote<T>(
    {
      exchange,
      routingKey,
      queue,
      payload,
    }: {
      exchange: string;
      routingKey: string;
      queue: string;
      payload: any;
    },
  ): Promise<T> {
    const requestOptions: RequestOptions = {
      exchange,
      routingKey,
      queue,
      payload,
    };
    const result: any = await this.amqpConnection.request(requestOptions);
    if (result.error) {
      throw Error(result.error);
    }
    return result.data as T;
  }
}
```
Consumer helper:
```typescript
export function RpcListener(target: any, propertyKey: string, descriptor: PropertyDescriptor): void {
  const original = descriptor.value;
  // eslint-disable-next-line no-param-reassign
  descriptor.value = async function value(...args): Promise<any> {
    try {
      const data = await original.apply(this, args);
      return { data };
    } catch (error: any) {
      return { error: error?.message ?? String(error) };
    }
  };
}
```

Consumer usage:

```typescript
  @RabbitRPC({
    exchange: 'exchangeKey',
    routingKey: 'routingKey',
    queue: 'queue',
  })
  @RpcListener
  public async handleRpcMessage(
    msg: any,
  ): Promise<Date> {
    return {hello: 'world'};
  }
```

**Comment by WonderPanda** [comment]
@akoidan Thanks for sharing your implementation. I guess the point that I was trying to make is that this library is intentionally flexible when it comes to how people want to handle their own errors. Your approach might work great for some users but be a big design issue for others depending on the nature of their application. For this reason I've left it up to people to implement their own.

If there's enough interest from the community I would consider adding in an "official" error handling mechanism for RPC that might be similar to what you've shown. I think that if I were to do that it would need to have better support for different kinds of logical error scenarios as opposed to just relying on having an `error` property on the response

**Comment by Setitch** [comment]
@WonderPanda I think his implemantation should be added to the library - with example uses and documentation why he used that - so others can not only use it or implement theirs own. Nest is opinionated, so maybe its good to opinionate some flows and just leave users the ability to reimplement them themselves?

**Comment by WonderPanda** [comment]
@Setitch I'll consider something similar for the V2 roadmap
