### ISSUE TITLE
inject AmqpConnection in my service

### ISSUE THREAD

**Issue by dvirarad** [golevelup/nestjs#221]
Hi
I have issue when I am trying to connect to
This is my module that connects to RabbitMQ
`
@Module({
  imports: [
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      useFactory: async (config: ConfigService) => {
        const exchanges = await getExchanges(config);
        return getRabbitMQConfig(exchanges, config);
      },
      inject: [ConfigService],
    }),
  ],
})
export class AmqpSubscribeModule {}
`
When I have a module that I want to subscribe I'm just importing איק AmqpSubscribeModule module.

But when I am trying to use AmqpConnection in the service I am getting error

Nest can't resolve dependencies of the service (LoggerService, ConfigService, ?). Please make sure that the argument AmqpConnection at index [2] is available in the service context.

**Comment by WonderPanda** [comment]
@dvirarad If you are manually wrapping around the built in RabbitMQ Module you need to add `RabbitMQModule` to the exports array of your wrapper module. Then all modules that import your wrapper will have access to `AmqpConnection`

``` typescript
import { AmqpConnection, RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { Module } from '@nestjs/common';

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      uri: `amqp://rabbitmq:rabbitmq@localhost:5672`,
      exchanges: [
        {
          name: 'test-exchange',
          type: 'topic',
        },
      ],
    }),
  ],
  providers: [],
  exports: [RabbitMQModule],  // this line is important
})
export class WrapperModule {}
````

**Comment by farzadso** [comment]
I wish we didn't have to `export` it. Other libraries (e.g., the `@nestjs/mongoose` library) don't require this extra `export` line. I think the reason is that the `RabbitMQModule` itself doesn't directly export the `AmqpConnection`.

I chose not to go with this model and create a service for my wrapper module that exposes functions that `create` or `read` messages.

**Comment by gilvex** [comment]
Is here an update on that?
