### ISSUE TITLE
Can you provide an example of the webhook or further explain in the docs

### ISSUE THREAD

**Issue by twigs67** [golevelup/nestjs#222]
Hello,

Using this as a service does not seem to be working.
```
@Injectable()
class PaymentCreatedService {
  @StripeWebhookHandler('payment_intent.created')
  handlePaymentIntentCreated(evt: StripeEvent) {
    // execute your custom business logic
  }
}
```

I'm able to change the webhook secret key and the request still goes through. Also, I can't find `StripeEvent` is this a stripe type?

**Comment by WonderPanda** [comment]
@twigs67 Are you able to create a small example reproduction of the webhook secret not being validated?

Event payloads are available from the `stripe` package. I should update the docs to show this better but you should be able to get type safety like this:

``` typescript
import { StripeWebhookHandler } from '@golevelup/nestjs-stripe';
import { Injectable } from '@nestjs/common';
import Stripe from 'stripe';

@Injectable()
export class StripeService {
  @StripeWebhookHandler('account.updated')
  handlePaymentIntentCreated(evt: Stripe.AccountUpdateParams) {
    console.log(evt);
  }
}
```

**Comment by WonderPanda** [comment]
@twigs67 Feel free to open this up again if more info or a reproduction for the validation not working is available. Closing for now

**Comment by audiBookning** [comment]
Thanks for the example.
But i had some problems with it. I will show here how i resolved it for anyone who stumble on this issue.
Correct me if i am wrong.

 The `Stripe.AccountUpdateParams` is the payload used for creating an account, not the one for an event in response to it.
As seen here in the [API](https://stripe.com/docs/api/events/types#event_types-account.updated) the event returns an [account object](https://stripe.com/docs/api/events/types#account_object). So the correct parameter type should be:

```typescript
import { StripeWebhookHandler } from '@golevelup/nestjs-stripe';
import { Injectable } from '@nestjs/common';
import Stripe from 'stripe';

@Injectable()
export class StripeService {
  @StripeWebhookHandler('account.updated')
  handlePaymentIntentCreated(evt: : Stripe.Event) {
    console.log(evt);
    const account = evt.data.object as Stripe.Account;
  }
}
```
Unfortunately, in stripe, the type of ` evt.data.object` is an empty object `{}`, so unless they correct it in their code (or us with custom dt.ts) with an union of types, we have to make do.

This is kind of confusing and this issue helped me a lot. I agree that you should update the docs to show this better 🙂.

**Comment by tomups** [comment]
Just wanted to add that it's possible to have strongly typed events by using https://github.com/kgajera/stripe-event-types :

![image](https://github.com/golevelup/nestjs/assets/690217/d67212ba-c91b-48f5-9001-d6038ede7c25)

Unfortunately we have to repeat the event type in the method so the TypeScript discriminator will kick in, but it's not too bad.
