### ISSUE TITLE
One handler bound to multiple exchanges

### ISSUE THREAD

**Issue by theabuitendyk** [golevelup/nestjs#225]
Hello 👋 I'm working on adding support for message retries to my queues. I'd like to use the errorHandler to catch errors and publish the message to a delayed message exchange so that I can space out the retries. If I have one handler for the initial process attempt and another for the retries I end up with a lot of duplicated config & retry logic that I'll need to keep in sync.

Are there any plans to add support for binding one handler to multiple exchanges using the RabbitSubscribe decorator? I found a mention of it in this thread: https://github.com/golevelup/nestjs/issues/151

**Comment by WonderPanda** [comment]
Hey @theabuitendyk this is definitely a common ask from the community. I've had it on my radar for a long time now to take a look at improving the error handling and retry scenarios but I think it would make a lot of sense to tackle this with some breaking changes and release a 2.x version that addresses this and a number of other architectural improvements at the same time.

Would you be interested in participating in a bit more discussion around what you think that a good feature set and API for this would look like? Based on the number of people who've asked similar things in Github Issues and on Discord I'm wondering about starting up a Discussion in the GitHub repo to try and gather some more requests and feedback from the community to make sure version 2.x is a huge improvement over the current library.

Let me know what you think!

**Comment by theabuitendyk** [comment]
@WonderPanda Thanks for the quick response! That sounds great and I'd be happy to join the discussion. I'll try to find some time over the weekend to think about a reasonable interface for retries.

Out of curiosity what are the other main architectural improvements?

**Comment by WonderPanda** [comment]
Other than error handling and retry logic the main ones that have been brought up are allowing for a more pluggable design around message parsing/serialization/deserialization/validation.

The current API made a lot of assumptions around JSON messages being a standard and so I had to tack on functionality for other patterns in a way that wasn't as composable as I would have liked to avoid making any premature breaking changes and forcing a version 2.x.

Eg: https://github.com/golevelup/nestjs/issues/174 and https://github.com/golevelup/nestjs/issues/137

**Comment by WonderPanda** [comment]
Just created an official discussion to talk about this further https://github.com/golevelup/nestjs/discussions/227

Please feel free to put in any thoughts or ideas you have about what the ideal interface for you would look like for the problems you're currently trying to tackle!

**Comment by WonderPanda** [comment]
Closing this in favor of having a continued discussion with the community over in #227
