### ISSUE TITLE
RabbitMQ: pass message headers to amqpConnection.request() 

### ISSUE THREAD

**Issue by fabricemathis** [golevelup/nestjs#229]
I'm surprised that it is possible to pass message headers through `amqpConnection.publish`, with the help of the `options` parameter, but not through `amqpConnection.request`.

Is it something that was specifically avoided, or is it just that there was no particular demand for this ?

**Comment by WonderPanda** [comment]
No particular reason, just a lack of demand. This will be addressed as part of [the roadmap for v2](https://github.com/golevelup/nestjs/discussions/227)

**Comment by fabricemathis** [comment]
Good news ! Thanks for your answer ! 😃

**Comment by leanpilar** [comment]
any news on this?
on the 0.1.5 the request function type accepts as third argument requestHeaders?: Dom.RequestInit['headers'] but it not works or I pass it wrong?
like {param: 'param'}
