### ISSUE TITLE
[RabbitMQ] How to handle the "reply-to" message from a published message

### ISSUE THREAD

**Issue by neilime** [golevelup/nestjs#230]
Hi,

I cannot find in the documentation / issues how to retrieve the replyTo message of a published message.

Here is the service that publish the message, it works good.

```ts
@Injectable()
export class MessageQueueService {
  constructor(
    private readonly amqpConnection: AmqpConnection,
  ) {}

  async publishMessage(): Promise<void> {
    this.amqpConnection.publish(
      "",
      "my-test-queue",
      {
       "test": "data"
      },
      {
        replyTo: "my-test-queue.replies",
        correlationId: "random-uuid",
      }
    );
  }
}
```

The message is processed by RabbitMQ. Later an external service is consuming that message then publishes the response in the right reply-to queue:

```json
{
     "exchange": "",
     "routing_key": "my-test-queue.replies",
     "body": "{\"result\": \"ok\"}",
      "correlationId": "random-uuid",
}
```

How am I supposed to retrieve this message (`{"result": "ok"}`) in my `MessageQueueService` ?

I've tried but it does not work: 

```ts
  @RabbitRPC({
    exchange: "",
    routingKey: "my-test-queue.replies",
    queue: "my-test-queue.replies",
  })
  public async handleReply(msg: unknown): Promise<void> {
    console.log(`Received message: ${JSON.stringify(msg)}`);
  }
```
Thank you for your help

**Comment by WonderPanda** [comment]
It looks like you're implementing your own version of RPC using your own `replyTo` this is fine, but on the consuming side you should use `@RabbitSubscribe` instead of `RabbitRPC` to receive the response from your external service.

Alternatively if your external service is using the direct reply to functionality of RabbitMQ you can use

```
await this.amqpConnection.request(....)
```

instead of using `publish` so that your service will wait for a response

**Comment by neilime** [comment]
Thank you for your answer @WonderPanda, it works good with `this.amqpConnection.request` but as I don't know when the message will handle by the external service nor the response will be sent. 

I prefer to use the `@RabbitSubscribe`  I have try that : 

```ts
@Injectable()
export class MessageQueueService {
  constructor(
    private readonly amqpConnection: AmqpConnection,
  ) {}

  async publishMessage(): Promise<void> {
    this.amqpConnection.publish(
      "",
      "my-test-queue",
      {
       "test": "data"
      },
      {
        replyTo: "my-test-queue.replies",
        correlationId: "random-uuid",
      }
    );
  }

  @RabbitSubscribe({
    exchange: "",
    routingKey: "my-test-queue.replies",
    queue: "my-test-queue.replies",
  })
  public async handleReply(msg: unknown): Promise<void> {
    console.log(`Received message: ${JSON.stringify(msg)}`);
  }
}
```

Nest logs `[Nest] 208144   - 02/04/2021, 7:55:31 PM   [AmqpConnection] Successfully connected to a RabbitMQ broker` in loop.
But I don't see any consumer on the queue `my-test-queue.replies` via  the Rabbit Management Web App
And the method is never called while there are message in the queue.

**Comment by neilime** [comment]
Thank you for this answer
