### ISSUE TITLE
Problem with interceptor and amqpConnection.publish

### ISSUE THREAD

**Issue by AmadorSV** [golevelup/nestjs#236]
Hi,

I'm in the need of encrypt and decrypt a part of the message when sending and receiving a message. I made an interceptor to accomplish this, my problem is that when I use amqpConnection.publish(msg) all pipes used in handle is not getting any data. When I use amqpConnection.request it works as intended.

````typescript 
@Injectable()
export class RabbitInterceptor implements NestInterceptor {
    intercept(context: ExecutionContext, next: CallHandler<any>): Observable<any> | Promise<Observable<any>> {

        const request = context.getArgByIndex(0);
        const payload = JSON.stringify(request);
        const properties = Object.getOwnPropertyNames(request);

        request.data = Buffer.from(payload).toString("base64");

        return next.handle()
        .pipe(
            map(payload => payload.data = Buffer.from(payload.data,'base64').toString('ascii'))
        )
    }
}
````

**Comment by WonderPanda** [comment]
Can you please show an example of how you're trying to use Pipes for the `publish` method. There isn't enough information here yet to be able to provide a good solution or recommendation

**Comment by AmadorSV** [comment]
ext.handle()
        .pipe(
            map(payload => payload.data = Buffer.from(payload.data,'base64').toString('ascii'))
        )

here payload is empty

**Comment by WonderPanda** [comment]
I still don't completely understand your scenario. Interceptors don't really make sense in the context of `publishing` a message. Do you want to run custom logic on every message right before you publish it? If so Interceptors will not work you should just create a wrapper service around `AmqpConnection` which you could inject instead that does your custom logic and then calls `publish` on the `AmqpConnection`

**Comment by AmadorSV** [comment]
Yes, i want to do something with the message right before sending and receiving it

**Comment by WonderPanda** [comment]
You have a couple options: 
- write a helper function that you use to transform the message body before you publish it and just remember to call it before you do `publish` with the new message contents
- make your own RabbitMQ service which is a wrapper around `AmqpConnection` (it should inject the connection into its constructor). Then you can expose your own `publish` message which will hide the transformation logic and make sure that it is always applied. Then you can call `publish` inside this service

Creating NestJS services is outside the scope of this repo if you choose to go for the second option and have more questions you might want to review NestJS docs or ask on the Discord

**Comment by Jendorski** [comment]
> AmqpConnection

Hi @WonderPanda can you share a sample of the wrapper service, say by extending `AmqpConnection` in a class, thanks
