### ISSUE TITLE
Rabbit and ha-mode

### ISSUE THREAD

**Issue by pigant** [golevelup/nestjs#239]
Context: I got a cluster in k8s with 3 nodes running rabbit. I set the policy to ha-mode=all over all my queues.

Problem: When 1 node is down, what is normal with my infrastructure, and that node got one queue what i'm listen to in nest. I lost the subscription, but not the connection. The problem with that is there are not errors detected and there is not new subscription ..

What i'm doing for now: I compare the connections register in AmqpConnection.channel.consumers vs the API of rabbit vs one list with all my queues, if one is missing, i kill my app and then k8s restart it.
code
```typescript
const connectionsTags: string[] = Object.keys(this.amqpConnection.channel.consumers);
      this.httpClient
        .get(`${this.config.rabbitApi}/api/consumers`, {
          headers: { 'content-type': 'application/json' },
          auth: {
            username: this.config.rabbitUser,
            password: this.config.rabbitPassword,
          },
        })
        .pipe(
          map((data) => {
            const responseFromRabbit: RabbitmqStatus[] = data.data;
            const out: { [queue: string]: boolean } = queues.reduce((acc, prev) => {
              acc[prev] = false;
              return acc;
            }, {});
            connectionsTags.forEach((connection) => {
              const coincidence = responseFromRabbit.find((d) => d.consumer_tag === connection);
              if (coincidence) {
                out[coincidence.queue.name] = queues.includes(coincidence.queue.name);
              }
            });
            return out;
          }),
        )
        .subscribe({
          next: (data) => {
            Object.keys(data).forEach((key) => {
              if (!data[key]) {
                this.logger.error(`Problema de conexión con colas... estado: ${JSON.stringify(data)}\nSaliendo de la aplicación`);
                process.exit(1);
              }
            });
          },
        });
```

**Comment by underfisk** [comment]
@pigant This seems more a higher-level problem not related to how RMQ module manages your connections, you can in fact have a module that leverages the module lifecycle (more specifically the module shutdown) and make sure you disconnect or force to unmount.
The connections are closed once the module is destroyed (https://github.com/golevelup/nestjs/blob/3b18359c5203ab05dd1c06899e772c8065e055bc/packages/rabbitmq/src/rabbitmq.module.ts#L96) therefore i don't really see how we could help

**Comment by ssilve1989** [comment]
I'm not sure the question was understood here? In a k8s cluster configured with a HA Rabbit Cluster, when one of the nodes goes down, the queues created by `@RabbitSubscribe` are not re-created when the connection is re-established.

I can consistently reproduce the following case: 

- serve a 3-node rabbit cluster in k8s
- connect N replicas of a service with 1 unnamed queue each
- Rabbit Management GUI shows N queues. This is correct
```typescript
    @RabbitSubscribe({
      exchange: DIRECT_EXCHANGE,
      queueOptions: {
        autoDelete: true,
        durable: false,
      },
      routingKey,
})
```
- restart one of the 3 nodes in the rabbit cluster
- Rabbit Management Console shows the # of queues for the replicated services that were connected to that node disappear. Total number of queues in Rabbit GUI is now `N - replicas on that node`

These replicas when reconnected to rabbit, as evidenced by a health check and checking `managedConnection.isConnected()` never re-create a new queue binding for the service. 

Interestingly enough, if you restart _all_ nodes in the rabbit cluster, when the final node has restarted _then_ all queues will be recreated, but until then each replica when reconnecting does not make any new queues.
