### ISSUE TITLE
Dynamically configure RabbitSubscribe decorator?

### ISSUE THREAD

**Issue by monkeydeus** [golevelup/nestjs#240]
Is there a way to configure the arguments passed to the RabbitSubscribe decorator dynamically, without creating a new decorator factory, or some such?  What I would like to achieve is this:

@RabbitSubscribe({
		exchange: configService.get('EXCHANGE_NAME'),
		routingKey: configService.get('ROUTING_KEY_NAME'),
		queue: configService.get('QUEUE_NAME')
	})

**Comment by spasibo-ra** [comment]
We will never know the answer

**Comment by WonderPanda** [comment]
Yes, it is possible assuming that you load the values ahead of time through ENV and make them available to your application before the Decorator file is processed.

It is not possible using something like `configService` as it would require the NestJS DI container to be bootstrapped ahead of time.

If you're interested it is possible to achieve this set up using [@golevelup/profiguration](https://github.com/golevelup/ts-ecosystem/blob/master/libs/profiguration/README.md) or you would have to build your own config loader that can be referenced before any of the other decorator code

**Comment by ahmednawazkhan** [comment]
this is a common use case. I solved it using `AmqpConnection` class

![image](https://user-images.githubusercontent.com/20334388/156347928-52b9dffe-132e-4db4-af3e-96ddbd1f8d41.png)

Hope this helps
