### ISSUE TITLE
How to create a @RabbitSubscribe from array  Routing keys

### ISSUE THREAD

**Issue by spasibo-ra** [golevelup/nestjs#241]
Can't use this.config in @RabbitSubscribe
![image](https://user-images.githubusercontent.com/6201285/110621575-0cd6fb00-81a3-11eb-86b6-dc8bd425d164.png)

**Comment by WonderPanda** [comment]
Decorators do not have access to values from inside of a class. This is a limitation of Typescript and not this library

**Comment by spasibo-ra** [comment]
![image](https://user-images.githubusercontent.com/6201285/110796604-d079cc80-8280-11eb-981e-4b97fd11c9f8.png)

**Comment by WonderPanda** [comment]
Sure if you want to pull them from a global variable that is technically okay. You'll probably want a way to load globals properly and have type safety for them which can be accomplished using @golevelup/profiguration
