### ISSUE TITLE
Upgrading amqplib in rabbitmq

### ISSUE THREAD

**Issue by trotsaleksandrov** [golevelup/nestjs#242]
Hi! 
Is it possible to upgrade `amqplib` in rabbitmq package to version ^0.7.0 or higher? 
That package uses `url-parse` which has this [vulnerability](https://snyk.io/test/npm/url-parse/1.4.7) 
Thanks in advance!

**Comment by WonderPanda** [comment]
@trotsaleksandrov This is now available in `@golevelup/nestjs-rabbitmq@1.16.1`
