### ISSUE TITLE
[DISCOVERY] Is no longer working with the V6

### ISSUE THREAD

**Issue by adrien2p** [golevelup/nestjs#25]
![Screen Shot 2019-03-19 at 18 01 23 (2)](https://user-images.githubusercontent.com/25098370/54626400-5cc9ce00-4a71-11e9-9a8c-b97b41d9034e.png)

It's no longer working with nest version 6 due to the REQUEST

**Comment by WonderPanda** [comment]
Yeah I started taking a look at this last night as well. There have been a significant amount of changes to the underlying DI mechanisms now that Request scoped providers are a thing. My number one priority over the next couple days will be releasing new packages that target Nest 6

**Comment by WonderPanda** [comment]
I'm going to close this in favor of tracking the overall migration to Nest 6 in #26

**Comment by WonderPanda** [comment]
@adrien2p I've published new versions of the packages that now support v6. Discovery will simply ignore request scoped dependencies as they don't actually have an available instance or meta to scan at application start up. Let me know if you get a chance to try this out in your project and run into any issues

**Comment by adrien2p** [comment]
@WonderPanda i have updated my package, everything is working properly 👍 thank's

**Comment by WonderPanda** [comment]
Awesome glad to hear it!
