### ISSUE TITLE
Can not publish with amqpConnection

### ISSUE THREAD

**Issue by noctis-doahub** [golevelup/nestjs#261]
`@Injectable()
export class ProductsService {
  constructor(
    private readonly amqpConnection: AmqpConnection
  ) {
  }
  
  @RabbitSubscribe({
    exchange: 'events',
    routingKey: 'product.created',
    queue: 'products',
    queueOptions: {
      durable: false,
    },
  })
  public async onHandleProductCreated(msg: {}) {
    console.log(`Received message: onHandleProductCreated`, this.amqpConnection);
    await this.amqpConnection.publish('events', 'es.index', { msg: 'hello world' })
  }`

I tried to published to another queue when Receiving Messages but it's not working.

This is response message

`Received message: onHandleProductCreated AmqpConnection {
  messageSubject: Subject {
    _isScalar: false,
    observers: [],
    closed: false,
    isStopped: false,
    hasError: false,
    thrownError: null
  },
  initialized: Subject {
    _isScalar: false,
    observers: [],
    closed: false,
    isStopped: false,
    hasError: false,
    thrownError: null
  },
  config: {
    prefetchCount: 10,
    defaultExchangeType: 'topic',
    defaultRpcErrorBehavior: 'REQUEUE',
    defaultSubscribeErrorBehavior: 'REQUEUE',
    exchanges: [],
    defaultRpcTimeout: 10000,
    connectionInitOptions: { wait: true, timeout: 5000, reject: true },
    connectionManagerOptions: {},
    registerHandlers: true,
    enableDirectReplyTo: true
  },
  logger: Logger { context: 'AmqpConnection', isTimestampEnabled: false }
}
[Nest] 50248   - 05/12/2021, 5:36:53 PM   [ExceptionsHandler] Cannot read property 'isConnected' of undefined +63810ms
`

Any helps?

**Comment by noctis-doahub** [comment]
It worked now. Thanks

**Comment by Xdy1579883916** [comment]
How to solve it

**Comment by Xdy1579883916** [comment]
> It was OK in version 2.2.0, but not in version 2.3.0

```typescript

constructor(
    private readonly amqpConnection: AmqpConnection,
  ) {}


 // ------- use

await this.amqpConnection.publish("exchanges", "queueA", msg)


// ------ but running error ---
this.amqpConnection is undefined
```
