### ISSUE TITLE
nestjs-testing package is outdated

### ISSUE THREAD

**Issue by adrianwix** [golevelup/nestjs#265]
https://www.npmjs.com/package/@golevelup/nestjs-testing Doesn't include support for promises

**Comment by WonderPanda** [comment]
@adrianwix Can you give some more context into the issue you're seeing?

Using the latest version of the library from NPM this works just fine:

```typescript
import { createMock } from "@golevelup/nestjs-testing";

interface WithPromises {
    getData(): Promise<string>
}


const mock = createMock<WithPromises>({
    getData: async () => {
        return 'test';
    }
});

describe('test', () => {
    it('should work with promises', async () => {
        const result = await mock.getData();
        expect(result).toBe('test');
    });
});
```

**Comment by adrianwix** [comment]
It should automatically mock promises like https://github.com/golevelup/nestjs/pull/161
```ts
import { createMock } from '@golevelup/nestjs-testing'

interface WithPromises {
    getData(): Promise<string>
}

class Service implements WithPromises {
    async getData(): Promise<string> {
        return 'test'
    }
}

const mock = createMock<Service>()

describe('test', () => {
    it('should work with promises', async () => {
        await mock.getData()
        expect(mock).toHaveBeenCalled()
    })
})

```
### Output

```
 jest app.spec.ts --no-cache
 FAIL  src/app.spec.ts (31.995 s)
  test
    ✕ should work with promises (5006 ms)

  ● test › should work with promises

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      14 |
      15 | describe('test', () => {
    > 16 |     it('should work with promises', async () => {
         |     ^
      17 |         await mock.getData()
      18 |         expect(mock).toHaveBeenCalled()
      19 |     })

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (app.spec.ts:16:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        32.037 s
Ran all test suites matching /app.spec.ts/i.
```

I copied your package code directly from the repository and it mocks promises as expected. I am using it right now for testing in the meantime.

Anyways thanks for making this package. It saved a lot of time for me while writing tests

**Comment by adrianwix** [comment]
Using "@golevelup/nestjs-testing": "^0.1.2"

**Comment by WonderPanda** [comment]
Hey @adrianwix I deeply apologize for not realizing what was going on here earlier. Quite a while ago now I changed the package name and started releasing this under `@golevelup/ts-jest` instead of `@golevelup/nestjs-testing` since the mock utility is generic to TS and jest and doesn't really have anything to do with Nest. I somehow didn't catch that you were referring to the older package in our correspondence.

@golevelup/ts-jest is on version 0.3.1 and should include the behavior you're looking for. I'll look into a way to properly mark the old package as deprecated to avoid confusion

**Comment by mlyskawinski** [comment]
@WonderPanda The old package is still not deprecated

I would be great to add an official NPM notice, as i've worked in many projects and many teams, that do not know about the name change and still use the old package

**Comment by WonderPanda** [comment]
> @WonderPanda The old package is still not deprecated
> 
> I would be great to add an official NPM notice, as i've worked in many projects and many teams, that do not know about the name change and still use the old package

I just marked it as deprecated in NPM. Says it might take a few minutes to process but hopefully you'll starting seeing warnings during installation if you still depend on the old version.
