### ISSUE TITLE
More Docs Detail and Example

### ISSUE THREAD

**Issue by dorman99** [golevelup/nestjs#271]
hello iam hafizh

currently ive case to build an application that can produce dedicated data generate by master collection, as example

collections
- users
- vouchers
- user-vouchers

each time voucher being generated the data will be map into user-vouchers collection. in the past few days, this package seems will help me to solve my problem, but my question is, i got lost while using di read.me docs and the i cant find quite example using this package, any one can help ?

**Comment by WonderPanda** [comment]
@dorman99 This repository is home to 8 different packages. It is not clear from your message which package you are referring to

**Comment by WonderPanda** [comment]
Feel free to reopen if you can provide some more context here for what you're looking for

**Comment by dorman99** [comment]
hey, iam sorry for my mistake for undetailed message before. 

currently iam trying to use the rabbitMq services. its working properly now... iam little bit confuse before because its only support for exchange cases am i right ? if we use the original package from nest, there is send message to send single queue, so iam assuming this package approach is pub/sub pattern, even though we still can use the basic queue pattern.. anyway its greate package..

i have another question, is that possible if we send something to exchange and publish it. but there is no listener, and after that we just create the listener, will the listener can consume the message that created before it available(the listener), or if theres no listener the message will be vanish ?

case-flow
1. publish message to exchange with options {durable: true}
2.  no listener / consumer
3. create & init listener / consumer
4. restart service
5. consume number 1 message

**Comment by dorman99** [comment]
@WonderPanda

**Comment by dorman99** [comment]
btw i cant reopen this issue.

and i found this one https://github.com/golevelup/nestjs/issues/69

how can i set this assertQueue query params ?

**Comment by dorman99** [comment]
`await this.amqpConnection.publish(constant.exchanges.challenge.remove.name, routing, {id: id}, {persistent: true});`

i have add persistent to options configuratin while publishing the message.

> @RabbitSubscribe({
        exchange: constant.exchanges.challenge.remove.name,
        routingKey: constant.exchanges.challenge.remove.routingKeys,
        queueOptions: {
            durable: false
        }
    })
    public async pubSubRemoveChallenge(msg: {id: Types.ObjectId}) {
        console.log("here you go !!")
    }


    this code above is the consumer, i want to make the message not vanish before i initiate this consumer. can i do that? 
    and will be consume when i implement those consumer only.
