### ISSUE TITLE
How to make webhook public?

### ISSUE THREAD

**Issue by alessandrosangalli** [golevelup/nestjs#272]
By default all my routes needs authentication, how i can make my webhook route (i'am using stripe) public?

**Comment by WonderPanda** [comment]
@alessandrosangalli How are you currently authentication globally? You will need to add an exception for the stripe route

**Comment by WonderPanda** [comment]
Closing this for now as it's not really an issue with this library but in how you're configuring your NestJS app. If you can provide more detail about your setup to help narrow it down feel free to reopen this and I can take a look
