### ISSUE TITLE
Support using RabbitMQ with NestJS microservices

### ISSUE THREAD

**Issue by WonderPanda** [golevelup/nestjs#274]

**Comment by LucSalommez** [comment]
Hello, is there any hope that this feature is developed in near future or should I abandon RabbitMQ for my Microservices architecture ?

**Comment by LucSalommez** [comment]
Hello, do you have any update on this issue ?
Do you know any alternative in order to have Pub/Sub in a NestJS Microservices architecture ?
Thanks

**Comment by notmedia** [comment]
@underfisk Hi! Do you have any updates on this?
