### ISSUE TITLE
Malformed message causes handler not called + high cpu

### ISSUE THREAD

**Issue by ApizrTech** [golevelup/nestjs#279]
Hi,
Thanks for your very good work.
Just to tell that if a malformed* json message is published to a topic, via the rabbitmq web console, then a nestjs consumer has the following problem :
-the cpu goes high
-the delivery rate displayed by the console is around 1000/s
-the handler function is not triggered

*in my case, a double quote was missing at the end of a field's string value

my versions : rabbitmq:3-management docker image for the broker, "@golevelup/nestjs-rabbitmq": "^1.16.1" for the client, node v12.19.0
thanks,
Anselme

**Comment by WonderPanda** [comment]
This depends on your error handling configuration. By default, a message that is failed to be processed will be requeued. If you do nothing about it, there will be a loop of requeues. You can use the nack behavior instead if you like but in general with this library It is up to you to provide the correct error handling behavior for your application

**Comment by ApizrTech** [comment]
Thanks for your detailed answer. 
However my handler function is not called in the case I submit, so I can't figure out where to define the error handling.
Is there another place to define error handling, in annotations or module ?
Thanks
Anselme

**Comment by rafaelcorreiapoli** [comment]
I'm also having the same issue.
@ApizrTech did you manage to solve it ?
