### ISSUE TITLE
Instantiate a new class

### ISSUE THREAD

**Issue by Zyles** [golevelup/nestjs#282]
Is there a way to create a new class instance from the discovery data?

I have my service which registers all the available classes and the data returned is:
```
{
    meta: { name: 'Boolean', code: 'boolean', context: 'base' },
    discoveredClass: {
      name: 'BooleanAttributeType',
      instance: BooleanAttributeType {},
      injectType: [class BooleanAttributeType],
      dependencyType: [class BooleanAttributeType],
      parentModule: [Object]
    }
  }
```

How can I dynamically in code create an instance of BooleanAttributeType without knowing its name, for example in a loop?

I tried with something like: 
```
const attributeTypeClass = (await attributeTypesWithClassData).find((attribute: any) => attribute.meta.code === attributes.code)
const attributeTypeInstance: any = new (<any>[attributeTypeClass.discoveredClass.instance])
```

But get:
`TypeError: [attributeTypeClass.discoveredClass.instance] is not a constructor`

Is it possible?

Thanks.

**Comment by WonderPanda** [comment]
`injectType` and `dependencyType` in your example both point to the constructor function of `BooleanAttributeType`

**Comment by Zyles** [comment]
> `injectType` and `dependencyType` in your example both point to the constructor function of `BooleanAttributeType`

`TypeError: [attributeTypeClass.discoveredClass.injectType] is not a constructor`

**Comment by WonderPanda** [comment]
@Zyles You need to access the `prototype.constructor` if you want to try and dynamically instantiate a class. It'll be up to you to figure out how to pass the right args to it if the constructor expects any. Here's an example:

```typescript
import { Module, OnModuleInit } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { DiscoveryModule, DiscoveryService } from '@golevelup/nestjs-discovery';

@Module({
  imports: [DiscoveryModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule implements OnModuleInit {
  public constructor(private readonly discover: DiscoveryService) {}

  async onModuleInit() {
    const providers = await this.discover.providers(
      (x) => x.name === 'AppService',
    );

    const [provider] = providers;

    const ctor = provider.dependencyType.prototype.constructor;

    const instance = new ctor();
    console.log(instance);
  }
}
```
