### ISSUE TITLE
RabbitMQ: DefaultRpcErrorBehaviour is ignored

### ISSUE THREAD

**Issue by ssarj** [golevelup/nestjs#289]
This can be seen in [setupRpcChannel](https://github.com/golevelup/nestjs/blob/d72c8fa4950d057d5d1eab896699dddd2b00e724/packages/rabbitmq/src/amqp/connection.ts#L323), where it accidentally references [defaultSubscribeErrorBehaviour](https://github.com/golevelup/nestjs/blob/d72c8fa4950d057d5d1eab896699dddd2b00e724/packages/rabbitmq/src/amqp/connection.ts#L374).

I will submit a PR today :)

**Comment by WonderPanda** [comment]
@ssarj Thanks! I appreciate you taking the time to diagnose and come up a with a solution for this :rocket:

**Comment by underfisk** [comment]
This issues seems to have been fixed, also there was a change on the error behaviour
