### ISSUE TITLE
Separate AmqpConnection from Repo

### ISSUE THREAD

**Issue by WonderPanda** [golevelup/nestjs#29]
AmqpConnection is a general purpose Typescript client for interacting with AMQP. It should live in it's own repository and be published to NPM outside of the @nestjs-plus organization so that it can be easily consumed by other projects

**Comment by underfisk** [comment]
@WonderPanda Nestjs exposes a load package util which allow us to lazy load this module and also ask the consumer to provide us with the module instead, if that's the expected behaviour i can make the change

**Comment by WonderPanda** [comment]
The intent was to make a dedicated package for the AmqpConnection logic that could be used completely separately from NestJS ecosystem eg `@golevelup/rabbitmq`.

I don't think it's a very important issue right now though. We should probably switch over to NX before we start splitting apart more packages. I'm going to close this for now and we can revisit it again in the future.
