### ISSUE TITLE
[ RabbitMQ ] how to publish a message to particular queue

### ISSUE THREAD

**Issue by rakeshlanjewar** [golevelup/nestjs#290]
Hey Guys,
I am trying to publish a message to a particular queue, but not sure how to do it.

```ts
@RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'rpc-route',
    queue: 'dynamicLinks',
  })
  public async rpcHandler(msg: {}) {
    console.log("🚀 ~ file:  msg)
    return {
      response: 42,
    };
  }
```

```this.amqpConnection.publish('', '', {msg : "Hi"})```

**Comment by WonderPanda** [comment]
@rakeshlanjewar Generally speaking you shouldn't be trying to send messages directly to queues. You should be sending them to the exchange with a routing key and they will be automatically handled at the correct queue.

**Comment by rakeshlanjewar** [comment]
Can you please give me an example !

**Comment by WonderPanda** [comment]
Did you read through the docs? https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#sending-messages 

What is the issue that you're having?

**Comment by rakeshlanjewar** [comment]
Thanks for the help!

Sorry, I am fairly new to rabbitMQ.

coming from ampqlib 😞

```
@RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'rpc-route1',
  })
  public async processDynamicLinks(msg: {}) {
    return {
      response: 42,
    };
  }

```



```
    this.amqpConnection.publish('exchange1', 'rpc-route1', {msg : "Hi"})
    this.amqpConnection.publish('exchange2', 'rpc-route2', {msg : "Hi"})

```

**Comment by WonderPanda** [comment]
If you're trying to use RPC to get a response back you should use the request method: https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#requesting-data-from-an-rpc
