### ISSUE TITLE
dynamic modules and tests

### ISSUE THREAD

**Issue by TrejGun** [golevelup/nestjs#291]
Heya! Thanks a lot for your libs, they are truly amazing
I was using dynamic modules for some time and then decided to cover one of my modules with tests using jest like in nest docs

here is my module
```ts
@Module({
  imports: [HttpModule],
  providers: [Logger, MailchimpService],
  exports: [MailchimpModule, MailchimpService],
})
export class MailchimpModule extends createConfigurableDynamicRootModule<MailchimpModule, IMailchimpOptions>(
  ProviderType.MAILCHIMP_OPTIONS,
) {
  static Deferred = MailchimpModule.externallyConfigured(MailchimpModule, 1000);
}
```

and here is how I initiate in the test file
```ts
    const moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({
          envFilePath: `.env`,
        }),
        MailchimpModule.forRootAsync(MailchimpModule, {
          imports: [ConfigModule],
          inject: [ConfigService],
          useFactory: (configService: ConfigService) => {
            const apiKey = configService.get<string>("MAILCHIMP_API_KEY", "");
            const userName = configService.get<string>("MAILCHIMP_API_USER_NAME", "");
            const dc = configService.get<string>("MAILCHIMP_DC", "");
            const from = configService.get<string>("MAILCHIMP_FROM", "");
            return { apiKey, userName, dc, from };
          },
        }),
        ... other modules
      ],
      providers: [Logger],
    }).compile();
```

this works but each time after tests has already passed I see a warning from jest

```
Ran all test suites with tests matching "UserService".
(node:98629) UnhandledPromiseRejectionWarning: Error: Expected MailchimpModule to be configured by at last one Module but it was not configured within 2000ms
(Use `node --trace-warnings ...` to show where the warning was created)
(node:98629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:98629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I believe this is because of static property called Deferred. 
Do you have anything in mind how can I remove this warning message??

PS I can increase timeout from 1000 to 60000 and tests will wait for this timeout to finish

**Comment by WonderPanda** [comment]
Hey @TrejGun thanks for the kind words. Another user recently suggested that the pattern for setting up a static `Deferred` property isn't ideal as it triggers the await behind the scenes https://github.com/golevelup/nestjs/pull/252

Can you give this a shot and define it as `static Deferred = () => MailchimpModule.externallyConfigured(MailchimpModule, 0);`

**Comment by TrejGun** [comment]
@WonderPanda , @steinroe  thanks! the new pattern works like a charm

btw I have the same case , my module is actual npm which I use in several apps

**Comment by TrejGun** [comment]
I thought it was fixed but apparently, it was not.

Here is an example code to demonstrate the issue, it could be a little bit simpler, so sorry. 
You should have nmv to switch between node 14 and 16 and download one file

first switch to node 14
```
nvm use 14
```

then clone example project
```sh
git clone https://github.com/GemunIon/nestjs-sqs.git
npm i
```

then download elasticmq-server-1.2.0.jar from https://github.com/softwaremill/elasticmq and start it from the root of the project using another terminal
```sh
java -Dconfig.file=.github/build/elasticmq.conf -jar elasticmq-server-1.2.0.jar
```

then in first terminal execute tests
```sh
npm t
```

this will end up in a clean run. now switch to node 16
```sh
nvm use 16
```

and run tests again
```sh
npm t
```

this time you will see

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  RANDOMBYTESREQUEST

      42 | 
      43 |     it("should register module", async () => {
    > 44 |       module = await Test.createTestingModule({
         |                           ^
      45 |         imports: [
      46 |           SqsModule.forRoot(SqsModule, {
      47 |             consumers: [TestQueues[TestQueue.Test]],

      at rng (node_modules/@nestjs/core/node_modules/uuid/dist/rng.js:18:21)
      at Object.v4 (node_modules/@nestjs/core/node_modules/uuid/dist/v4.js:17:63)
      at new ModulesContainer (node_modules/@nestjs/core/injector/modules-container.js:8:38)
      at new NestContainer (node_modules/@nestjs/core/injector/container.js:21:24)
      at new TestingModuleBuilder (node_modules/@nestjs/testing/testing-module.builder.js:14:26)
      at Function.createTestingModule (node_modules/@nestjs/testing/test.js:8:16)
      at Object.<anonymous> (src/sqs.module.spec.ts:44:27)

```

Yes it points out to uuid module but I believe this is an actual reason

**Comment by TrejGun** [comment]
lol, this looks like a problem with uuid
nevermind

**Comment by TrejGun** [comment]
so while I tried to create a bug to uuid it turned out it is ok
```ts
import { v4 } from "uuid";

describe("uuid", () => {
  it("RANDOMBYTESREQUEST", done => {
    v4();
    done();
  });
});
```

this simple test on empty repo as well as on nestjs-sqs repo works perfectly fine

so the problem is somewhere in this module or nest itself. can you please help me to nail it down?

**Comment by TrejGun** [comment]
some more references
https://github.com/TrejGun/uuid-bug
https://stackoverflow.com/questions/65653226/jest-and-randombytesrequest-open-handles

**Comment by TrejGun** [comment]
just checked on another module to make sure it is not nestjs itself.
the problem is definitely in this module

i would love to help to fix it

**Comment by WonderPanda** [comment]
The stack trace here is pointing entirely at code coming from `@nestjs/core`. The code base for dynamic modules is very small (1 file, less than 200 lines of code) and it doesn't reference or use the `uuid` package anywhere. I need more evidence that this is actually an issue with this library before I can spend time debugging. Have you tried the ideas from the linked StackOverflow thread in your previous comment?

**Comment by TrejGun** [comment]
to move the mouse? yes i did :D does not help

**Comment by TrejGun** [comment]
this is not related to your code mate, cheers
