### ISSUE TITLE
about consumer

### ISSUE THREAD

**Issue by guohui666** [golevelup/nestjs#292]
Sorry, I'm not good at English

when i use  `deadLetterExchange` to  expire unpaid orders ， I don't want to create consumer, because it will always access my program, so I added a new parameter `needConsumer` to control whether to create consumer

Is there a better way to do that?

thx

```javascript
@RabbitSubscribe({
    exchange: 'TTL',
    routingKey: 'TTL',
    queue: 'TTL',
    needConsumer: false,  // new
    queueOptions: {
      exclusive: false,
      deadLetterExchange: 'deadLetter',
      deadLetterRoutingKey: 'deadLetter'
    }
  })
  public async rpcHandler(msg: any, amqpMsg: ConsumeMessage) {}
```

```javascript
export interface MessageHandlerOptions {
  exchange: string;
  routingKey: string | string[];
  queue?: string;
  needConsumer?: boolean,  // new
  queueOptions?: QueueOptions;
  /**
   * @deprecated()
   * Legacy error handling behaviors. This will be overridden if the errorHandler property is set
   */
  errorBehavior?: MessageHandlerErrorBehavior;
  /**
   * A function that will be called if an error is thrown during processing of an incoming message
   */
  errorHandler?: MessageErrorHandler;
  allowNonJsonMessages?: boolean;
}

```

```javascript
const { exchange, routingKey, allowNonJsonMessages, needConsumer = true } = rpcOptions;

    const { queue } = await channel.assertQueue(
      rpcOptions.queue || '',
      rpcOptions.queueOptions || undefined
    );

    const routingKeys = Array.isArray(routingKey) ? routingKey : [routingKey];

    await Promise.all(
      routingKeys.map((x) => channel.bindQueue(queue, exchange, x))
    );
    if (!needConsumer){ // here
      return
    }
//.....
```

**Comment by WonderPanda** [comment]
I think that I am confused about what you are trying to accomplish. In your example, what should happen with the method:
```typescript
public async rpcHandler(msg: any, amqpMsg: ConsumeMessage) {}
```

Does this method receive messages?

**Comment by guohui666** [comment]
> I think that I am confused about what you are trying to accomplish. In your example, what should happen with the method:
> 
> ```ts
> public async rpcHandler(msg: any, amqpMsg: ConsumeMessage) {}
> ```
> 
> Does this method receive messages?


I may not have described it clearly, This is my current code,

I use `createRpc` to create  a new `exchange`

```javascript
await this.amqpConnection.createRpc(() => Promise.resolve(), {
      exchange: 'TTL',
      routingKey: 'TTL',
      queue: 'TTL',
      needConsume: false, 
      queueOptions: {
        exclusive: false,
        deadLetterExchange: 'deadLetter',
        deadLetterRoutingKey: 'deadLetter'
      }
    })
```

now the handler is `() => Promise.resolve()`   because this is a special queue , I don't need a consumer , I want all messages to go to the `deadLetterExchange` when they expire， so I added a new parameter `needConsumer `to control whether to create consumer and change the source code


```javascript
public async setupRpcChannel<T, U>(
    handler: (
      msg: T | undefined,
      rawMessage?: amqplib.ConsumeMessage
    ) => Promise<RpcResponse<U>>,
    rpcOptions: MessageHandlerOptions,
    channel: amqplib.ConfirmChannel
  ) {
    const { exchange, routingKey, allowNonJsonMessages, needConsumer = true } = rpcOptions;

    const { queue } = await channel.assertQueue(
      rpcOptions.queue || '',
      rpcOptions.queueOptions || undefined
    );

    const routingKeys = Array.isArray(routingKey) ? routingKey : [routingKey];

    await Promise.all(
      routingKeys.map((x) => channel.bindQueue(queue, exchange, x))
    );

 // here---------------------------------
    if (!needConsumer){ 
      return
    }


    await channel.consume(queue, async (msg) => {
      try {
        if (msg == null) {
          throw new Error('Received null message');
        }

        const response = await this.handleMessage(
          handler,
          msg,
          allowNonJsonMessages
        );

        if (response instanceof Nack) {
          channel.nack(msg, false, response.requeue);
          return;
        }

        const { replyTo, correlationId } = msg.properties;
        if (replyTo) {
          await this.publish('', replyTo, response, { correlationId });
        }
        channel.ack(msg);
      } catch (e) {
        if (msg == null) {
          return;
        } else {
          const errorHandler =
            rpcOptions.errorHandler ||
            getHandlerForLegacyBehavior(
              rpcOptions.errorBehavior ||
                this.config.defaultSubscribeErrorBehavior
            );

          await errorHandler(channel, msg, e);
        }
      }
    });
  }

```
If not do this, it will always execute the consumer，the console will always print unrelated logs

**Comment by WonderPanda** [comment]
I don't think you should be using `createRpc` for this at all. Can you just create the necessary queue using the AmqpConnection directly?

Alternatively if you basically just need this code:
```typescript
const { exchange, routingKey, allowNonJsonMessages, needConsumer = true } = rpcOptions;

    const { queue } = await channel.assertQueue(
      rpcOptions.queue || '',
      rpcOptions.queueOptions || undefined
    );

    const routingKeys = Array.isArray(routingKey) ? routingKey : [routingKey];

    await Promise.all(
      routingKeys.map((x) => channel.bindQueue(queue, exchange, x))
    );
```
You could just move this to a new public method called for example `bindRoutingKeys` and then it can be reused inside of `createRpc` as well as in your own code

**Comment by guohui666** [comment]
> I don't think you should be using `createRpc` for this at all. Can you just create the necessary queue using the AmqpConnection directly?
> 
> Alternatively if you basically just need this code:
> 
> ```ts
> const { exchange, routingKey, allowNonJsonMessages, needConsumer = true } = rpcOptions;
> 
>     const { queue } = await channel.assertQueue(
>       rpcOptions.queue || '',
>       rpcOptions.queueOptions || undefined
>     );
> 
>     const routingKeys = Array.isArray(routingKey) ? routingKey : [routingKey];
> 
>     await Promise.all(
>       routingKeys.map((x) => channel.bindQueue(queue, exchange, x))
>     );
> ```
> 
> You could just move this to a new public method called for example `bindRoutingKeys` and then it can be reused inside of `createRpc` as well as in your own code

You're right, I can pull this logic out and use it, I'll try it this way, thx

**Comment by WonderPanda** [comment]
@guohui666 I think that this could be useful to expose from the AmqpConnection so if you try it out and it works for your purposes I'd gladly accept a pull request

**Comment by WonderPanda** [comment]
Closed as it appears that the main issue is resolved
