### ISSUE TITLE
allowNonJsonMessages = true call 

### ISSUE THREAD

**Issue by diegodarossi** [golevelup/nestjs#293]
in AppModule is set the "APP_GUARD"
`{
      provide: APP_GUARD,
      useClass: AuthorizeGuard,
 }`

@RabbitSubscribe({ exchange: 'example', routingKey: '', queue: 'example', **allowNonJsonMessages: true**, })
when allowjson this to true and the message does not come in JSON is calling the "AuthorizeGuard" why?

**Comment by WonderPanda** [comment]
Are you sure that this is happening based on the `allowNonJsonMessages` property? In general Guards and Interceptors will be applied to your handlers

**Comment by diegodarossi** [comment]
I managed to solve here

what happened was that if I sent an invalid JSON directly through the Rabbit panel when I arrived in my "AuthorizeGuard" the variable "req" was undefined and gave a problem in the code below, I put it to check if the context was from RabbitMQ and solved.

[Link Image](https://i.ibb.co/zZ12WLx/rabbit.png)
