### ISSUE TITLE
@golevelup/nestjs-rabbitmq: unresolve scope request

### ISSUE THREAD

**Issue by aitormunoz** [golevelup/nestjs#302]
Hi, 
I was working with the library and I ran into a problem trying to inject a token with REQUEST scope. It does not give any error when executing it, but the constructor parameters are not initialized, when the message arrives they are undefined.

Example : 
```
export const TestProvider = {
  provide: 'TestProvider',
  useFactory: async (): Promise<any> => {
    return {
      hello: 'bye'
    };
  },
  scope: Scope.REQUEST,
  inject: []
};
```

```
@Injectable()
export class SendSmsSubscriber {
  constructor(
    @Inject('TestProvider') private testProvider: any,
  ) {
  }

  @RabbitSubscribe({
    exchange: 'sms-core.exchanger',
    routingKey: 'send.sms',
    queue: 'queue.sms-core/send.sms'
  })
  public async pubSubHandler(msg: ISMS): Promise<void> {
  }
}
```
Without the scope it works fine.

Thank you for your work,

**Comment by Scrib3r** [comment]
@aitormunoz Hello. I have same problem and have created the issue few months ago. https://github.com/golevelup/nestjs/issues/243

**Comment by WonderPanda** [comment]
Closing this as a duplicate of #243

Request scoped dependencies are inherently incompatible with RabbitMQ handlers because request scope specifically deals with HTTP requests. The current solution is to not use request scoped providers
