### ISSUE TITLE
Conditionally import `HasuraModule` based on value from `ConfigService`

### ISSUE THREAD

**Issue by arslancharyev31** [golevelup/nestjs#303]
Hello.

The documentation regarding [Automatic Hasura Metadata Synchronization] states that:
> It is recommended that you conditionally add this configuration based on the Node Environment as this should only be used in development environments

It is quite trivial to do so with `process.env.NODE_ENV`, since it is available outside of the Dependency Injection framework, but what if we wanted to set the condition based on the value from Nest's `ConfigService`, which is available from within the DI? I know that if we use `HasuraModule.forRootAsync`, we would be able to configure the module using the injected config service, but I can't seem to find a similar factory method  that would allow me to exclude the `HasuraModule` from the `imports` array of the `@Module` annotation.

[Automatic Hasura Metadata Synchronization]: https://github.com/golevelup/nestjs/tree/master/packages/hasura#automatically-synchronize-hasura-metadata

**Comment by WonderPanda** [comment]
Are you trying to conditionally enable/disable the entire HasuraModule? Or just the configuration which causes it to try and automatically synchronize your Hasura metadata?

The HasuraModule needs to be included in imports if you want to be able to process events inside your application

**Comment by arslancharyev31** [comment]
> Are you trying to conditionally enable/disable the entire HasuraModule?

I am actually unsure about it, now that you asked it. Is there any use to it other than to automatically synchronize Hasura metadata? If that's all it does, then yes, I want to disable the entire module since it would not be needed for the production. I wanted to do it using the `ConfigService`, but could not find a way.

**Comment by WonderPanda** [comment]
The HasuraModule provides the necessary components to actually receive event payloads from Hasura and then route them to the correct service so that they can be handled by your custom business logic. If you do not include the HasuraModule in your imports then you will not be able to process events.

The section you linked in your original comment from the docs is referring specifically to the `managedMetaDataConfig` portion of the module configuration. You should only include this property in development mode so that the module can help keep your local metadata files up to date.

**Comment by arslancharyev31** [comment]
> The section you linked in your original comment from the docs is referring specifically to the `managedMetaDataConfig` portion of the module configuration. You should only include this property in development mode so that the module can help keep your local metadata files up to date.

OK, now it makes perfect sense. The `ConfigService` is available at the `managedMetaDataConfig` section as a DI as well, which answers my initial question. I am very grateful for your help.

**Comment by WonderPanda** [comment]
No problem, glad I was able to help out :)
