### ISSUE TITLE
customize the properties

### ISSUE THREAD

**Issue by pedramaghasian** [golevelup/nestjs#309]
Hello, 
please add the ability to customize the properties or add new one.

> Invalid properties will be ignored. Valid properties are:
>> - content_type
>> - content_encoding
>> - priority
>> - correlation_id
>> - reply_to
>> - expiration
>> - message_id
>> - timestamp
>> - type
>> - user_id
>> - app_id
>> - cluster_id

thank you .

**Comment by WonderPanda** [comment]
@pedramaghasian Can you please elaborate on what you're looking for here? I assume this has to do with RabbitMQ?

**Comment by WonderPanda** [comment]
Closing for lack of information. Feel free to open again if there's more context for what you're trying to accomplish and what the desired API might look like
