### ISSUE TITLE
Keep unack messages in queue and disable requeue

### ISSUE THREAD

**Issue by mohsensaremi** [golevelup/nestjs#310]
I have a message listener like this:
```ts
  @RabbitSubscribe({
    exchange: 'exchange1',
    routingKey: 'subscribe-route',
    queue: 'app2Queue',
  })
  public async pubSubHandler(msg: any) {
    console.log('1');
    const data = transformAndValidateSync(MessageDto, msg);
    console.log(`App2Service Received message`, data);
  }
```
If the validation fails. It will requeue the message again and again and fails millions of times.
If I change the `errorBehavior` to `MessageHandlerErrorBehavior.ACK` or `MessageHandlerErrorBehavior.NACK`, the message will be deleted and gone forever.

I need a way to keep the unacked messages in the queue.

How can I keep them in queue but do not requeue them?

**Comment by WonderPanda** [comment]
Your best bet would be to set up a [dead letter exchange/queue](https://www.rabbitmq.com/dlx.html) which nacked messages will be automatically sent to. Then you can decide what you want to do with these messages as part of your application logic
