### ISSUE TITLE
Using rabbitmq_delayed_message_exchange for delay message not work as expected

### ISSUE THREAD

**Issue by mohsensaremi** [golevelup/nestjs#311]
I registered `RabbitMQModule` like this:
```ts
RabbitMQModule.forRoot({
      exchanges: [
        {
          name: publisher.flight.reservation,
          type: 'topic',
          options: {
            arguments: { 'x-delayed-type': 'direct' },
          },
        },
      ],
    })
```

and publish messages like this:
```ts
this.amqpConnection.publish(
              publisher.flight.reservation,
              message.flight.reservation.checkExpiration,
              {
                id: reservation.id,
              },
              {
                headers: {
                   'x-delay': 10000,
                },
              },
            ),
```

But this message will execute right after publishing and will not wait for 10 seconds before executing.
Am I doing something wrong?

**Comment by eduscrakozabrus** [comment]
To fix it: change in your module
 type: 'topic'  ->  type: 'x-delayed-message'

And install before plugin, if not dot it

RabbitMQModule.forRoot(RabbitMQModule, {
            exchanges: [
                {
                    name: 'my-cool-delayed-exchange-name',
                    type: 'x-delayed-message',
                    options: {
                        arguments: { 'x-delayed-type': 'direct' },
                    },
                },
            ],
            uri: process.env.RABBITMQ_URLS,
            connectionInitOptions: { wait: false },

        }),

**Comment by mohsensaremi** [comment]
@eduscrakozabrus Thank you.
I am closing this issue.

**Comment by WonderPanda** [comment]
@eduscrakozabrus Thanks for chiming in here :pray:
