### ISSUE TITLE
Rabbit queues

### ISSUE THREAD

**Issue by Deigmin** [golevelup/nestjs#312]
Hello. My problem is I just want to point to queue I want to subscribe without writing exchange and routing key because I don't need them.  Is it possible doing this anyhow? 
I want something:
```javascript
@RabbitSubscribe({
        queue: queue
    })
```

instead of :

```javascript
    @RabbitSubscribe({
        exchange: exchange,
        routingKey: routingKey,
        queue: queue
    })
```

**Comment by WonderPanda** [comment]
If you just want direct queue connection you might just want to use the built in NestJS RabbitMQ support.

Usually exchanges help to ensure your application is built well which is why this library was created, but they are not a requirement
