### ISSUE TITLE
[Question] Multiple handlers for a queue separated by routing key

### ISSUE THREAD

**Issue by vinaybedre** [golevelup/nestjs#315]
Hey,

Is it possible to do something like following with golevelup/rabbitmq within the same module?
```typescript
@RabbitSubscribe({exchange:"any", queue:"user", routingKey:"key1"})
handleKey1() {
...
}

@RabbitSubscribe({exchange:"any", queue:"user", routingKey:"key2"})
handleKey2() {
...
}
```

**Comment by vinaybedre** [comment]
If this is not possible, does it mean that by using golevelup/rabbitmq, we can only tie one method to an entire queue? 
What is the reasoning behind this? Should I need to use different queues for various purpose of communication between 2 parties?

**Comment by WonderPanda** [comment]
Queues in RabbitMQ are lightweight and they are intended to be purpose driven. There is no benefit to to reusing the same queue for multiple handlers. A typical application that's properly leveraging RabbitMQ would have dozens if not hundreds or more queues.

A single RabbitMQ node could potentially handle tens of thousands of queues, see for example https://stackoverflow.com/a/22990200/1364771

If you *really* feel the need to do this (I'd be curious about your reasoning) you could have a single handler that receives all your messages through one queue. The handler could then do conditional processing based on the contents of the message itself.

There are no plans to try and implement the suggested functionality you've shown in your original comment as its generally an anti-pattern

**Comment by vinaybedre** [comment]
@WonderPanda Thanks for the insights.
I have couple of microservices (8+), which communicate between them either via RPC / Event publishing.
I thought of having 1 queue for 1 service. 
I am afraid that having 1 queue per purpose may explode the number of queues I may have say in next 3 to 5 years. (just an estimation).

On the other hand, I do not want to have a single handler per service and use switch/if statements, where I will loose the context of typings. (For eg. I am using an interface/class which is used by producer and consumer to keep the input/outputs types strongly typed, at least in TypeScript) With 1 queue, 1 handler, I will be perfectly using strong types when communication happens between services.

**Comment by WonderPanda** [comment]
I don't think number of queues should be a concern for you at all unless you think that it could increase to be hundreds of thousands or millions

**Comment by eduscrakozabrus** [comment]
@RabbitSubscribe({
    exchange: 'messenger',
    routingKey: 'user-send-message',
    queue: 'messenger',
  })

и 
  @RabbitSubscribe({
    exchange: 'messenger',
    routingKey: 'customer-send-message',
    queue: 'messenger',
  })

there is no difference, the functions are called randomly. Why specify routingKey in the decorator at all. The documentation indicates that the decorator determines what will be executed to select the handler, but routingKey is simply ignored, which is misleading. 

Translated with www.DeepL.com/Translator (free version)

**Comment by WonderPanda** [comment]
@eduscrakozabrus You have two handlers which are both bound to the same queue. This is an anti pattern. When you do this, all messages from both routing keys all end up in the same queue, but two handlers are connected to that queue so it is not deterministic which handler will receive the message.

The only way to safely re-use the same queue is if you add conditional logic inside the handler to check the contents of the message but that defeats the purpose of the entire library.

Just don't re-use queues like this and you won't have problems

**Comment by kasir-barati** [comment]
I know I am commenting on this closed issue too late but just to share my thought I decided to comment here.

@WonderPanda maybe this could be one use case:

- We have a queue named `audit_log.logs`.
- Then we have these routing keys: `*.created`, `*.updated`, `*.deleted` for this queue:

  I need to do something similar to this in my _audit-log service_ (**you can find a working example at the end of this comment**):
  ```ts
  @RabbitRPC({
    exchange: 'amq.topic',
    queue: 'audit_log.logs',
    routingKey: ['*.created', '*.updated', '*.deleted']
  })
  async log(@RabbitPayload() message: Entity) { await this.repo.create(message) }
  ```
  E.g. users microservice might publish messages with these routing keys: `user.created`, `user.deleted`, `user.updated` in a topic exchange. **We need to just log them in our _audit-log microservice_**.

- Notifications microservice  has its own business logic for different routing keys:

  ```ts
  @RabbitRPC({
    exchange: 'amq.topic',
    queue: 'notification.user_registration',
    routingKey: 'user.created',
  })
  async sendWelcomeEmail(@RabbitPayload() message: User) { await this.mail(message.email, 'welcome'); }

  @RabbitRPC({
    exchange: 'amq.topic',
    queue: 'notification.user_deletion',
    routingKey: 'user.deleted',
  })
  async sendPartingGift(@RabbitPayload() message: User) { 
    await this.mail(message.email, 'Here is an ebay 10% discount code');
  }
  ```

## You can find a complete NestJS app which demonstrates this [here](https://github.com/kasir-barati/docker/tree/main/docker-compose-files/rabbitmq/topic-nestjs). Loved [my docker repo](https://github.com/kasir-barati/docker)? Give it a :star:.
