### ISSUE TITLE
RabbitMQ: dynamic Subscription

### ISSUE THREAD

**Issue by nidomiro** [golevelup/nestjs#322]
I'm trying to make the topic of a subscription configurable [via NestJs Module-Initialization].

The problem is, decorators cannot use values available at Object creation time.

Is there a way to create a Subscription 'manually' and keep the benefits of the Decorator-variant (automatic reconnect, ...)?

**Comment by WonderPanda** [comment]
This is a major shortcoming of the NestJS configuration system and why I strongly suggest that configuration should occur separate from DI/Module initialization. The config package `@golevelup/profiguration` which I use for my own projects specifically gets bootstrapped at the start of your application before any imports are evaluated so you can actually use it to configure decorators.

If you want to stick with your existing config system you can definitely manually set up subscriptions/rpc in module init. Just inject the AmqpConnection and call the methods directly
