### ISSUE TITLE
RabbitMQ: inject @RabbitSubscribe decarator properties from .env

### ISSUE THREAD

**Issue by federicogatti** [golevelup/nestjs#324]
I need to inject different properties in @RabbitSubscribe() decorator based on my ._env_ file likes

```
  @RabbitSubscribe({
    routingKey: process.env.RABBITMQ_QUEUE_NAME,
    queue: process.env.RABBITMQ_QUEUE_NAME,
    exchange: process.env.RABBITMQ_QUEUE_NAME,
  })
```

Actually I'm not able to inject the properties using the process.env variable or using the NestJS Config Service.

Can you explain me how do that? I don't find anything in the documentation

**Comment by WonderPanda** [comment]
This is not an issue with this library and is a symptom of how Config loading is done with NestJS. Please follow up with discussion here: https://github.com/golevelup/nestjs/discussions/323 where someone is asking similar quesitons

**Comment by WonderPanda** [comment]
I have updated the answer in the linked discussion to provide two different ways to accomplish what you're looking for. Please continue discussion there if the answers are not sufficient for your use case
