### ISSUE TITLE
Add support for dispatching scheduled events with an injectable service

### ISSUE THREAD

**Issue by ivorpad** [golevelup/nestjs#326]
I read the code in #182, but it does not explain how to use it, and the documentation does not provide any information.

I noticed it detects if the event is a Hasura Scheduled Event with:

```ts
function isHasuraScheduledEventPayload(
  value: any
): value is HasuraScheduledEventPayload {
  return ['name', 'scheduled_time', 'payload'].every((it) => it in value);
}
``` 

And all it does is allow to pass the event with:

```ts
@HasuraEventHandler({
   triggerName: 'send-mail',
})
```

But you need to handle your own insert via `POST /v1/query` and pass a body with a `create_scheduled_event` type — am I right?

**Comment by WonderPanda** [comment]
@ivorpad Please see the docs here:
https://github.com/golevelup/nestjs/tree/master/packages/hasura#automatically-synchronize-hasura-metadata

You need to use the `TrackedHasuraEventHandler` decorator which will automatically update your `metadata` files. After that you just need to run `hasura metadata apply` in order to synchronize the changes. You do not need to use any APIs eg `create_scheduled_event`

**Comment by ivorpad** [comment]
@WonderPanda Please don't close this, I've read the docs.

The `TrackedHasuraEventHandler` decorator doesn't take an `scheduled_time` option. e.g. `HasuraScheduledEventPayload` — in fact, I don't think this interface is being used ? only in this test.

https://github.com/golevelup/nestjs/blob/bcb6fc6b4294ac2200f7b85a0c4ccd62bfec5782/packages/hasura/src/tests/hasura.event-handling.spec.ts#L154-L169

---

https://github.com/golevelup/nestjs/blob/bcb6fc6b4294ac2200f7b85a0c4ccd62bfec5782/packages/hasura/src/hasura.interfaces.ts#L107-L113

What I'm trying to achieve is creating a One-off Scheduled Event: https://hasura.io/docs/latest/graphql/core/scheduled-triggers/create-one-off-scheduled-event.html

**Comment by WonderPanda** [comment]
@ivorpad Its in the Readme under the section called [Registering Scheduled Event Handlers](https://github.com/golevelup/nestjs/tree/master/packages/hasura#registering-scheduled-event-handlers)

You just use the `TrackedHasuraScheduledEventHandler` decorator for scheduled stuff.

**Comment by ivorpad** [comment]
@WonderPanda I think you're confused, It is not the same. How would you pass a `scheduled_time` to `TrackedHasuraScheduledEventHandler`? It takes a `cronSchedule` config option and not a `scheduled_time`. 

https://github.com/golevelup/nestjs/blob/51609a9225748752153e831ffbf1041cb168144b/packages/hasura/src/hasura.decorators.ts#L26-L35

https://github.com/golevelup/nestjs/blob/51609a9225748752153e831ffbf1041cb168144b/packages/hasura/src/hasura.interfaces.ts#L91-L97

**Comment by WonderPanda** [comment]
Are you trying to schedule a one off scheduled event using a decorator? I don't see how it would make sense at all to do that. Decorators are evaluated once during code import when the application boots up so everytime your application starts up it would schedule a new event at a hard-coded time? What value would you put in the `schedule_time` if you were going to do this? Would you be constantly changing the decorator arguments manually everytime you made a new release or something?

If you want to do scheduled events it makes way more sense to do it at runtime using a NestJS Injectable service to queue something to be run in the future based on application events. Is this what you're actually trying to accomplish?

I think this would be a useful feature to provide some Injectable services from this library that support common interactions with the Hasura API so under the hood it would take care of calling `POST /v1/query and pass a body with a create_scheduled_event` for you

**Comment by ivorpad** [comment]
@WonderPanda 

> I think this would be a useful feature to provide some Injectable services from this library that support common interactions with the Hasura API so under the hood it would take care of calling POST /v1/query and pass a body with a create_scheduled_event for you

And this was my question 😋

Alright I'll think in something. Would you like me to give it a try and send a PR with this feature?

**Comment by WonderPanda** [comment]
Sure, if you feel like trying to build this feature I would gladly take contributions
