### ISSUE TITLE
RabbitSubscribe not setup correctly when routingKey is empty string

### ISSUE THREAD

**Issue by 3fd** [golevelup/nestjs#328]
No messages are received for a fanout exchange subscription with 
```ts
@RabbitSubscribe({ exchange: 'logs', routingKey: '' })
```

This is a regression introduced in #317 

https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L441

**Comment by WonderPanda** [comment]
I'll try and get a fix out for this after work this evening

**Comment by WonderPanda** [comment]
Fix is available in @golevelup/nestjs-rabbitmq@1.18.1
