### ISSUE TITLE
Multiple concurrent consumers and Prefetch Count at queue level 

### ISSUE THREAD

**Issue by rishabh-banknovo** [golevelup/nestjs#334]
I want to spin up multiple consumers count and also want to add prefetch level at queue level. Please advise.

**Comment by underfisk** [comment]
@rishabh-banknovo You have now the capability to have multiple channels and define `prefetchCount`. If that doesn't help you, i would need a little bit more details

**Comment by WonderPanda** [comment]
I definitely think this is covered by the recent additions of multiple connections. @rishabh-banknovo if it doesn't cover your use case feel fee to open this back up but I'm going to close it for now
