### ISSUE TITLE
Create a more Unified Config and Module Bootstrap Experience for RabbitMQ

### ISSUE THREAD

**Issue by WonderPanda** [golevelup/nestjs#34]
Update the RabbitMQModule builder methods to use the `forRoot` and `forRootAsync` to stay with the conventions of the existing NestJS ecosystem. Investigate a better way to allow for injection of a config service to allow people to pull the necessary AMQP config information from their existing tools for config management.

**Comment by WonderPanda** [comment]
@kjetilhp The newest published versions of @nestjs-plus/rabbitmq contain the forRoot and forRootAsync static configuration methods

**Comment by kjetilhp** [comment]
Nice, tested the new package, so what I wanted works:
```
RabbitMQModule.forRootAsync({
      useFactory: async (configService: ConfigService) => {
        return await configService.messagingConfig()
      },
      inject: [ConfigService],
    }),
```

**Comment by WonderPanda** [comment]
Awesome! Glad that it's working out for you. As part of this changed I also added some utility in the `@nestjs-plus/common` package to facilitate this async configuration pattern. If you're ever building modules that need to support this config pattern feel free to check it out
