### ISSUE TITLE
How to use custom logger in AmqpConnection

### ISSUE THREAD

**Issue by Scrib3r** [golevelup/nestjs#341]
Hello everyone. I have next configuration of Rabbit module in my app.module:
```ts
    LoggerModule.forRoot({
      appName: appConfig.app,
      env: appConfig.env,
      serverEnv: appConfig.serverEnv,
      level: appConfig.logger.level,
      format: appConfig.logger.format as 'file' | 'json',
      colorize: appConfig.logger.colorize,
      silent: appConfig.logger.silent,
    }),
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      imports: [RabbitConfigModule],
      inject: [RabbitMqConfigService, AppConfigService],
      async useFactory(config: RabbitMqConfigService, applicationConfig: AppConfigService) {
        return {
          uri: config.url,
          prefetchCount: 1,
          connectionInitOptions: { wait: true },
          connectionManagerOptions: {
            connectionOptions: {
              clientProperties: {
                connection_name: [applicationConfig.app, `[${applicationConfig.env}]`].join(' '),
              },
            },
          },
          exchanges: [
            {
              name: rabbitExchangesConfig.payments.exchange,
              type: 'direct',
            },
          ],
        };
      },
    }),
```

I have disabled logger in my main.ts with next buffering:
```ts
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    logger: false,
    bufferLogs: true,
  });
  const logger = new MyLogger('APP');
  app.useLogger(logger);
```

But how I received a lot of logs from AmqpConnection.ts. I see that it use `Logger` class from `nestjs/common`. But can I use another instance of logger? For example, `MyLogger` from example?

**Comment by bogulean** [comment]
Hello, same here, the ability to override default logger would be much appreciated. Or at least a workaround...

**Comment by underfisk** [comment]
I'll take a look into this matter and see if we can provide a custom logger
@Scrib3r The code looks right to me but we do not use the logger defined for Nestjs, we could but i think having a factory would be better and give you more flexibility.

**Comment by Scrib3r** [comment]
@underfisk It sounds good. I think that having a logger factory for external modules such as this is a good idea. May be would it be a factory with implementation specific interface for logger?

**Comment by underfisk** [comment]
As i have explained in one of the issues that have requested the same feature for the hasura module, if you override Nestjs logger all the instantiated loggers from our rabbitmq package will directly stream the logs to your custom logger, now i haven't checked in-depth but from some small tests, all my amq goes through my custom logger
