### ISSUE TITLE
deadLetterExchange and deadLetterRoutingKey are not working?

### ISSUE THREAD

**Issue by yogiGueta** [golevelup/nestjs#345]
I am trying to implement a retry mechanism, so I tried to use deadLetterExchange and deadLetterRoutingKey in my consumer, but when I put those params and restart the service,  the service is stuck and did not finish the initialization step. 

After some investigation its looks like Rabbit service is stuck on an infinite loop in the function: 
node_modules/@golevelup/nestjs-rabbitmq/lib/amqp/connection.js --> setupSubscriberChannel --> Args.assertQueue function and throwing:  Unhandled rejection Error: Channel ended, no reply will be forthcoming

**Comment by underfisk** [comment]
@yogiGueta Could you provide me a repo to setup faster locally? I have removed the code from the comment so that its less confusing

**Comment by apichai-brnp** [comment]
![image](https://user-images.githubusercontent.com/12517161/153066550-95bbcef6-36df-4d0b-b398-88be55c1f28f.png)
I found message error

**Comment by underfisk** [comment]
@Ma2iio Did it start after we upgrade to v8? It seems to be an underlying `amqlib` error but if you could provide us a repo and the steps to make this happen, i'll take a look and see what might be causing this

**Comment by apichai-brnp** [comment]
@underfisk Thank you, I resolved by delete exchange and queue. It's work

**Comment by underfisk** [comment]
I'm glad that you've a solution
