### ISSUE TITLE
Validation of message payloads structure

### ISSUE THREAD

**Issue by in-emilio** [golevelup/nestjs#352]
I tried to validate message payload structure using class-validator dtos and it does not work. Anyone who knows how to solve this?

**Comment by underfisk** [comment]
Which packages are you using in order to validate the DTO? If possible could you provide a snippet/repro?

**Comment by WonderPanda** [comment]
@in-emilio As underfisk mentioned we need more information here. How are you attempting to use class-validator? Are you using Pipes or Interceptors, or something else?

**Comment by muhammadzadeh** [comment]
It seems, that to bring validations to work, you should use the `@RabbitPayload()` decorator.
`createTransaction(@RabbitPayload() msg: CreateTransactionDto, amqpMsg: ConsumeMessage){}`
