### ISSUE TITLE
Multiple stripe webhooks

### ISSUE THREAD

**Issue by annakopp** [golevelup/nestjs#355]
Is it possible to set this up to work with two different webhook endpoints? (I need one for connect accounts & one for direct accounts.)

**Comment by CarsonF** [comment]
You can setup stripe with one webhook url and use mulitple `@StripeWebhookHandler` with different events

**Comment by annakopp** [comment]
@CarsonF That's what I was doing initially but then I needed to create a webhook that used stripe connect (stripe sends different events to direct vs connect webhooks). 

I think I can create the 2nd webhook to hit the same endpoint, but the webhook secret will be different, so that won't work.

**Comment by CarsonF** [comment]
Ahh my bad you're right.

I think you could configure the module twice with a different controller prefix. The decorator uses their discovery library which I believe is global, so both modules would find all handlers. Each webhook controller though would use its own signing secret verification first.
Worth a shot.

**Comment by WonderPanda** [comment]
I'd definitely try out the suggestion provided by @CarsonF first and see if it works out for you. In a future version we might be able to provide support for multiple configurations with some kind of name value that allows you to correlate webhook handlers to only be linked to the specific signing secret that matters for them.

Are there any major differences between connect accounts and direct accounts other than the signing secret?

**Comment by annakopp** [comment]
> Are there any major differences between connect accounts and direct accounts other than the signing secret?

I think that's the only difference as far as I understand.

**Comment by ofilipowicz** [comment]
@WonderPanda I tried the solution suggested by @CarsonF however I was unable to make it work. It looks like it's attempting to always use a secret from the first module in the app imports list. It results in only half events being authenticated. Rest of them return 401.

**Comment by ofilipowicz** [comment]
I tried multiple setups of two webhook endpoints - two separate modules, two configurations in one module. Unfotunately nothing worked. The issues I encounted during my testing where:

- Basically, one of the configurations didn't expose endpoint at all. It kept returning 404 in Stripe dashboard.
- The other endpoint was established but returned an error 
`No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe`

Once I removed any one of them and kept just one, it started to work perfectly. 

Is there any other way to handle two webhook secrets? I'll have to switch to some custom endpoint otherwise :(

**Comment by laserchicken** [comment]
As a last resort you could probably monkey patch it:
```
        StripePayloadService.prototype.tryHydratePayload = function (
          signature: string,
          payload: Buffer
        ) {
          const decodedPayload = JSON.parse(
            Buffer.isBuffer(payload) ? payload.toString('utf8') : payload
          );

          return this.stripeClient.webhooks.constructEvent(
            payload,
            signature,
            decodedPayload.account
              ? stripeWebhookConnectSecret
              : stripeWebhookDirectSecret
          );
        };
```

**Comment by nusu** [comment]
This is really a need, Direct and Connect hooks should be processed in different endpoints.
I use Direct for my business webhooks, subscription start, end, upgrade etc.
Connect is for people who have connected their stripe accounts so we can get updates from their accounts.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1702215/185347926-981ca6ff-2ee0-4ccc-8440-15143d3eb8e1.png">

I'm happy to collaborate on implementing that, if you can guide me over

**Comment by nusu** [comment]
@underfisk can we have a release on #522 ?

**Comment by underfisk** [comment]
> @underfisk can we have a release on #522 ?

I don't have permissions to do that, only @WonderPanda
