### ISSUE TITLE
Is it possible to Subscribe multipe row?

### ISSUE THREAD

**Issue by AnanthGopal** [golevelup/nestjs#360]
Hi @WonderPanda 

Below code, i used to Subscribe data from Rabbimq, but i got only one row from rabbitmq, but I need to receive bulk rows, Is it possible?

 
 ```
@RabbitSubscribe({
    exchange: 'pmacct',
    routingKey: 'acct',
    queue: 'rpc-queue',
    errorHandler: (exchange, msg, e) => RabittmqService.errorHandler(exchange, msg, e),
  })
  public async pubSubHandler(msg: {}) {}
```

**Comment by underfisk** [comment]
@AnanthGopal What do you mean by rows? Do you mean that your payload dto is a row data format? I'm not sure if you want to receive multiple rows (in the context that you're talking about your DTO) or that you want multiple events to be consumed at once by the subscriber? 
When a message is sent, it is singularly consumed

**Comment by AnanthGopal** [comment]
thank you for your response @underfisk 

For example, I received payload data like below
`{"name":"test1"}`

But i try to receive payload as an array-like below

`[{"name":"test1"},{"name":"test2"},{"name":"test3"}]`

**Comment by underfisk** [comment]
@AnanthGopal I would advocate making some property `rows` where you have your array but even at the root level it should do just fine. Test something like 
```
{ "rows": [{whatever data}] }
```

**Comment by AnanthGopal** [comment]
@underfisk  Can you provide sample code for consume multiple rows ?

**Comment by underfisk** [comment]
> @underfisk Can you provide sample code for consume multiple rows ?

All you have to do is go over your publisher code (where you actually send the rows) and make an object where the rows are inside the `rows` property

**Comment by AnanthGopal** [comment]
@underfisk  yes i can publish multiple rows to Rabbimq but I want to consume or receive or subscribe multiple rows from rabbitmq(Now I receive one by one row from Rabbbimq queue)

**Comment by underfisk** [comment]
@AnanthGopal I will have to play around with what you're trying to accomplish, could you create a github repro containing a sample code so i can fetch the project and take a look?

**Comment by WonderPanda** [comment]
@AnanthGopal Are you referring to treating messages as an RXJS Observable?

**Comment by WonderPanda** [comment]
Closing for now since there is nothing actionable for us. Feel free to open again if you can provide a more clear understanding of what you'd like to accomplish
