### ISSUE TITLE
Update documentation to explain that a Type is needed for typescript to get "options" of an exchange working.

### ISSUE THREAD

**Issue by iangregsondev** [golevelup/nestjs#361]
Hi,

Great library!

Maybe we could update the documentation, I had to install the following to get code completion working on options of an exchange in the Options

```
yarn add @types/amqplib -D  
```

Cheers

**Comment by underfisk** [comment]
@iangregsondev Thanks for brining this up, i can take a look but i'll need a clear repro if you can provide one to understand exactly what this provides

**Comment by iangregsondev** [comment]
It provides typescript types, without it there is no code completion on the "options"

I can get a repo to you but it will be the weekend..

But in your code you have 

```
import * as amqplib from 'amqplib';
```

But with no types, there is no code completion on

![image](https://user-images.githubusercontent.com/2370364/150202955-f8819859-cbbf-4490-a646-b3f334d4ec18.png)


Once you have it installed then you can see it here

![image](https://user-images.githubusercontent.com/2370364/150203093-c7df07a6-ffad-4d6c-b2de-ebb2260310e1.png)

So in the calling code the "exchanges" is an "any"

![image](https://user-images.githubusercontent.com/2370364/150203255-d60d7ad1-a0a0-4115-a9fb-338f8164e602.png)

Let me know if you still need one, and i will try and get one over on the weekend.

**Comment by underfisk** [comment]
> It provides typescript types, without it there is no code completion on the "options"
> 
> I can get a repo to you but it will be the weekend..
> 
> But in your code you have
> 
> ```
> import * as amqplib from 'amqplib';
> ```
> 
> But with no types, there is no code completion on
> 
> ![image](https://user-images.githubusercontent.com/2370364/150202955-f8819859-cbbf-4490-a646-b3f334d4ec18.png)
> 
> Once you have it installed then you can see it here
> 
> ![image](https://user-images.githubusercontent.com/2370364/150203093-c7df07a6-ffad-4d6c-b2de-ebb2260310e1.png)
> 
> So in the calling code the "exchanges" is an "any"
> 
> ![image](https://user-images.githubusercontent.com/2370364/150203255-d60d7ad1-a0a0-4115-a9fb-338f8164e602.png)
> 
> Let me know if you still need one, and i will try and get one over on the weekend.

Thanks, i see the problem now and i think we can actually incorporate the types

**Comment by iangregsondev** [comment]
No worries, as I say if I install them in my own project then it works..

Ohh, I noticed one other thing as well, its not urgent - well none of these are, everything works great..

But there is a definition of "channels" that you can pass, there are no types fro this i.e.

![image](https://user-images.githubusercontent.com/2370364/150203846-082c20a7-3d4c-49ae-bccc-e18e0cb57f87.png)

Thanks again for a great library, its saved me a lot of effort wrapping rabbitmq.

**Comment by underfisk** [comment]
#367 contains an improvement on how the types are being imported and its already merged to master so once @WonderPanda is available to deploy a new version you'll be able to see the types being working as expected
