### ISSUE TITLE
RabbitMQ controllers support

### ISSUE THREAD

**Issue by underfisk** [golevelup/nestjs#369]
Previously I had suggested that we migrate to microservices adapter, well the way that microservices packages work with what we have as services is using controllers which gives the developer more flexibility to leverage things such as pipes, guards, etc etc

My proposal here is to support both services and controllers and help people to slowly migrate (having two ways of defining handlers etc can be confusing but i want to make it as simple as possible)

If anyone appreciates the idea, has any feedback at all just let me know, i haven't yet started but this doesn't take that much to do

**Comment by jeremylvln** [comment]
It would be neat indeed, one step forward hexagonal architecture \o\

**Comment by verti4cal** [comment]
+1

otherwise i have to rewrite any service function or have to implement a second function as a wrapper.

```
  async userFindOneByUuidQuery(query: QueryUserFindOneByUuid): Promise<User> { // used for the rpc
    return this.userModel.findOne({ uuid: query.uuid });
  }

  async userFindOneByUuid(uuid: string): Promise<User> { // used internal
    return this.userModel.findOne({ uuid: uuid });
  }
```
