### ISSUE TITLE
Feature requeset: setting message headers

### ISSUE THREAD

**Issue by norberto-e-888** [golevelup/nestjs#372]
Hi,

At my company we have a use case for writing to the message headers to set the following properties:

'x-retry': counter of retries attempts
'x-retry-limit': limit number of retry attempts
'x-delay': number of milliseconds the message should be delayed

could I get some guidance on how this might be achieved using the underlying amqp client, so I can potentially contribute said functionality in case the core team is busy. It is quite urgent for us...

Thank you

**Comment by underfisk** [comment]
@norberto-e-888 This could be achieved during the publish using `headers` property in message properties but our rabbitMQ module isn't forwarding that, i can provide this feature

**Comment by WonderPanda** [comment]
Thanks @underfisk for super fast turn around to help out norberto. This is available now in `@golevelup/nestjs-rabbitmq@1.21.01`.

Let us know if it accomplishes your goals

**Comment by norberto-e-888** [comment]
Thanks a lot for the super fast support. There is just one thing I forgot to mention, our use case requires not only to set headers on publish but also on message re-queueing, meaning when we return and instance of Nack(true). Any ideas on how we might achieve this?

**Comment by underfisk** [comment]
@norberto-e-888 After testing for a while it seems that the message that is consumed is simply forward but if you wish to customize the error behavior you can do that and provide your custom error handler using `errorHandler` property. If this doesn't help you i can test more in-depth but having a repro by then would be then also useful

**Comment by norberto-e-888** [comment]
@underfisk Looking at the args of `errorHandler` it looks quite promising as it exposes the headers, I will experiment to see if these headers are read-only or if we can write to them. I will report back my results. Thanks again for all the help.
