### ISSUE TITLE
RabbitMQ logging - Unable to replace RabbitMQ logger with an external logger

### ISSUE THREAD

**Issue by shakedo** [golevelup/nestjs#379]
In RabbitMQ module, ConsoleLogger (@nestjs/common) is used for logging and by that it's not possible to replace it with an external logger as described here: https://docs.nestjs.com/techniques/logger#use-external-logger

The solution is to use Logger (@nestjs/common) instead of ConsoleLogger in these files:

packages\rabbitmq\src\amqp\connection.ts
packages\rabbitmq\src\rabbitmq.module.ts

**Comment by underfisk** [comment]
@shakedo You can extend `ConsoleLogger` and we shouldn't be going back to the deprecated `Logger`, you can see at: https://docs.nestjs.com/techniques/logger#extend-built-in-logger that you can extend and then provide your logger

**Comment by shakedo** [comment]
Thois code for example, dosent replace RabbitMQ logs and do replace NestJs logs:

class MyLogger extends ConsoleLogger {
  log(message: any, context?: string) {
    super.log(message + '!!!!!!!', context);
  }
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bufferLogs: true });
  app.useLogger(new MyLogger());
  app.flushLogs();
  await app.listen(3000);
}
bootstrap();



[Nest] 12380  - 24.01.2022, 16:50:28     LOG [NestFactory] Starting Nest application...!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [NestFactory] Starting Nest application...!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [InstanceLoader] LoggerModule dependencies initialized!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [NestFactory] Starting Nest application...!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [NestFactory] Starting Nest application...!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [InstanceLoader] LoggerModule dependencies initialized!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [InstanceLoader] DiscoveryModule dependencies initialized!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [InstanceLoader] AppModule dependencies initialized!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [InstanceLoader] RabbitMQModule dependencies initialized!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [RoutesResolver] AppController {/}:!!!!!!!
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [RouterExplorer] Mapped {/, GET} route!!!!!!!
**[Nest] 12380  - 24.01.2022, 16:50:28     LOG [RabbitMQModule] Initializing RabbitMQ Handlers**
[Nest] 12380  - 24.01.2022, 16:50:28     LOG [NestApplication] Nest application successfully started!!!!!!!
**[Nest] 12380  - 24.01.2022, 16:50:28     LOG [AmqpConnection] Successfully connected to a RabbitMQ broker**
**[Nest] 12380  - 24.01.2022, 16:50:28     LOG [AmqpConnection] Successfully connected a RabbitMQ channel "AmqpConnection"**

**Comment by underfisk** [comment]
@shakedo Thanks for the repro, I'll need to investigate and see why's that happening

**Comment by underfisk** [comment]
After checking this it seems to be an internal nestjs issue, I've communicated to see what we should be doing differently, anyway it should work as it was with `Logger`
