### ISSUE TITLE
Vulnerabilty in shortid dependency

### ISSUE THREAD

**Issue by vincent-benbria** [golevelup/nestjs#383]
ShortId is deprecated and vulnerable: https://github.com/dylang/shortid

Exposure of Sensitive Information to an Unauthorized Actor in nanoid.
Path:  @golevelup/nestjs-rabbitmq > @golevelup/nestjs-common > shortid > nanoid 

Should be replaced by NanoID: https://github.com/ai/nanoid

**Comment by WonderPanda** [comment]
@vincent-benbria Are you interested in contributing this change?

**Comment by vincent-benbria** [comment]
Done. This PR does 20 letters for random IDs instead of the previous 7 letters. Only need to change `nanoid()` to `nanoid(7)` to reduce it, but it obviously increases the chances of a collision.
