### ISSUE TITLE
RabbitMQ: events are being consumed before application is ready on Nest 8

### ISSUE THREAD

**Issue by ckfngod** [golevelup/nestjs#386]
Hey all, I'm running into an issue where RabbitMQ consumers start up and consume events before the main Nest application is completely initialized. This started happening after we migrated from Nest 7 to Nest 8. I've resolved the issue in my application by moving the RabbitMQ module to the very end of the application module imports list:
```
// consumers start before application initialized
@Module({
  imports: [
    RabbitMQModule,
    ...ModulesThatDependOnRabbitMQ
  ]
})

// consumers start after application initialized 
@Module({
  imports: [
    ...ModulesThatDependOnRabbitMQ,
    RabbitMQModule
  ]
})
```

Package versions:
```
@nestjs/core@8.2.6
@nestjs/common@8.2.6
@golevelup/nestjs-rabbitmq@1.18.1
```

Is anybody else seeing this behaviour?

**Comment by underfisk** [comment]
@ckfngod I'm not sure if the problem was actually from v7 to v8, the lifecycle we use is the initialization of the module which means each provided `RabbitMQModule` will spin its connections etc etc
What I could do is provide a way to perform what we do at `onModuleInit` and actually bind at `onApplicationBootstrap` but i need to play with it first
Could you just provide a sample github repo with an app to see your use case first hands?

**Comment by WonderPanda** [comment]
I think it should probably be fine for us to move all the logic from `onModuleInit` to `onApplicationBootstrap` like you suggested.

@ckfngod I don't think the order of the imports actually matters in your case, its more likely that its just a lucky thing with the timing that you happen to see a difference when you reorder the array

**Comment by ckfngod** [comment]
@underfisk @WonderPanda Thanks for the responses. Yeah it looks like it's definitely lucky timing, wasn't able to get it to work in my sample app. I'm seeing issues specifically with this in combination with a GRPC microservice. Rabbit consumers will begin processing events before the GRPC service is ready so as the application starts up it will throw a bunch of errors but afterwards it works fine.

Sample app is here: https://github.com/ckfngod/rabbitmq-app-init-issue

Start up the app to assert the queue, stop the app, publish a couple events to the queue then start the app again and you should see the issue.

**Comment by farzadso** [comment]
Is a fix for this in progress?

**Comment by farzadso** [comment]
> Is a fix for this in progress?

This is what happens when you comment something before testing it :D

All my `onModuleInit` functions are working before the app consumes messages now.

Thanks for the fix.
