### ISSUE TITLE
How to open multiple connection and use in their respective modules?

### ISSUE THREAD

**Issue by Deegiimurun** [golevelup/nestjs#393]
Hello, is it possible to create multiple connection and use in their respective modules? I tried like

`@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: 'exchange1',
          type: 'headers',
        },
      ],
      uri: 'amqp://username:password@server1:5672',
      enableControllerDiscovery: true,
    })
  ],
  controllers: [FirstController]
})
export class FirstController {}`

`@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: 'exchange2',
          type: 'headers',
        },
      ],
      uri: 'amqp://username:password@server2:5672',
      enableControllerDiscovery: true,
    }),
  ],
  controllers: [SecondController],
})
export class SecondController {}`

it created 2 connection but same queues on both rmq server without respecting modules.

**Comment by Deegiimurun** [comment]
I tried solution like https://github.com/golevelup/nestjs/issues/78#issuecomment-585641143. But it is same result with 2 connection opened and created same queues on them

**Comment by underfisk** [comment]
@Deegiimurun The way it is designed isn't going to use the same module instance, so the best thing would be to only import the module once and allow the discovery to do its own thing. A few months ago I thought about implementing re-usable connections so the module would share connections/metadata across all instantiated modules.
If this is not an intended thing we'll have to revisit but i will ask you if you can create a repro for us

**Comment by Deegiimurun** [comment]
Hello i just created repro in https://github.com/Deegiimurun/nest-rqm-repro

For simplicity i used docker compose to start 2 rabbitmq instance. How to run:

1) run `docker compose up --build`
2) It starts 2 rabbitmq instance on port 5001, 5002 (15001, 15002 for web interface) with username and password of guest:guest.
3) After started use nest cli to run nest project with command `nest start --watch`

Expected behaviour:
Since RabbitMq1Module instantiate with port 5001 instance of rabbitmq, RabbitMq2Module instantiates with port 5002 instance of rabbitmq those 2 module's controllers, providers should use different connection to connect different rabbitmq servers. RabbitMq1Controller connects and creates queue **rpc-queue1**, RabbitMq2Controller connects and creates queue **rpc-queue2** with their respective connections. Now  rabbitmq1 server should have **rpc-queue1** queue and  of rabbitmq2 server should have **rpc-queue2** queue.

Problem:
Both rabbitmq1 and rabbitmq2 servers have **rpc-queue1**, **rpc-queue2** queues.

**Comment by Deegiimurun** [comment]
Hi, @underfisk is there any update on this one?

**Comment by underfisk** [comment]
@Deegiimurun Hey, i'm sorry but i've been out but once i'm able too i'll pick the repro and review this issue

**Comment by andrewda** [comment]
Hey @Deegiimurun & @underfisk, I've been running into the same issue. I'm happy to work on a PR to add this functionality if it's not currently possible, but might need some guidance (or at least a high-level overview of how it should be implemented).

**Comment by underfisk** [comment]
@andrewda The way it is working right now only contains a single connection which means that in order to support multiple you need to adapt (https://github.com/golevelup/nestjs/blob/18ca7996ca66d9681ff763658cfc5256f9d26405/packages/rabbitmq/src/rabbitmq.module.ts#L64) the factory to push new connections to an array of connections rather than a single connection object. The implementation should be something like we did for the channels if you look at the merged PR's where you always have a default connection and we can specify named connections/URL and simply pick that

**Comment by andrewda** [comment]
Great, thanks for the details @underfisk! I'll see what I can do.
