### ISSUE TITLE
RabbitMQ: Support void as SubscribeResponse 

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [golevelup/nestjs#396]
Currently `SubscribeResponse` is the type `Nack | undefined`.
https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/handlerResponses.ts#L10
```ts
export type SubscribeResponse = Nack | undefined;
```

In my application I can not use the `@RabbitSubscribe` annotation, because I need to extract the exchange from options provided as provider, so I have to call the `createSubscriber` function of the `AmqpConnection`. But the handler does not allow to have no return because this does not count as `undefined` so I have to explicitly return it.

```ts
await this.amqpConnection.createSubscriber(
  async (msg) => {
    console.log(msg);
    return undefined;
  },
  {
    exchange: this.options.amqp.exchange,
    routingKey: 'example.execute',
    queue: 'example-queue',
  },
);
```

It would be nice to just leave the return away like it would be possible when using the annotation:
```ts
await this.amqpConnection.createSubscriber(
  async (msg) => {
    console.log(msg);
  },
  {
    exchange: this.options.amqp.exchange,
    routingKey: 'example.execute',
    queue: 'example-queue',
  },
);
```

Could there be some sideeffects by changing the `SubscribeResponse ` by adding also void?
```ts
export type SubscribeResponse = Nack | undefined | void;
```

**Comment by underfisk** [comment]
@Samuel-Schober-USU Could you create the PR that will provide this feature? I don't think having void will have any effect because undefined would be the value gathered if nothing is returned
Any contribution would be more than welcome!
