### ISSUE TITLE
provide an example of re-exporting the RabbitMQModule

### ISSUE THREAD

**Issue by Loki-Afro** [golevelup/nestjs#399]
Could you please provide an example the RabbitMQModule is re-exported and an AMQPConnection is provided globally?

I am coming from this issue https://github.com/golevelup/nestjs/issues/246#issuecomment-808472225 and i'm struggling to get it working.

Thanks

**Comment by maciejtutak** [comment]
At the end of nest.js Modules [documentation](https://docs.nestjs.com/modules#dynamic-modules) there is a bit about exporting a dynamic module:

> If you want to in turn re-export a dynamic module, you can omit the forRoot() method call in the exports array:

```
import { Module } from '@nestjs/common';
import { DatabaseModule } from './database/database.module';
import { User } from './users/entities/user.entity';

@Module({
  imports: [DatabaseModule.forRoot([User])],
  exports: [DatabaseModule],
})
export class AppModule {}
```

Therefore, I think you can do something like this:

```
@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      uri: 'amqp://username:pass@host:5672',
      exchanges: [{...}]
      connectionInitOptions: { wait: false },
    }),
  ],
  exports: [RabbitMQModule],
})
export class SharedRabbitModule {}
```

and you should be able to use `SharedRabbitModule` across your application.

**Comment by underfisk** [comment]
@Loki-Afro No it isn't re-used, each time you have a `RabbitMQModule` it will create all its connections scoped to that import, each time you have import the root module it will not share any connections therefore as @maciejtutak probably having a shared module would be the best solution if you wish to re-use connections
