### ISSUE TITLE
How Queues are created automatically on application startup

### ISSUE THREAD

**Issue by ahmednawazkhan** [golevelup/nestjs#404]
Hello. Thank you for such a great library. Can you please help me in understanding how queues can be created and attached to exchange automatically on application startup. I can see exchanges are created automatically which we define them in `RabbitMQModule.forRoot()`

**Comment by ahmednawazkhan** [comment]
it creates queue automatically

**Comment by ledger32570** [comment]
Is it possible to pass in a custom queue name?
