### ISSUE TITLE
NestJS global auth guard clashing with RabbitMQ subscriber

### ISSUE THREAD

**Issue by MateoKruk** [golevelup/nestjs#409]
I have set up a global auth guard for my app and it's intercepting the pub/sub I have setup. Anyone know how to fix this problem?

<img width="343" alt="image" src="https://user-images.githubusercontent.com/9438362/159849810-50b88a4e-eba8-4c85-8633-d7e8c9ff2294.png">

**Comment by reinaldorauch** [comment]
I think I got a similar problem with an interceptor, you can in your guard skip the validation if you're in a rabbitmq context like so:

![image](https://user-images.githubusercontent.com/2676370/160009273-b9d65a75-99a1-493b-8c53-9bff77ee7a84.png)

The `isRabbitContext` function is in the package

**Comment by underfisk** [comment]
@MateoKruk The answer provided above will fix your issue, you can decide whether your guard can ignore mrq messages
