### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by mcblum** [golevelup/nestjs#41]
Sorry for the multiple issues! Got everything working and I see the exchanges are created. Is there a process to create queue bindings or should that be implemented manually in the app?

Thank you!

**Comment by mcblum** [comment]
Edit: Ok apparently I asked the wrong question. I see the binding, but for some reason the handler function never actually gets triggered. I've tried using `*` for a routing key, and using a specific routing key. In Rabbit, all of the messages look like this:

![Screen Shot 2019-08-16 at 1 54 32 PM](https://user-images.githubusercontent.com/1761867/63191129-67db5700-c02d-11e9-9388-78576a9a3183.png)

If the binding is being created, which it is, then I assume the subscriber is working. Any idea why that function never gets called?

I also see this:
![Screen Shot 2019-08-16 at 2 19 53 PM](https://user-images.githubusercontent.com/1761867/63192552-f43b4900-c030-11e9-85d5-c3e02165dd59.png)
which I assume means that Rabbit is spamming the connection with delivery attempts, none of which are succeeding?

**Comment by mcblum** [comment]
Apparently, I'm answering my own questions here :) I didn't realize those decorators couldn't be used in a controller, which is why the binding was working but the function was never being called. I've fixed that, but don't see in the docs how to handle the response from `@RabbitRPC`. With NestJS' default implementation you'd do `.subscribe((res) => {})` but I don't see docs for that here. Am I misunderstanding how this works vs. Nest's default?

**Comment by mcblum** [comment]
Once again, given enough time, apparently I learn how to read. Should anyone else struggle with this coming from NestJS' default implementation, make sure if you want a response to your message you use ` await this.amqp.request` and not ` await this.amqp.publish`

**Comment by WonderPanda** [comment]
Hey @mcblum Sorry I didn't get back right away, I'm actually on vacation this week so haven't been keeping an eye on this. Thanks for checking out the library and I'm glad that you got things sorted out! Feel free to open issues if you do run into any issues or limitations with the current capabilities of the librar

**Comment by mcblum** [comment]
@WonderPanda all good, no worries at all! It's so great - thank you for putting this together. It took a bit for me to stop doing dumb things, but eventually, I got everything working great. I made a small wrapper around the `request` method using observables and now everything is great.

Really appreciate your hard work on this, it's so awesome to be up and running!

**Comment by WonderPanda** [comment]
@mcblum That sounds awesome! Did you want to contribute the Observable wrapper back to the library? I can see that being something more people might be interested in. I'm happy to merge pull requests for good additions

**Comment by mcblum** [comment]
@WonderPanda yeah dude, I'll do that!
