### ISSUE TITLE
Cannot find module '@nestjs/common'

### ISSUE THREAD

**Issue by andrekat** [golevelup/nestjs#414]
Hey! 

I installed the @golevelup/nestjs-rabbitmq@2.2.0 package in my Nest JS app. As soon as I run the app, I am getting following error message. 

`
Error: Cannot find module '@nestjs/common' Require stack: - D:\node_modules\@golevelup\nestjs-rabbitmq\lib\amqp\connection.js - D:\node_modules\@golevelup\nestjs-rabbitmq\lib\index.js - D:\apps\api\dist\invitation\invitation.service.js - D:\apps\api\dist\configuration-page\configuration-page.service.js - D:\apps\api\dist\configuration-page\configuration-page.module.js - 
`

I have checked my apps dependencies and can confirm that I have @nestjs/common@8.4.3 installed.

**Comment by nusu** [comment]
I had the same issue for stripe package, strangely when I looked at the package.json "@golevelup/nestjs-stripe" was not there, I added it and installed it again and the issue have been resolved. 

In your case it seems like you are trying to install rabbitmq version, maybe checkout your package.json to make sure it's in the dependencies

**Comment by underfisk** [comment]
@andrekat Can you post here your package.json because as @nusu it might happen when packages mismatch
If you prefer to give us a repro I'll review and see what's going on
