### ISSUE TITLE
Cancel Consumer and Restart

### ISSUE THREAD

**Issue by rphansen91** [golevelup/nestjs#415]
**Issue**
Currently it is possible to cancel a consumer, but their is not clear way to restart the consumer.

**Reason**
When dependencies of a Microservice are offline it is beneficial to stop the consumer and only restart when work is ready to be continued. This saves a lot of rabbit bandwidth not needing to deliver nack requeue over and over until the consumer is ready.

**Solution**
Maintain a list of the consumer options so that the canceled consumer can be restarted

**Comment by craigotis** [comment]
@underfisk This feature seems to meet one of our service needs - but I'm finding it hard to retrieve the `ConsumerTag` created once a subscriber is established. The `AmqpConnection.createSubscriber()` method returns `Promise<void>`, so it's unclear what we're supposed to pass to the cancel/resume functions to make use of this. 🤔

**Comment by underfisk** [comment]
@craigotis Would you be down to have a PR to fix this issue?

**Comment by craigotis** [comment]
@underfisk I'm happy to look into it - though it seems the subscription is created in the `addSetup()` callback for the `ChannelWrapper` from [this project](https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.ts), so it would potentially need to be implemented as an optional callback parameter in the `createSubscriber()` function.

Before I go that route though, am I missing something? How was this cancel/restart implementation intended to be used? 

**Edit:** It might look something like this: https://github.com/golevelup/nestjs/pull/472

**Comment by underfisk** [comment]
@craigotis Your PR looks good to me but i would advocate adding some test coverage so that we can safely track whether its properly working
