### ISSUE TITLE
is publishing messages really "Fire and Forget" ? 

### ISSUE THREAD

**Issue by FahmyChaabane** [golevelup/nestjs#417]
Hello, 

First of all, i want to appreciate your work for maintaining this piece of library, it is so much needed. 
And i do believe it should be mentioned in the official NestJs documentation that if we wanna dig a little bit into rabbitmq, we could use @golevelup/nestjs-rabbitmq and not only stick to the general implementation that NestJs guys have done.

I do have one little question about the documentation tho. precisely on the part of "Publishing Messages" in here : https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#publising-messages-fire-and-forget
You guys wrote between parentheses that it is "Fire and Forget". That made me wonder : 
One, because rabbitmq specification for messages is supposed to be persistent and not fire and forget. 
Two, I did implement a light basic code example with two workers and a fanout distributed message, and the message did persistent even when i killed one worker and brougth it back. 

I am not sure if i am missing some concept ? or the documentation is not 100% correct ? I'd appreciate any help :)

**Comment by WonderPanda** [comment]
Hey @FahmyChaabane the idea of "fire and forget" isn't supposed to indicate that the message is not persisted in RabbitMQ. Instead the concept is that your application code is not expecting to get a direct response based on publishing its message.

This is in contrast to RPC where your application code *is* expecting to get a result back.

Let me know if this makes sense or if you need more clarification.

**Comment by FahmyChaabane** [comment]
@WonderPanda Thank you for the response. 
Yes, think i get it now. 
I also believe that is how brokers do their job in general, that why i got confused ^^
