### ISSUE TITLE
How to consume queues dynamically?

### ISSUE THREAD

**Issue by Deegiimurun** [golevelup/nestjs#420]
Hi I'm trying to make wrapper module around @golevelup/rabbitmq module.  Im getting config data from parent module. is it possible to consume queue dynamically? For example

@RabbitSubscribe({
    exchange: 'sms.receive',
    queue: `${SmsModule._specnum}.sms.receive`,
    routingKey: 'sms',
    queueOptions: {
      bindQueueArguments: {
        "x-match": "all",
        "type": "sms",
        "target": `${SmsModule._specnum}`
      }
    },
    allowNonJsonMessages: true
  })

As far as i investigated OnApplicationBootstrap event fires before wrapper module initialized so is there any way to get this data?

**Comment by Deegiimurun** [comment]
One solution could be register queues in RabbitMQModule.forRootAsync and use them later.

**Comment by Deegiimurun** [comment]
Okay it seems i can use static async AmqpConnectionFactory and create&manage connection myself.

**Comment by kasir-barati** [comment]
Hey @Deegiimurun, I am running into another issue, I read your code snippet and based on it I deduced that you're using headers exchange. And now I have a question for you, why you're specifying routingKey while the doc and everywhere else it is said that we do not need to specify it and it will be ignored by RabbitMQ.

And if possible I would love to see a working example of how you've configured. I have these configurations but it is not working:

```ts
import { ModuleConfigFactory } from '@golevelup/nestjs-modules';
import { RabbitMQConfig } from '@golevelup/nestjs-rabbitmq';
import { Inject } from '@nestjs/common';
import { ConfigType } from '@nestjs/config';
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import verificationApiConfig from '../configs/verification-api.config';
import { RabbitmqService } from './rabbitmq.service';
import verificationApiConfig from '../configs/verification-api.config';

const DRIVER_VERIFICATION_REQ_HEADER = 'driver-verification-req';
const DRIVER_VERIFICATION_REQ_QUEUE = 'driver.verification.req';
const HEADERS_EXCHANGE = 'amq.headers';

class RabbitmqModuleConfig
  implements ModuleConfigFactory<RabbitMQConfig>
{
  constructor(
    @Inject(verificationApiConfig.KEY)
    private readonly verificationApiConfigs: ConfigType<
      typeof verificationApiConfig
    >,
  ) {}

  createModuleConfig(): RabbitMQConfig | Promise<RabbitMQConfig> {
    const { RABBITMQ_URL } = this.verificationApiConfigs;

    return {
      uri: RABBITMQ_URL,
      exchanges: [
        {
          name: HEADERS_EXCHANGE,
          type: 'headers',
        },
      ],
      queues: [
        {
          name: DRIVER_VERIFICATION_REQ_QUEUE,
          createQueueIfNotExists: true,
          bindQueueArguments: {
            'x-match': 'any',
            [DRIVER_VERIFICATION_REQ_HEADER]:
              DRIVER_VERIFICATION_REQ_QUEUE,
          },
          routingKey: '',
        },
      ],
      connectionInitOptions: { wait: false },
    };
  }
}

@Module({
  imports: [
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      imports: [ConfigModule.forFeature(verificationApiConfig)],
      useClass: RabbitmqModuleConfig,
    }),
  ],
  providers: [RabbitmqService],
})
export class RabbitmqModule {}
```

And then in my `RabbitmqService` I have annotated a method with the following decorator:

```ts
@RabbitRPC({
  exchange: HEADERS_EXCHANGE,
  queue: DRIVER_VERIFICATION_REQ_QUEUE,
  routingKey: '',
  queueOptions: {
    bindQueueArguments: {
      'x-match': 'any',
      [DRIVER_VERIFICATION_REQ_HEADER]:
        DRIVER_VERIFICATION_REQ_QUEUE,
    },
  },
})
```

I know that I have tons of duplication (like `bindQueueArguments` which I am repeating it in two different places but I am right now just trying to get it to work, later I'll shave it). Any idea what is wrong with my code?
