### ISSUE TITLE
Returning 'true' or '1' to rabbit handler throws its handler to infinite loop

### ISSUE THREAD

**Issue by igolka97** [golevelup/nestjs#421]
Returning `true` or `1` to rabbit handler throws its handler to infinite loop. Is it expected behavior and why?

The same with `Promise.all` and promises that returns `true` or `1`

**Comment by WonderPanda** [comment]
You should not be returning anything from a method decorated with RabbitSubscribe. They should be `void` or `Promise<void>` methods
