### ISSUE TITLE
createMock does not work as expected with Prisma

### ISSUE THREAD

**Issue by wave-light** [golevelup/nestjs#424]
When mocking Prisma, `createMock` does not create jest functions for the query methods. For example:
```
const mockPrismaService = createMock<PrismaService>();
mockPrismaService.user.findUnique.mockReturnValue({id: 1, name: 'Test'});
```
The above causes a Typescript error: `Property 'mockReturnValue' does not exist on type ...`

**Comment by underfisk** [comment]
@wave-light What's does the actual object look like? Is the user defined? Is the methods in the user object defined? I've never ran into problems with nested mocks but I would like to know what's going on, if you can provide a repro then we'll be able to just get it and play around

**Comment by wave-light** [comment]
Hi @underfisk. The user is indeed defined, and the methods in it are also defined. I have created a repo to demonstrate the issue: https://github.com/wave-light/prisma-examples-graphql-nestjs
Please take a look at the last commit to see the issue. Thanks.

**Comment by underfisk** [comment]
@wave-light Can you try using spys rather than mutating the mock? Usually thats the best approach, all you need to do is to spy on the instance and then proxy the calls

**Comment by wave-light** [comment]
@underfisk That's what I ended up doing. I was just wondering why I can't call `mockReturnValue` directly on those methods in the object created by `createMock`.

**Comment by RobertDS07** [comment]
jest.spyOn not work in this scenario, it is expected?

**Comment by nicolabovolato** [comment]
@RobertDS07 Same issue happening to me. Did you find a solution?

**Comment by RobertDS07** [comment]
@nicolabovolato Yep, I does a mock in the function that I use in test, like that: `createMock<PrismaService>({ plan: { findMany: jest.fn() } })`

**Comment by jacksonblankenship** [comment]
I'm having this problem, too. It's weird that `createMock` isn't handling those query functions. I did notice that it mutated _some_ subproperties, such as `prisma.$connect` but nothing for the entities.

**Comment by MylesWardell** [comment]
Why was this issue closed was it unresolved? I am also experiencing this issue
