### ISSUE TITLE
Error - AmqpConnection is undefined

### ISSUE THREAD

**Issue by verti4cal** [golevelup/nestjs#430]
After the latest Update (2.3.0), i get an error using the AmqpConnection.
The injected AmqpConnection is undefined.
It only happens, when the RabbitMQModule gets imported in a submodule and not the main "AppModule".

I forked the repo and edited the integration-tests to match these circumstances.

https://github.com/verti4cal/nestjs

**Comment by verti4cal** [comment]
I got the error.
But I have to write some tests for this use-case.

Btw. I'm adding tests for the NamedConnectionModule aswell.
The  module got imported in the integration-test module, but there are no test cases covering it.

**Comment by verti4cal** [comment]
i fixed the issue and added tests for the named connections.

Doing so, i found another bug, wich should be discussed:
currently the configuration.e2e-spec.ts suit fails, because the connection is reused.
therefore the amqp.connect function is only called the first time.

it's really problematic, because the configs of these connections differ.

**Comment by yinchuandong** [comment]
Hi @verti4cal , thanks for the update! I also met this issue. I also found it works in the submodule if there is another Rabbitmq connection. Will keep an eye on this issue and looking forward to seeing the updates.

![image](https://user-images.githubusercontent.com/3993196/165445424-141bb42b-f637-4e25-8c17-ccb29cad419a.png)

**Comment by verti4cal** [comment]
@underfisk @WonderPanda 
I cant think of a really good check for changed configuration on the named connections.


Problem is:
Connection A with name 'test' is created with config A
Connection B with the same name 'test' should be created, but with config B.
->
the connection-manager returns the already created connection A without any info or error.

The user would think, the connection with config B is created and returned, but he gets a connection with config A.

**Comment by underfisk** [comment]
@verti4cal It does make sense what you're saying, would you be up to creating a PR to address this issue?

**Comment by WonderPanda** [comment]
@verti4cal I took a glance at the work you've got in your fork and it looks promising. Did you want to open up a pull request against this repo and then we can go over any additional issues that might be left?

**Comment by verti4cal** [comment]
I cant get it running without major changes to the whole package and at this point i'm out of knowlege of the project.

**Comment by underfisk** [comment]
Feel free to propose in a PR your changes, we'll evaluate

**Comment by gallak87** [comment]
This also happened to me, had to pin ~2.2.0 to get around it. Looking forward to any updates

**Comment by all2pie** [comment]
Getting same error in `2.3.0`
