### ISSUE TITLE
Publishing to queue bound to exchange

### ISSUE THREAD

**Issue by mrmodise** [golevelup/nestjs#433]
Hi,

I wanted to know whether it's possible to publish messages to a queue instead of an exchange. Okay that part is answered cause I can do so via the routing key. However, I wanted to know how do I programmatically bind a queue to an exchange via the routing key to ensure when I push content to the exchange it gets routed to the linked queue

Thanks,

**Comment by underfisk** [comment]
You will always need a default exchange and i do advocate to do so

**Comment by mrmodise** [comment]
@underfisk aligned to that too however I would like my data to sit in the queue instead of exchange to allow me to have multiple queues linked to a single exchange hence my question above. I notice I cant just create the queue like i can with the exchange similar to how [amqp-connection-manager](https://github.com/jwalton/node-amqp-connection-manager#basics) does it. I can create an exchange link it to a queue at runtime

**Comment by underfisk** [comment]
@mrmodise Can you give me a practical example (e.g: code snippet) using the amq connection manager so that i can see what you're thinking of.
You can customize your queue and the way your consumers work but if you want something to sit on top of a queue then there are better alternatives (and simpler) than using rmq, doesn't Redis/Bull serve your purpose? I don't use that often RMQ nowadays but if this is something we don't expose form the connection manager and we can do, then I'll be glad to implement

**Comment by WonderPanda** [comment]
@mrmodise The library already supports multiple queues bound to the same exchange. Just use the same routing key and they'll all receive a copy whenever a new message gets published.

The binding of queue to exchange is taken for you automatically when you use the decorators from the library.

**Comment by mrmodise** [comment]
> @mrmodise Can you give me a practical example (e.g: code snippet) using the amq connection manager so that i can see what you're thinking of. You can customize your queue and the way your consumers work but if you want something to sit on top of a queue then there are better alternatives (and simpler) than using rmq, doesn't Redis/Bull serve your purpose? I don't use that often RMQ nowadays but if this is something we don't expose form the connection manager and we can do, then I'll be glad to implement

Thanks. In the example below from amqp-connection-manager or amqplib if I assert a queue that doesn't exist it will be created automatically:

```ts
var channelWrapper = connection.createChannel({
  json: true,
  setup: function (channel) {
    // this line creates a queue if it doesn't exist
    return channel.assertQueue('rxQueueName', { durable: true });
  },
});
```

However, with this package if i specify the exchange and routing key the queue is not automatically created meaning i have to create it manually and bind it to the exchange in order for content to be routed correctly:

```ts
RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: RABBITMQ_OPTIONS.exchangeName,
          type: RABBITMQ_OPTIONS.exchangeType,
        },
      ],
      uri: process.env.AMQP_BASE_URL,
      connectionInitOptions: { wait: false },
    }),
```

It would be nice to get the queue automatically created and linked to the exchange when the above is specified

**Comment by mrmodise** [comment]
> @mrmodise The library already supports multiple queues bound to the same exchange. Just use the same routing key and they'll all receive a copy whenever a new message gets published.
> 
> The binding of queue to exchange is taken for you automatically when you use the decorators from the library.

Thanks but my desired use case is for the library to also create the queue in addition to the exchange

**Comment by mrmodise** [comment]
To illustrate the idea and as a workaround I am doing the following to create queue and bind it to the exchange:


```ts
@Injectable()
export class LoggingService {
  constructor(private readonly amqpConnection: AmqpConnection) {}

  createQueue() {
    const conn = this.amqpConnection.managedConnection;
    if (conn.isConnected()) {
      conn.createChannel({
        name: RABBITMQ_OPTIONS.exchangeName,
        setup: (channel: Channel) =>
          Promise.all([
            channel.assertExchange(
              RABBITMQ_OPTIONS.exchangeName,
              RABBITMQ_OPTIONS.exchangeType,
              {
                durable: true,
              },
            ),
            channel.assertQueue(RABBITMQ_OPTIONS.queueName, { durable: true }),
            channel.bindQueue(
              RABBITMQ_OPTIONS.queueName,
              RABBITMQ_OPTIONS.exchangeName,
              RABBITMQ_OPTIONS.routingKey,
            ),
          ]),
      });
    }
  }
```

The only caveat being that my binding takes place when I publish instead of when the connection is established at runtime

**Comment by WonderPanda** [comment]
@mrmodise Is my understanding correct that you are not using any of the decorators from the library and that you are manually setting up queue listeners? Is there a reason that using `@RabbitSubscribe` or `@RabbitRPC` doesn't fit your use case?

**Comment by mrmodise** [comment]
> @mrmodise Is my understanding correct that you are not using any of the decorators from the library and that you are manually setting up queue listeners? Is there a reason that using `@RabbitSubscribe` or `@RabbitRPC` doesn't fit your use case?

Thanks I didn't find documentation on the decorator so I interpreted it as meaning am setting up a consumer/subscriber instead of a a publisher which is my desired use case

**Comment by WonderPanda** [comment]
@mrmodise I am still a bit confused by your responses. It is not clear to me so far what you're trying to accomplish.

In your examples, who/what will be consuming the messages posted to this queue? Is it a completely different application that is not using NestJS?

If you want to just pre-create some queues during application startup you could hook into the [NestJS lifecycle events](https://docs.nestjs.com/fundamentals/lifecycle-events) and inject the `AmqpConnection` to ensure that certain queues do exist

**Comment by mrmodise** [comment]
@mrmodise I am still a bit confused by your responses. It is not clear to me so far what you're trying to accomplish.

In your examples, who/what will be consuming the messages posted to this queue? Is it a completely different application that is not using NestJS?

> Correct its a different application the NestJs one is only responsible for publishing and not consuming

If you want to just pre-create some queues during application startup you could hook into the [NestJS lifecycle events](https://docs.nestjs.com/fundamentals/lifecycle-events) and inject the AmqpConnection to ensure that certain queues do exist
> Thanks I was hoping the library would do this for me hence the questions above

**Comment by WonderPanda** [comment]
At this point the library is mainly focused on using NestJS as message consumers hence the automatic queue binding for `RabbitSubscribe` and `RabbitRPC`.

It's pretty straightforward to set up queue binding using the NestJS lifecycle so I don't think we will plan to add further library integration unless there's significantly more interest from the community for this feature. 

Alternatively, I would suggest that the application that is actually doing the consuming is the one that sets up its own queue bindings instead of expecting the publisher to setup bindings for the consumer
