### ISSUE TITLE
Error: Nest can't resolve dependencies of the DiscoveryService

### ISSUE THREAD

**Issue by sk52** [golevelup/nestjs#437]
Using the discovery module with NestJS v8.2.3 gives the following error: 
```
Error: Nest can't resolve dependencies of the DiscoveryService (?, MetadataScanner). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.
```

Adding `ModulesContainer` as a provider in `discovery.module.ts` fixes this error.

**Comment by WonderPanda** [comment]
@sk52 Can you share a repo that reproduces this problem in isolation? I've been chatting with someone on Discord who is having a similar problem, but I just spun up a brand new app and I'm not seeing the same problem.

Can you please also provide information about what package manager you're using and also how you've structured your application directory? Are you using any monorepo technologies?

**Comment by sk52** [comment]
Unfortunately haven't been able to reproduce this in a new app either. 

We're using the discovery module within a custom nest module, which is in turn installed as a dependency in a nest application. Not using any monorepo technologies.

**Comment by underfisk** [comment]
@sk52 Please make sure you only have a single version of nestjs v8 installed otherwise this can occur
