### ISSUE TITLE
Provider with null instance crashes module

### ISSUE THREAD

**Issue by jasperblues** [golevelup/nestjs#44]
If (inadvertently) a provider has a null instance, the module will crash. 

This can be fixed by filtering, before passing for processing: 

```typescript
const providers = (await this.providers(providerFilter)).filter(it => it.instance != undefined);
```

Example scenario: 

I had a config module (`@Inject('config.SENDGRID_API_KEY')`) that returned null for a given value. Not intended as the config is required, however if the config was optional, this would be a show stopper.

**Comment by Ermodo** [comment]
I have a similar issue with transient provider. In my case, I defined a provider with 'useFactory' and 'Scope.TRANSIENT'. In this case, the instance is null as the provider is not singleton. Nestjs is not able to start and crashes silently with:

```
TypeError: Cannot read property 'constructor' of undefined
  File "node_modules\@nestjs-plus\discovery\src\discovery.service.ts", line 48, col 24, in component
  File "node_modules\@nestjs-plus\discovery\src\discovery.service.ts", line 90, col 57, in filter.x
  ?, in Array.filter
  File "node_modules\@nestjs-plus\discovery\src\discovery.service.ts", line 90, col 45, in DiscoveryService.providers
  File "internal/process/next_tick.js", line 68, col 7, in process._tickCallback
```
Expected is to ignore providers with undefined or null instances.

I am using nestjs 6.6.7 and nestjs-plus 2.0.1.

**Comment by WonderPanda** [comment]
@jasperblues @Ermodo Thanks for providing this info guys. I'll try and push out some fixes tonight for both of these scenarios.

**Comment by WonderPanda** [comment]
Hey @jasperblues @Ermodo Thanks for your patience on this one. I've had a ton of stuff going on with my day job and some big plans with regards to NestJS and Open Source that I'm hoping to reveal in the near future but should have got a fix out for this sooner

This should be fixed now and is available with the following new package versions:
 - @nestjs-plus/discovery@2.0.2
 - @nestjs-plus/rabbitmq@1.4.1

Please feel free to open up other issues if you come across anything and I'll try and address them in a more timely fashion
