### ISSUE TITLE
 the Module containing Symbol(STRIPE_CLIENT_TOKEN)

### ISSUE THREAD

**Issue by MuttakinHasib** [golevelup/nestjs#444]
`Error: Nest can't resolve dependencies of the StripeService (?). Please make sure that the argument Symbol(STRIPE_CLIENT_TOKEN) at index [0] is available in the SharedModule context.`

**Comment by MuttakinHasib** [comment]
@WonderPanda can you plz help me?

**Comment by WonderPanda** [comment]
It is not possible to help you given the information you have provided. Feel free to reopen this if you can provide sufficient detail. At the very least please include list of package versions and code snippets for your various modules so we can see if there's something wrong with your configuration.

It would be preferred if you provide a minimum reproduction demonstrating the issue

**Comment by KonstntinM** [comment]
Hey, I have seen the same error, when trying to test a provider that is importing the stripeClient using jest. I have created a minimum code reproduction repo here: https://github.com/KonstntinM/minrep-golevelup-nestjs-444 .

**Comment by KonstntinM** [comment]
@WonderPanda Do you think you could take a look at this?

**Comment by KonstntinM** [comment]
Okay, so I found a temporary workaround. It seems like the @InjectStripeClient decorator is dependent on the constant STRIPE_CLIENT_TOKEN. When importing a service that uses the @InjectStripeClient into a testing module, you need to pass not only a StripeModule mock but also a STRIPE_CLIENT_TOKEN mock like this

```ts
import { StripeModule, STRIPE_CLIENT_TOKEN } from '@golevelup/nestjs-stripe';

const app = await Test.createTestingModule({
  providers: [
    AppService,
    { provide: StripeModule, useValue: {} },
    { provide: STRIPE_CLIENT_TOKEN, useValue: {} }
  ],
}).compile();
```
