### ISSUE TITLE
nestjs-modules: forward config values

### ISSUE THREAD

**Issue by nidomiro** [golevelup/nestjs#449]
I'm currently exploring the use of this package (nestjs-modules) to implement Hexagonal architecture in my app.
So far everything works as expected and I can inject adapter implementations into the core.

What I'm struggling with, is to pass the config on to imported (child-) modules.

My use-case:
`CoreModule` imports and exports `CoreUsersModule`.
Only the `CoreModule` is imported in my App and therefore receives all the config.
Now I need to pass on the config to `CoreUsersModule` in order to be able to use the config.

How can I achieve this?
My first tries resulted in an chicken-egg problem.

**Comment by MrMaz** [comment]
Have you tried the `externallyConfigured()` pattern yet? This is how we solved it for our plugin architecture.

You have to be careful though. It is very easy to end up with a tightly coupled architecture and/or circular dependencies if your lib stack is not a perfect tree. We eventually gave up on hierarchy and went totally flat, except for key dependencies that do not import any other plugin modules.

For instance if the User needs to import Auth to get services for hashing passwords, and Auth needs to import User services for looking up credentials, it gets extremely complex.

**Comment by nidomiro** [comment]
Yes, I tried to use `externallyConfigured` but it resulted in `TS2506: 'CoreModule' is referenced directly or indirectly in its own base expression.`.

The approach I tried:

```ts
/*
	CoreUsersModule
 */
export const CORE_USERS_MODULE_CONFIG_INJECT_TOKEN = Symbol('CORE_USERS_MODULE_CONFIG_INJECT_TOKEN')
export interface CoreUsersModuleConfig {
		myProp: string
}

@Module({})
export class CoreUsersModule extends createConfigurableDynamicRootModule<CoreUsersModule, CoreUsersModuleConfig>(
	CORE_USERS_MODULE_CONFIG_INJECT_TOKEN,
	{

	},
) {}

/*
	CoreModule
 */
export const CORE_MODULE_CONFIG_INJECT_TOKEN = Symbol('CORE_MODULE_CONFIG_INJECT_TOKEN')
export interface CoreModuleConfig {
	myProp: string
}

@Module({})
export class CoreModule extends createConfigurableDynamicRootModule<CoreModule, CoreModuleConfig>(
	CORE_MODULE_CONFIG_INJECT_TOKEN,
	{
		imports: [CoreUsersModule.forRootAsync(CoreUsersModule, {
			imports: [CoreModule.externallyConfigured(CoreModule, 0)],
			inject: [CORE_MODULE_CONFIG_INJECT_TOKEN],
			useFactory: (coreModuleConfig: CoreModuleConfig) => coreModuleConfig
		})],
		exports: [CoreUsersModule]
	},
) {}
```

In my specific case I also flattened the hierarchy to not use child-modules but one single CoreModule instead.
Nevertheless I want to know how to achieve the forwarding of config, since I'm sure I will encounter this problem in the future again.

**Comment by MrMaz** [comment]
Yes, you can't reference a module inside its own definition like you already see (chicken/egg).

The solution is to create a CoreConfigModule which exports the config, but you can also just use the ConfigModule from Nest to achieve the same thing using `ConfigModule.forFeature()`

You are still creating a tree structure, instead of being composable... which is fine if is just one app, but it will be impossible to use each module independently, the dependencies will be too tightly coupled (monolithic).

**Comment by nidomiro** [comment]
As it's not a problem right now anymore I would close the issue and revisit the topic if I encounter it again in the future.
Thank you for your thoughts on it :)
