### ISSUE TITLE
API breaking change introduced in version 2.4.0 

### ISSUE THREAD

**Issue by santriseus** [golevelup/nestjs#452]
Hi you changed one of the public async method to sync. It is a braking change, now all code assumed you are returning Promise should be rewritten. According to semver you should update major version after such braking change.
https://github.com/golevelup/nestjs/commit/45f68f68d2dbc01a82e01d2f9e3dedf3242be854#diff-b531b20a58e14f0da9a03b8ea64b6e140535f684c585825fa664d63e98b2806aL434

**Comment by WonderPanda** [comment]
Apologies, we didn't catch that this change would be breaking for consumers. It definitely should have been a major version bump according to semver. I'd recommend you stick to the previous version for now and the next time we publish I'll bump it up to 3.x
