### ISSUE TITLE
notification to publisher once message is dropped ?

### ISSUE THREAD

**Issue by koodpzok** [golevelup/nestjs#453]
Hi, im using 'x-message-ttl': 60000 for the queue and Publising Messages (Fire and Forget). When the message is expired, it is just dropped silently. Is there any way to place a hook on this? or in other words, i want the rabbitmq to notify the publisher that the message was dropped.

**Comment by underfisk** [comment]
@koodpzok This doesn't seem related to `@golevelup` packages, you're question is more likely related to the underlying `amqlib` that we use or rabbitMQ itself

If you want to build some sort of listener for messages that were dropped you'll have to dive into the `amqlib` or build something outside
