### ISSUE TITLE
[Stripe] Execution context in webhook handlers incorrectly has 'http' type

### ISSUE THREAD

**Issue by sgarner** [golevelup/nestjs#454]
Firstly thanks for all your efforts with these modules, they're very helpful!

I have a global `APP_GUARD` configured in my NestJs application, which tries to fetch authorization information from headers on the HTTP request object. The guard was working perfectly until I added `@golevelup/nestjs-stripe` to my application.

The guard is now being triggered by Stripe webhook handlers. When this happens the NestJs execution context passed to the guard has type `http`, but the arguments array contains the Stripe webhook payload instead of the HTTP request and response that it should have. So when I do `context.switchToHttp().getRequest().headers.authorization` an error occurs because `headers` is undefined -- `getRequest()` is actually returning an object like `{ object: 'event', id: 'evt_XXX', api_version: '2020-08-27', etc }`.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/904004/173993556-703bc865-805d-4f61-a31f-e6b1b454eff0.png">

I could easily work around this if the context of webhook handlers had a different type (e.g. `stripe_webhook`), but because it claims to be an HTTP context the only option is to resort to inspecting the shape of the context arguments, which feels kind of dirty.

The NestJs `ExternalContextCreator.create()` method accepts a ninth(!) argument which is the context type:
https://github.com/nestjs/nest/blob/cbec376216831303d581bf23c85fa7ad0d08f43e/packages/core/helpers/external-context-creator.ts#L91-L108

In your call this argument is omitted, so it receives the default value of 'http'. I think if you simply adjusted this call to specify a custom context type it would make life better for apps that use NestJs guards, filters and interceptors. [The relevant code is here.](https://github.com/golevelup/nestjs/blob/351b6f0882b0b910786ea702f332be0e4c4135cd/packages/stripe/src/stripe.module.ts#L130-L134)

I also note that the `@golevelup/nestjs-rabbitmq` and `@golevelup/nestjs-hasura` modules have the same issue, which is related to #204. The solution that was adopted there looks like it wouldn't have been necessary if a different context type was set instead.

**Comment by WonderPanda** [comment]
Yeah this is a really good idea. We did actually end up changing the execution context name for RabbitMQ in addition to the original changes made in #204. Are you interested in contributing a fix for this?

**Comment by sgarner** [comment]
> Yeah this is a really good idea. We did actually end up changing the execution context name for RabbitMQ in addition to the original changes made in #204. Are you interested in contributing a fix for this?

I've made [a PR](https://github.com/golevelup/nestjs/pull/461). Thanks!
