### ISSUE TITLE
How to set up two GraphQL APIs 

### ISSUE THREAD

**Issue by singulart** [golevelup/nestjs#455]
Hello Team, 

In my project that uses GraphQL client code generator, I need to access **two** GraphQL APIs. `codegen.yml` schema has a possibility to set an array of URLs like this: 

```
schema: 
  - https://query.joystream.org/graphql # Pioneer 
  - https://orion.joystream.org/graphql # Atlas
``` 

However, when I mix the queries for these two APIs in the same codegen.yml file, they end up in the same `Sdk`. 

How do I make sure that queries that are supposed to be executed against the first URL are segregated from those that are related to the second API URL?

**Comment by singulart** [comment]
@underfisk It's not polite to close tickets with no comment :)

**Comment by underfisk** [comment]
@underfisk I forgot to gave context but this doesn't seem related to golevelup therefore i close, there's no action item possible
