### ISSUE TITLE
Display compiler error on missing attributes at `forRootAsync`

### ISSUE THREAD

**Issue by nidomiro** [golevelup/nestjs#456]
Currently the compiler does not enforce you to provide values at `forRootAsync`.
It is valid just to call `Module.forRootAsync(Module, {})` even, if there is a needed config.

In my opinion the compiler should complain about that and therefore reduce possible runtime-errors.

_Note:_ I will provide a PR to fix that.

**Comment by WonderPanda** [comment]
This is a good catch. I appreciate you willing to help out with a contribution!
