### ISSUE TITLE
How to reconnect rabbitmq when heartbeat timeout?

### ISSUE THREAD

**Issue by ganruip** [golevelup/nestjs#46]
How to reconnect rabbitmq when heartbeat timeout?
![image](https://user-images.githubusercontent.com/15976895/65586287-83d00200-dfb6-11e9-9562-b46dc9fba501.png)

**Comment by WonderPanda** [comment]
Hey @ganruip. Currently we provide access to the underlying AMQP connection and channel in our connection abstraction: https://github.com/WonderPanda/nestjs-plus/blob/master/packages/rabbitmq/src/amqp/connection.ts

This allows you to attach appropriate event handlers to the connection, such as the `close` event where you could put in logic to attempt to reconnect in the case of a heartbeat timeout. If I have some free time I will look at providing an easier way to do this through our library directly but no promises on a timeline right now.
