### ISSUE TITLE
[@golevelup/ts-jest] Problem auto mocking Logger depencendy

### ISSUE THREAD

**Issue by fer8a** [golevelup/nestjs#462]
First and foremost I wanted to thank you for this great package, it makes the mocking of dependencies so much easier, so kudos!

Now down to business.
I'm currently having an issue trying to mock a Logger dependency on my tests. The mock is not being generated and the real instance is passed along instead.
I'm not sure what the problem is since all the other dependencies are mocked just fine, except for the logger.

I use a custom logger in the form of
```typescript
// main.ts
import { Logger } from 'nestjs-pino';

app.useLogger(app.get(Logger));
```
Then inject it in my controller this way:
```typescript
// controller.ts
import { Logger } from '@nestjs/common';

constructor(private readonly logger: Logger) {
    this.logger = new Logger(Controller.name);
  }
```
In my tests, I do the following to initialize/mock dependencies 
```typescript
// spec.ts
import { Logger } from '@nestjs/common';
import { Controller } from './controller';

let controller: Controller;
let logger: Logger;

beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      controllers: [Controller],
    })
      .useMocker(() => createMock()) // this is how I auto-mock dependencies
      .compile();

   // fetch mock instances
    controller = moduleRef.get(Controller);
    logger = moduleRef.get(Logger);
  });
```

Then I proceed to use/spy on my mocks for the tests
```typescript
jest.spyOn(logger, 'log').mockImplementationOnce(() => Promise.resolve());
await controller.handler();
expect(logger.log).toHaveBeenCalledTimes(1); // this returned an error (called times = 0)
```
When I went to debug the test I found out that the logger itself wasn't being mocked (all the other dependencies are, as you can see in the ss below) and the real instance was being passed to the test instead.

![Screenshot from 2022-06-27 11-22-20](https://user-images.githubusercontent.com/3921419/175976882-05b95fc8-0664-4650-abd0-b04a1631ee6f.png)

Is this a bug? 
Do I need to do something different/extra for the Logger mock? 
Any hints would be highly appreciated.

_NOTE_
If I don't initialize the logger in the constructor `this.logger = new Logger(Controller.name)` the mock is generated properly.

**Comment by underfisk** [comment]
@fer8a You should head to the `nestjs-pino` repo and report this, it isn't related to golevelup therefore I'm going to close this issue
