### ISSUE TITLE
Messages not being handled

### ISSUE THREAD

**Issue by rstoermer** [golevelup/nestjs#469]
Just started out with this library and followed the documentation, but it seems that my messages are not being handled. I create the Messaging Service like so:

```
@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: 'tx-nextor',
          type: 'topic',
        },
      ],
      uri: RABBIT_URI,
      channels: {
        'channel-1': {
          prefetchCount: 15,
          default: true,
        },
      },
    }),
    MessagingModule,
  ],
  providers: [],
  controllers: [],
})
export class MessagingModule {}
```

Everything is connecting correctly and I can see the connection and channel in the RabbitMQ admin. After I created a subscriber:

```
@Injectable()
export class ResourceService {
  @RabbitSubscribe({
    exchange: 'tx-nextor',
    routingKey: 'resource.*',
    queue: 'resource-history-resource.*.updated',
  })
  public async updatedHandler(msg: {}, amqpMsg: ConsumeMessage) {
    console.log('Subscribe handler ran');
    console.log(JSON.stringify(msg));
    console.log(`Correlation id: ${amqpMsg.properties.correlationId}`);
    return 'test';
  }
}
```

This also connects:
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RoutesResolver] AppController {/}: +8ms
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RouterExplorer] Mapped {/, GET} route +3ms
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RoutesResolver] HistoryController {/history}: +1ms
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RouterExplorer] Mapped {/history/appointment, GET} route +1ms
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RouterExplorer] Mapped {/history/test, POST} route +1ms
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RabbitMQModule] Initializing RabbitMQ Handlers
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RabbitMQModule] Registering rabbitmq handlers from ResourceService
[resource-history] [Nest] 220  - 07/09/2022, 4:30:47 PM     LOG [RabbitMQModule] ResourceService.updatedHandler {subscribe} -> tx-nextor::resource.*::resource-history-resource.*.updated
[resource-history] [Nest] 220  - 07/09/2022, 4:30:48 PM     LOG [NestApplication] Nest application successfully started +11ms

But after I do this nothing is logged.
<img width="976" alt="image" src="https://user-images.githubusercontent.com/5518072/178114711-66aa9248-6cc2-4a13-8271-2d02623410d7.png">

Although the consumer is connected, all testmessages are staying on the queue:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/5518072/178114729-5af99528-3145-4ce0-bc14-d91b963012df.png">

**Comment by patrickacioli** [comment]
Same here.

**Comment by patrickacioli** [comment]
Maybe after nest update to V9?

**Comment by patrickacioli** [comment]
Hum... I just delete the exchanges and starting again. begin works.

**Comment by underfisk** [comment]
@rstoermer It isn't related to this library, when you're creating messages outside the nestjs context and do not follow any message header/pattern it is possible that the library routers would not h itandle.
This isn't actually an issue, please create a "publisher" nestjs app and try to publish messages to your server, if this persists between two nestjs apps you'll be able to give us a better repro

**Comment by manuschillerdev** [comment]
i'm also experiencing this.
When I create messages via the management UI, the messages are not being picked up.

**Comment by manuschillerdev** [comment]
this was probably a big rookie mistake. 

I sent the string `test` as message via the rabbitmq management ui.
Before, I did not have an error handler in my code.

```diff
import { RabbitSubscribe } from '@golevelup/nestjs-rabbitmq';
import { Injectable } from '@nestjs/common';

@Injectable()
export class MessagingService {
  @RabbitSubscribe({
    exchange: 'exchange',
    routingKey: 'subscribe-route',
    queue: 'subscribe-queue',
+   errorHandler: (channel, msg, error) =>
+    console.error('RabbitSubscribe error', {
+       channel,
+       msg,
+       error,
+     }),
  })
  public async pubSubHandler(msg: {}) {
    console.log(`Received message in Service: ${JSON.stringify(msg)}`);
  }
}

```

After adding an error handler to my service method, the error was clear: 

```
  error: SyntaxError: Unexpected token e in JSON at position 1
```

As soon as I sent a valid JSON-Payload as body, the messages are being handled correctly.
```bash
Received message in Service: {"hello":"world"}
```

@underfisk maybe this would be a good addition for the readme that payloads are expected to be valid JSON, and that you can handle raw string payloads by passing  `allowNonJsonMessages: true,` ?

**Comment by underfisk** [comment]
@manuschillerdev I haven't explored that yet but feel free to create a PR and propose those changes
