### ISSUE TITLE
[@golevelup/nestjs-rabbitmq] Cannot read properties of undefined (reading 'isConnected'

### ISSUE THREAD

**Issue by kejvi-doko** [golevelup/nestjs#473]
I have a NestJS Application using `@golevelup/nestjs-rabbitmq` version `2.2.0` and when publishing to the rabbit we get this error and we have tried different configuration to configure directly on the AppModule but still doesn't work.

```
[Nest] 13484  - 07/22/2022, 10:40:42 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'isConnected')
TypeError: Cannot read properties of undefined (reading 'isConnected')
    at AmqpConnection.publish (/Users/crs/dev/xxxx/xxxx-marketing-service/node_modules/@golevelup/nestjs-rabbitmq/src/amqp/connection.ts:423:33)
    at MailerService.sendToReferralInvitationMail (/Users/crs/dev/xxx/xxx-marketing-service/src/mailer/mailer.service.ts:33:35)
    at /Users/crs/dev/xxx/xxx-marketing-service/src/referrals/referrals.service.ts:70:36
    at Array.map (<anonymous>)
    at ReferralsService.send (/Users/crs/dev/xxx/xxx-marketing-service/src/referrals/referrals.service.ts:68:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/crs/dev/xxx/xxx-marketing-service/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at Layer.<anonymous> (/Users/crs/dev/xxx/xxx-marketing-service/node_modules/@nestjs/core/router/router-proxy.js:9:17)

```
Rabbit MQ Configuration 

```
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';
import { Global, Module } from '@nestjs/common';

@Global()
@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      uri: `${process.env.RABBITMQ_PROTOCOL}://${process.env.RABBIT_USER}:${process.env.RABBIT_PASSWORD}@${process.env.RABBITMQ_HOST}:${process.env.RABBITMQ_PORT}`,
      connectionInitOptions: { wait: false },
    }),
    RabbitModule,
  ],
  providers: [],
  exports: [RabbitMQModule],
})
export class RabbitModule {}

```
App Module Configuration

```
import { AppService } from './app.service';
import { RabbitModule } from "./utils/RabbitMQ/RabbitModule";

@Module({
  imports: [
    RabbitModule,
    MailerModule,
  ],
  providers: [AppService],
})
export class AppModule {}

```

**Comment by Jendorski** [comment]
Have you resolved this, I experiencing something similar

`Cannot read properties of undefined (reading 'heartbeat')`

**Comment by kejvi-doko** [comment]
yes is resolved, just make sure **NOT** to provide the amqp connector on the service that you are using, so the module should look this 

```
import { Module } from '@nestjs/common';
import { MailerService } from '../mailer/mailer.service';

@Module({
  providers: [MailerService],
  exports: [MailerService],
})
export class MailerModule {}

```

**Comment by Jendorski** [comment]
> yes is resolved, just make sure **NOT** to provide the amqp connector on the service that you are using, so the module should look this
> 
> ```
> import { Module } from '@nestjs/common';
> import { MailerService } from '../mailer/mailer.service';
> 
> @Module({
>   providers: [MailerService],
>   exports: [MailerService],
> })
> export class MailerModule {}
> ```

So how do you then publish. If I am to not inject the `AmqpConnection` into the service, I cannot extend the `AmqpConnection` into another class, then manually inject that class, how do I get to publish.

I did what you also did, I added the `AmqpConnection` to the constructor of the controller for the particular module, then added the Controller to the Module itself. I also added the Service class (which doesnt have the `AmqpConnection` btw) as provider and exports in the Module.

Still getting this error

`[Nest] 24776  - 07/22/2022, 5:42:54 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RegistrationController (RegistrationService, ?). Please make sure that the argument AmqpConnection at index [1] is available in the RegistrationModule context.`

The docs just says to call `AmqpConnection#publish` :(

**Comment by WonderPanda** [comment]
@Jendorski Can you open up a new issue with specific information about your setup so that we can try to diagnose. Preferably if you have a reproduction you can share of the problem but at a mininum we need to see your module configurations
