### ISSUE TITLE
Cannot read properties of undefined (reading 'heartbeat')

### ISSUE THREAD

**Issue by Jendorski** [golevelup/nestjs#474]
I have an issue with calling the `AmqpConnection` in my Controller.

`RegistrationController`:

`//All imports observed`
`
@Controller()
export class RegistrationController {
    constructor(private readonly regService: RegistrationService,
        private amqpConnection: AmqpConnection) { }
    @Post('/user/register')
    async registerUser(@Req() req, @Body() body: RegistrationCommand, @Res() res) {
        console.log('body reg controller, ', body)
        const registered = await this.regService.create(body)
        if(registered instanceof ErrorModel) return failed(res, registered.errorMessage, registered.errorMeta, registered.statusCode)
        this.amqpConnection.publish('user-exchange', 'email-welcome-verification-routing-key', { fullName: registered.fullName, email: registered.email, userID: registered.userID } );
        return success(res, 'successfully registered', registered, HttpStatus.CREATED)
    }
    `
    `RegistrationModule`:
    `@Global()
@Module({
  imports: [ DatabaseModule, CqrsModule ],
  controllers: [RegistrationController, ],
  providers: [RegistrationService, RegistrationHandler, UtilsService,   ],
  exports: [ RegistrationService, RegistrationController ]
})
`
`export class RegistrationModule implements NestModule { 
               configure(consumer: MiddlewareConsumer) {
        consumer
        .apply()
        .forRoutes(
            {path: '/user/register', method: RequestMethod.POST}
        )
    }
}
`

`Error:`
`
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [NestFactory] Starting Nest application...
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [AmqpConnection] Trying to connect to RabbitMQ broker (default)
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [RabbitMQModule] Successfully connected to RabbitMQ
[Nest] 25231  - 07/22/2022, 5:52:40 PM   ERROR [AmqpConnection] Disconnected from RabbitMQ broker (default)
TypeError: Cannot read properties of undefined (reading 'heartbeat')
    at /Documents/apiCode/node_modules/@golevelup/nestjs-rabbitmq/node_modules/amqp-connection-manager/dist/cjs/AmqpConnectionManager.js:231:42
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [InstanceLoader] UtilsModule dependencies initialized +1ms
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [InstanceLoader] ResetPasswordModule dependencies initialized +0ms
[Nest] 25231  - 07/22/2022, 5:52:40 PM     LOG [InstanceLoader] ForgotPasswordModule dependencies initialized +1ms
[Nest] 25231  - 07/22/2022, 5:52:40 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RegistrationController (RegistrationService, ?). Please make sure that the argument AmqpConnection at index [1] is available in the RegistrationModule context.
Potential solutions:
- If AmqpConnection is a provider, is it part of the current RegistrationModule?
- If AmqpConnection is exported from a separate @Module, is that module imported within RegistrationModule?
  @Module({
    imports: [ /* the Module containing AmqpConnection */ ]
  })

`
  
Thats two errors. So, first it connects and then disconnects, then pumps out the second error.

In the `RegistrationService`, I am not calling `AmqpConnection`, I tried it, I kept getting:

`ERROR [ExceptionHandler] Nest can't resolve dependencies of the RegistrationService (ConfigService, ?). Please make sure that the argument AmqpConnection at index [1] is available in the RegistrationModule context.`

I have tried to do something like:

`@Injectable()
export class RegWrapper extends AmqpConnection {

}`

It didnt work, In the corresponding call of the `RegWrapper`, in the `RegistrationController` and the `RegistrationService`, I keep getting `this.amqpConnection.publish is not a function`

I have also tried to manually inject the  `AmqpConnection` same error as `this.amqpConnection.publish is not a function`

What am I doing wrong?

**Comment by Jendorski** [comment]
`@Global()
@Module({
    imports: [
      RabbitMQModule.forRoot(RabbitMQModule, {
        exchanges: [
            {
              name: 'email-welcome-verification-exchange',
              type: 'direct',
              options: {
                durable: true,
              }
            },
          ],
          uri: process.env.RABBIT_MQ_CONN_URL,
          connectionInitOptions: { wait: false, timeout: 60 },
          enableControllerDiscovery: true,
          channels: {
            'email-welcome-verification-channel1': {
              prefetchCount: 1,
              default: false,
            },
            'channel-2': {
              prefetchCount: 1,
              default: true,
            },
          },
    }),
    ],
    providers: [],
    exports: [RabbitMQModule],  // this line is important
  })
  export class MainRabbitMQModule {
}`

This is how I got it to work.

Though I have now this error: 
`
[Nest] 31365  - 07/23/2022, 4:58:41 AM   ERROR [AmqpConnection] Disconnected from RabbitMQ broker (default)
TypeError: Cannot read properties of undefined (reading 'heartbeat')`

**Comment by FredIngwersen** [comment]
@Jendorski  did you manage to solve: "Disconnected from RabbitMQ broker (default)"?

**Comment by Jendorski** [comment]
Yea, the main reason for opening up the issue log is resolved.

Though I now have this error:

Cannot read properties of undefined reading ('heartbeat')

**Comment by Hareloo** [comment]
I am getting the same error
