### ISSUE TITLE
Custom logger is not used when using nest js 9

### ISSUE THREAD

**Issue by shakedo** [golevelup/nestjs#480]
I'm using nest js 9.0.0 and when I'm using custom logger, rabbitmq client logs are written to default logger and not to my custom logger:

[Nest] 26531  - 07/27/2022, 9:36:17 AM     LOG [AmqpConnection] Trying to connect to RabbitMQ broker (default)
[Nest] 26531  - 07/27/2022, 9:36:17 AM     LOG [RabbitMQModule] Successfully connected to RabbitMQ
[Nest] 26531  - 07/27/2022, 9:36:17 AM     LOG [RabbitMQModule] Initializing RabbitMQ Handlers
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"NestFactory","msg":"Starting Nest application..."}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"InstanceLoader","msg":"DiscoveryModule dependencies initialized"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"InstanceLoader","msg":"AppModule dependencies initialized"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"InstanceLoader","msg":"LoggerModule dependencies initialized"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"InstanceLoader","msg":"RabbitMQModule dependencies initialized"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"RoutesResolver","msg":"AppController {/}:"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"RouterExplorer","msg":"Mapped {/, GET} route"}
{"level":30,"time":1658903777435,"pid":26531,"hostname":"host","context":"NestApplication","msg":"Nest application successfully started"}
[Nest] 26531  - 07/27/2022, 9:36:17 AM     LOG [AmqpConnection] Successfully connected to RabbitMQ broker (default)
[Nest] 26531  - 07/27/2022, 9:36:17 AM     LOG [AmqpConnection] Successfully connected a RabbitMQ channel "AmqpConnection"

In main js, default logger is replaced:
  const app = await NestFactory.create(AppModule, { bufferLogs: true });
  app.useLogger(app.get(Logger));
  await app.listen(3000);

Issue is reproduced here: https://github.com/shakedo/nest9-example

**Comment by alko89** [comment]
Probably related that log level is being ignored after updating to nest 9. Its always set to verbose.

Example console log with logger set to false `const app = await NestFactory.create(AppModule, { logger: false });`

Nest 9:

```
[9:38:33 AM] Starting compilation in watch mode...

[9:38:36 AM] Found 0 errors. Watching for file changes.

Debugger listening on ws://127.0.0.1:9229/2a74f457-143b-4f61-815e-f85c22177b6e
For help, see: https://nodejs.org/en/docs/inspector
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [AmqpConnection] Trying to connect to RabbitMQ broker (default)
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [RabbitMQModule] Successfully connected to RabbitMQ
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [RabbitMQModule] Initializing RabbitMQ Handlers
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [RabbitMQModule] Registering rabbitmq handlers from UsageService
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [RabbitMQModule] UsageService.create {subscribe} -> usage::usage-create::usage-queue
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [AmqpConnection] Successfully connected to RabbitMQ broker (default)
[Nest] 833993  - 07/27/2022, 9:38:36 AM     LOG [AmqpConnection] Successfully connected a RabbitMQ channel "AmqpConnection"
^C[Nest] 833993  - 07/27/2022, 9:40:54 AM VERBOSE [RabbitMQModule] Closing AMQP Connections

npm run start:debug  11,46s user 4,08s system 11% cpu 2:21,23 total
```

Nest 8:

```
[9:44:08 AM] Starting compilation in watch mode...

[9:44:11 AM] Found 0 errors. Watching for file changes.

Debugger listening on ws://127.0.0.1:9229/dd13bd73-cbaa-4e57-91c6-10efb9ed72a3
For help, see: https://nodejs.org/en/docs/inspector
^C
npm run start:debug  7,27s user 0,46s system 88% cpu 8,769 total
```

**Comment by underfisk** [comment]
@alko89 I have merged your PR, LGTM but its pending a new version release @WonderPanda

**Comment by zogot** [comment]
--- Moved comment into seperate issue for clearer conversation: https://github.com/golevelup/nestjs/issues/487

**Comment by alko89** [comment]
For me the issue was that the rabbitmq module had nest 8 as peer dependency (you can check this by having a look at the @golevelup/rabbitmq node_modules folder).

So both nest versions were installed. After I updated my library, the nest dependency was gone and the one installed in node_modules was used.

That solved the issue for me because the proper nest instance was used. Did you update golevelup modules you use to latest vesions?

**Comment by zogot** [comment]
Hmm, you might be on to something, after doing a fresh install, removing node_modules and package-lock.json, I'll look a bit. I also made a new issue to group conversation a bit better @alko89
