### ISSUE TITLE
upgrade to nestjs v9 in golevelup/nestjs-modules forces upgrade to use golevelup/nestjs-rabbitmq

### ISSUE THREAD

**Issue by schealex** [golevelup/nestjs#484]
Hi,

because the rabbitmq modules has those dependencies:

"dependencies": {
    https://github.com/golevelup/nestjs: "^1.4.4",
    https://github.com/golevelup/nestjs: "^3.0.0",
    https://github.com/golevelup/nestjs: "^0.6.0",
    https://github.com/jwalton/node-amqp-connection-manager: "^3.0.0",
    https://github.com/amqp-node/amqplib: "^0.8.0",
    https://github.com/uuidjs/uuid: "^3.3.2"
  },

the recent update of golevelup/modules v0.6.1 to nestjs v9 causes the project to install v9 nestjs common which leads to us being unable to resolve our dependencies in our current projects:

TS2322: Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.   Type 'import("C:/dev/gitlab/nws-vc-s-core/node_modules/@golevelup/nestjs-rabbitmq/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule' is not assignable to type 'import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule'.     Types of property 'imports' are incompatible.       Type '(import("C:/dev/gitlab/nws-vc-s-core/node_modules/@golevelup/nestjs-rabbitmq/node_modules/@nestjs/common/interfaces/type.interface").Type<any> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@golevelup/nestjs-rabbitmq/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule | Promis...' is not assignable to type '(import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfaces/type.interface").Type<any> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule | Promise<...> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfa...'.         Type 'import("C:/dev/gitlab/nws-vc-s-core/node_modules/@golevelup/nestjs-rabbitmq/node_modules/@nestjs/common/interfaces/type.interface").Type<any> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@golevelup/nestjs-rabbitmq/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule | Promise...' is not assignable to type 'import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfaces/type.interface").Type<any> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule | Promise<...> | import("C:/dev/gitlab/nws-vc-s-core/node_modules/@nestjs/common/interfac...'.           Type 'Promise<DynamicModule>' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.

I strongly belive the upgrade to nestjs v9 in modules should have caused a major bump not a patch!

Regards
Alex

**Comment by schealex** [comment]
@underfisk has that been fixed, if so which version can we use?

**Comment by underfisk** [comment]
@schealex Hi there, I can't guarantee that this exact problem has been fixed but a long time ago we did upgrade the dependencies therefore if you're using v9 you'll be able to use it without any type of issue (try to use the latest version)
