### ISSUE TITLE
rabbitmq: how can it create a binding on created exchange

### ISSUE THREAD

**Issue by jn-novasol** [golevelup/nestjs#485]
Hello,
So this seem to create a new exchange called "some_exchange_here".
```
...
		RabbitMQModule.forRoot(RabbitMQModule, {
			exchanges: [
				{
					name: 'some_exchange_here',
					type: 'topic',
				},
			],
...
```
But! How can I also create a new route key that bind to a new queue?

For instance, if I now go to RabbitMQ UI and Edit the some_exchange_here, then I can create and bind a new route key to a new queue.. And then I can do this in my code:

```
...
		this.amqpConnection.publish('some_exchange_here', 'change.new', {
			msg: 'hello world',
		});
...
```
But I suppose I'm doing something wrong: it should not be necessary for me to go to RabbitMQ and do anything manually right?

**Comment by Lindennerd** [comment]
@jn-novasol have you figured it out? can you share the solution?

**Comment by WonderPanda** [comment]
You're supposed to just use the `RabbitSubscribe` and `RabbitRPC` decorators so that the library will automatically wire up the bindings for you
