### ISSUE TITLE
Rabbitmq publish: how to create routing key, binding and queue

### ISSUE THREAD

**Issue by jn-novasol** [golevelup/nestjs#486]
Hi,

So, I'm creating a simple service in Nest that only has to publish messages to RabbitMQ through an exchange to a queue.

My service  uses "golevelup/nestjs-rabbitmq" and so far when I publish a message then the specified Exchange is created automatically. However, I then manually have to create the queue and add the routing key binding before it work!

I'm just using something like the example:
`amqpConnection.publish('some-exchange', 'routing-key', { msg: 'hello world' });`

But there is no option to specify a queue, am I missing something? Help much appreciated. 

Regards J

**Comment by Ori-b** [comment]
You might namually do:
1. amqpConnection.managedChannel.**assertQueue**(queueName, assertQueueOptions..
2. amqpConnection.managedChannel.**bindQueue**(queueName, exchangeName, routingKey) .... or ..bindExchange(.....

**Comment by Ori-b** [comment]
@jn-novasol ,

Actually by defining a rabbit message handler you can get the same result (queue & exchange & binding), (no need to do it explicitly)
 @RabbitSubscribe({
    exchange: 'exchange.name',
    queue: 'queue.name',
    routingKey: 'routing.key',
    queueOptions: { durable: true },
  })....
  
  in addition 
  1. a routing key can be bound to more than one queue,
  2. there is a sendToQueue service on the underlying library (ampqlib) that as far as I know is not exposed in the wrapper library

**Comment by WonderPanda** [comment]
Yeah, as @Ori-b has mentioned the most straight forward way is to use the decorators provided by the library to set things up for you
