### ISSUE TITLE
[GraphQL] - Enhance README.md

### ISSUE THREAD

**Issue by Dunky13** [golevelup/nestjs#493]
Please add documentation on - not only how to set up the package but also - how to execute queries.

Right now have to find it out ourselves. Would make the developer experience better! :)

**Comment by underfisk** [comment]
@Dunky13 This library will wrap and inject for you the `graphql-request` which is a third party but i'll make sure i add a quick explanation and link for people to read that package where there are plenty of examples and more context

**Comment by RyanofWoods** [comment]
I think this would be beneficial as well, though I don't see an example
