### ISSUE TITLE
Nest js fails to run when RabbitMq is not reachable and the service is using @RabbitSubscribe or @RabbitRPC for listening a queue. 

### ISSUE THREAD

**Issue by vijaycenation14** [golevelup/nestjs#494]

**Comment by vijaycenation14** [comment]
https://github.com/golevelup/nestjs/blob/241a64075e06e15d273994ae786e7d0acec09c31/packages/rabbitmq/src/amqp/connection.ts#L340

Issue is in this function. Have to handle the failure scenario.

I.e, When addSetup fails, function doesn't call the callback instead it returns undefined.

**Comment by vijay94** [comment]
Raised a PR also

https://github.com/golevelup/nestjs/pull/495

**Comment by vijay94** [comment]
@WonderPanda

**Comment by davidtemplin** [comment]
I have experienced the same issue. When a connection to the RabbitMQ broker cannot be established, the NestJS application fails to start, even with `{ connectionInitOptions: { wait: false } }`. However, after I applied the patch suggested in #495 locally the application started successfully. I would like to begin using this package very soon, so if there is any way that the pull request can get reviewed and merged quickly, I would greatly appreciate it.

**Comment by vijay94** [comment]
@WonderPanda The fix was made only to RabbitSubscribe and not been done to RabbitRPC. Can Raise a merge request for the same?

**Comment by WonderPanda** [comment]
Sure, feel free to provide the fix and I will merge and publish a new
package version

**Comment by SnakeDrak** [comment]
This issue is occurring again due to https://github.com/golevelup/nestjs/pull/769. What would be the best way to resolve it?

@WonderPanda

**Comment by underfisk** [comment]
@SnakeDrak Thanks for reporting it. I believe we'll need to reproduce and make sure that we have test coverage to avoid any regression when doing any more modifications to that function logic.
