### ISSUE TITLE
Nest can't resolve dependencies of the PaymentService Please make sure that the argument Symbol(STRIPE_CLIENT_TOKEN)  in the BookingModule context.

### ISSUE THREAD

**Issue by mm-kitchenswaps** [golevelup/nestjs#499]
Hi there i am following instructions to the T and it's not working. I get this error:

[Nest] 92832  - 08/20/2022, 11:46:03   ERROR [ExceptionHandler] Nest can't resolve dependencies of the PaymentService (HttpService, UserService, BookingService, VivaWalletService, DatabaseService, ?). Please make sure that the argument Symbol(STRIPE_CLIENT_TOKEN) at index [5] is available in the BookingModule context.

Potential solutions:
- If Symbol(STRIPE_CLIENT_TOKEN) is a provider, is it part of the current BookingModule?
- If Symbol(STRIPE_CLIENT_TOKEN) is exported from a separate @Module, is that module imported within BookingModule?
  @Module({
    imports: [ /* the Module containing Symbol(STRIPE_CLIENT_TOKEN) */ ]
  })

It happens when i add     @InjectStripeClient() private stripeClient: Stripe, into my service. 

Any help would be greatly appreciated..

**Comment by Thanh-Nashtech** [comment]
I am also looking for solutions.

**Comment by jeppe-smith** [comment]
Add `StripeModule.externallyConfigured(StripeModule, 0),` to `imports` of `BookingModule`
