### ISSUE TITLE
Routing using Channels / Queues

### ISSUE THREAD

**Issue by car1ot** [golevelup/nestjs#510]
Hello. 
Routing is not explained in this module documentation.
Please, explain me how to send request to specific channel / queue. 

From docs:
```
  @RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'subscribe-route',
    queue: 'subscribe-queue',
    queueOptions: {
      channel: 'channel-2',
    },
  })
```

No explanation how to send request to queue or channel.

Should I use:

```
  amqpConnection.request({
    exchange: '...'
    routingKey: '...',
    payload: '...',
    queue: '...',
    queueOptions: {
      channel: '...'
    }
  });
```

like this?

No documentation for usage of request

**Comment by underfisk** [comment]
@ttshivers Based on your changes/proposal could you help with @car1ot question?

**Comment by ttshivers** [comment]
> @ttshivers Based on your changes/proposal could you help with @car1ot question?

My change isn't really affecting the rpc/request method at all. It appears that the `request` api in the library only allows specifying what exchange and routing key it uses.
https://github.com/golevelup/nestjs/blob/8962eed4ce527dba11fe7799de58cdf33d066e52/packages/rabbitmq/src/rabbitmq.interfaces.ts#L33-L41

**Comment by underfisk** [comment]
I see, that makes sense, our package has a partial pick of the underlying interface, I'm closing this long-standing issue unless there's still some doubt from the ticket creator
