### ISSUE TITLE
amqplib.ConsumeMessage does not works with @RabbitPayload() decorator 

### ISSUE THREAD

**Issue by m1n-q** [golevelup/nestjs#518]
```typescript
@UsePipes(
  new ValidationPipe({
    whitelist: true,
    forbidNonWhitelisted: true,
    transform: true,
    exceptionFactory: RmqErrorFactory('HERE'),
  }),
)
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @RabbitSubscribe({
    exchange: process.env.RMQ_USER_TOPIC,
    /* Competing Consumer must provide queue name*/
    queue: 'notification.user.event.q',
    routingKey: 'user.event.*.rk',
    errorHandler: RmqErrorHandler,
  })
  handleUserEvent(
    @RabbitPayload() msg,
    rawMessage: amqplib.ConsumeMessage,
  ): void {
    console.log(msg);
    console.log(rawMessage);
    // return this.appService.handleUserEvent(msg);
  }
}
```

I'm using `@RabbitPayload()`  decorator to use Pipe,  as guided by docs.
It seems that cannot get the `rawMessage` with that decorator. (undefined)
Without it, get `msg` and `rawMessage` but Pipe does not works.

How can I use both `Pipe` and `ConsumeMessage`?

**Comment by underfisk** [comment]
@m1n-q Unfortunately pipes are not supported yet since the RabbitMQ module has its own behaviour, we do not leverage Nestjs lifecycle but its intended in a future major to do so (also event handlers are created within services)

**Comment by m1n-q** [comment]
@underfisk It seems to be supported on [docs](https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#interceptors-guards-pipes), and it works. The problem is that `@RabbitPayload()` (needed to use pipes ) gets rid of `rawMessage`, the second param of handler.

**Comment by underfisk** [comment]
@m1n-q Indeed, it looks like it is supported but I don't know to what extent you can pass pipes for the arguments (i don't use the rabbitmq library for a while but if you spot the issue on the codebase, and wanna provide a PR to fix it, it's welcomed)

**Comment by m1n-q** [comment]
I couldn't find it in the documentation, but it seems to be possible to make it work by using `@RabbitRequest` instead of `ConsumeMessage`.

```
@RabbitSubscribe({
    exchange: process.env.RMQ_USER_TOPIC,
    /* Competing Consumer must provide queue name*/
    queue: 'notification.user.event.q',
    routingKey: 'user.event.*.rk',
    errorHandler: RmqErrorHandler,
  })
  handleUserEvent(
    @RabbitPayload() msg,
    @RabbitRequest() rawMessage,   // like this
  ): void {
    console.log(msg);
    console.log(rawMessage);
    // return this.appService.handleUserEvent(msg);
  }
}
```

It would be great if this item appeared in the documentation.

**Comment by nolawnchairs** [comment]
> I couldn't find it in the documentation, but it seems to be possible to make it work by using `@RabbitRequest` instead of `ConsumeMessage`.
> 
> ```
> @RabbitSubscribe({
>     exchange: process.env.RMQ_USER_TOPIC,
>     /* Competing Consumer must provide queue name*/
>     queue: 'notification.user.event.q',
>     routingKey: 'user.event.*.rk',
>     errorHandler: RmqErrorHandler,
>   })
>   handleUserEvent(
>     @RabbitPayload() msg,
>     @RabbitRequest() rawMessage,   // like this
>   ): void {
>     console.log(msg);
>     console.log(rawMessage);
>     // return this.appService.handleUserEvent(msg);
>   }
> }
> ```
> 
> It would be great if this item appeared in the documentation.

Where is this decorator `@RabbitRequest`? It's not expored from the `@golevelup/nestjs-rabbitmq` module.

**Comment by nolawnchairs** [comment]
> I couldn't find it in the documentation, but it seems to be possible to make it work by using `@RabbitRequest` instead of `ConsumeMessage`.
> 
> ```
> @RabbitSubscribe({
>     exchange: process.env.RMQ_USER_TOPIC,
>     /* Competing Consumer must provide queue name*/
>     queue: 'notification.user.event.q',
>     routingKey: 'user.event.*.rk',
>     errorHandler: RmqErrorHandler,
>   })
>   handleUserEvent(
>     @RabbitPayload() msg,
>     @RabbitRequest() rawMessage,   // like this
>   ): void {
>     console.log(msg);
>     console.log(rawMessage);
>     // return this.appService.handleUserEvent(msg);
>   }
> }
> ```
> 
> It would be great if this item appeared in the documentation.

Yes, the documentation is very poor
