### ISSUE TITLE
Publish does not send message if applications shuts down after directly

### ISSUE THREAD

**Issue by wodka** [golevelup/nestjs#519]
In a test script of us I realised that calling ampqConnection.publish will not deliver messages if there is not at least one await after it.

```ts
public doesNotDeliverMessage() {
  this.amqpConnection.publish(...)
}

public async doesDeliverMessage() {
  this.amqpConnection.publish(...)
  await new Promise(resolve => setTimeout(resolve, 1000))
}
```

is there some way to check if there are not yet delivered messages?

**Comment by underfisk** [comment]
@wodka There's an optional callback on publishing that is invoked once the message is sent or failed but I don't think we have the underlying implementation for that. If you would like to create a PR with that, feel free

**Comment by wodka** [comment]
@underfisk yes I can - what would you actually prefer there?

a) promise return of publish to be able to await it / catch the error if something goes wrong
b) another parameter to the function to pass the callback?

I personally lean more towards option a) - but it would imply a change in return value (void vs Promise<void>)

**Comment by underfisk** [comment]
@wodka Would you be up to contributing to that change? I see potential in there but currently, i don't have the time/context to add it so

**Comment by wodka** [comment]
yes :) did just that
