### ISSUE TITLE
How do i recive the message in dead letter queue

### ISSUE THREAD

**Issue by Abubakar989** [golevelup/nestjs#520]
i want to configure the dead letter mechanism in my project that . when any exception occur in code the the message is automatically goes into the dead letter queue. but it is not working . 
  @RabbitSubscribe({
    exchange: 'ampq',
    routingKey: 'ab',
    queueOptions: {
      deadLetterExchange: 'dead',
    },
  })

**Comment by victorperin** [comment]
Any advance on this? I'm having the same problem.

**Comment by owolfy** [comment]
Have you tried to add deadLetterRoutingKey to queueOptions? Should be like this:

```
@RabbitSubscribe({
        exchange: 'ampq',
        routingKey: 'ab',
        queueOptions: {
            deadLetterExchange: 'dlx',
            deadLetterRoutingKey: 'dlx_route'
        },
    })
```

```
@RabbitSubscribe({
        exchange: 'dlx',
        routingKey: 'dlx_route',
        queue: 'dlx_queue'
    })
```
