### ISSUE TITLE
@golevelup/nestjs-graphql-request but for OpenApi

### ISSUE THREAD

**Issue by Distortedlogic** [golevelup/nestjs#523]
Is there an equivalent for @golevelup/nestjs-graphql-request that generates a type-safe sdk for a rest api using its open-api spec?

**Comment by underfisk** [comment]
@Distortedlogic Yes, there is, for example https://github.com/OpenAPITools/openapi-generator

**Comment by Distortedlogic** [comment]
This link does not produce a nestjs injectable sdk that I see; am i missing it? There is a vanilla codegen for graphql like ur link does for openapi but yall still have @golevelup/nestjs-graphql-request which specifically creates a nestjs injectable sdk but do not an equivalent for openapi.

I am aware I can generate vanilla type safe fetchs given an openapi spec, but it would be awesome to be able to create a nestjs injectable sdk given the open api spec, like @golevelup/nestjs-graphql-request does for graphql. Make sense? Even if yall still dont plan to do it, just making sure we on the same page.

**Comment by underfisk** [comment]
@Distortedlogic Oh I see, yes you have https://www.the-guild.dev/graphql/codegen

**Comment by Distortedlogic** [comment]
yes there is graphql-codegen and @golevelup/nestjs-graphql-request

and there is openapi-generator and ?? (@golevelup/nestjs-openapi-request) ??

**Comment by underfisk** [comment]
@Distortedlogic golevelup does not have any codegen if that's what you're looking for

**Comment by Distortedlogic** [comment]
yes, thats my feature request lol. Or at least throwing the idea out there given openapi seems here to stay.

**Comment by underfisk** [comment]
@Distortedlogic It is out of scope or at least there's nothing planned to do so
