### ISSUE TITLE
transforming mocked context into GqlContext throws error

### ISSUE THREAD

**Issue by Mnigos** [golevelup/nestjs#527]
I tried doing `createMock<GqlExecutionContext>()` and `createMock<ExecutionContext>()`

Both of them throws error while using inside `GqlExecutionContext.create()`

```
    TypeError: Cannot read properties of undefined (reading 'req')

      12 |       context.getType() === 'http'
      13 |         ? context.switchToHttp().getRequest()
    > 14 |         : GqlExecutionContext.create(context).getContext().req
```

**Comment by underfisk** [comment]
@Mnigos It is related to the fact that the context is undefined, creating a mock doesn't guarantee you that `req` is injected (as in Nest it also can lead to the same behaviour) but my request would be a minimal repo if possible to quickly play around with this and see what i can do
