### ISSUE TITLE
SWC Support?

### ISSUE THREAD

**Issue by rivatove** [golevelup/nestjs#529]
Hi, does this work with the SWC compiler?
https://github.com/swc-project/swc

I'm getting `TypeError: Cannot read properties of undefined` errors, suggesting that mocking of classes is not working.

**Comment by underfisk** [comment]
@rivatove Do you have a repro project? It should work with SWC unless there is an unsupported feature or babel on the consume side but I have used the testing package with SWC and it did work flawlessly

**Comment by rivatove** [comment]
@underfisk Could you share your .swcrc file? Maybe there's a setting I've overlooked

**Comment by underfisk** [comment]
@rivatove I'm using the default but here it goes
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2018",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```
