### ISSUE TITLE
the interceptor causes rabbitconsumer error

### ISSUE THREAD

**Issue by 4haohansen2033** [golevelup/nestjs#53]
the global interceptor handle result of http reponse .but message from rabbitmq don't  get response object ,it will occur  TypeError.  meanwhile，rabbitmqm will doesn't get ack.  the consumer wiil alway get the message
![image](https://user-images.githubusercontent.com/18458663/66980359-33dee980-f0e3-11e9-8c40-e5c282f82af0.png)
![image](https://user-images.githubusercontent.com/18458663/66980740-59202780-f0e4-11e9-8ff3-b689cb223768.png)

**Comment by WonderPanda** [comment]
@4haohansen2033 Are you able to share a small repository or some other details that allow this to be easily reproduced? I don't have enough information from this ticket to look into it further

**Comment by WonderPanda** [comment]
Closing for lack of detail. Feel free to open again if there's more information available

**Comment by WonderPanda** [comment]
@4haohansen2033 Please see the workaround in #204
