### ISSUE TITLE
how to dynamic config RabbitSubscribe params

### ISSUE THREAD

**Issue by 4haohansen2033** [golevelup/nestjs#54]
As title. i want to config param by file.

**Comment by WonderPanda** [comment]
Can you share an example of what the file might look like? It might be possible for you to simply read the file inside of your application code and pass those values to the `RabbitSubcribe` decorator

**Comment by WonderPanda** [comment]
Closing as there's no follow up information for this. Feel free to re open if there is more detail to go on
