### ISSUE TITLE
Execution context loses http response with stripe webhook handler

### ISSUE THREAD

**Issue by kaansan** [golevelup/nestjs#541]
I can't reach http response at global exception filter due to this library., I can not send HTTP response to stripe.
Do you have a solution for accessing response object at global enhancers for stripe webhook route?
 

I assume External Contexts as written in Readme docs, causes this. I've handled this case in my global exception filter but how can I send a HTTP response from there?

or is  there an alternative way to access response object?

**Comment by CarsonF** [comment]
You can re-throw the exception in this case and so it bubbles out of the stripe webhook context up to the http context where you have the exception.

Here's a snippet from my global exception filter
```ts
  catch(exception: any, host: ArgumentsHost) {
    if (
      host.getType<ContextType | 'stripe_webhook'>() === 'stripe_webhook'
    ) {
      // We’ll let the exception bubble up and let the outer context handle this
      // error by returning an HTTP error response.
      // Note that this means that handler errors can affect other handlers.
      // We accept this isolation break (it could mess up other event handlers
      // for the same event if they are not idempotent), to allow stripe to be
      // aware of the error handling this event, so it can handle the retry logic.
      throw exception;
    }

    // send http error response
  }
```
