### ISSUE TITLE
Multiple consumer threads for one RabbitSubscribe method

### ISSUE THREAD

**Issue by josephtaylor** [golevelup/nestjs#544]
Question: Is it possible to configure consumers in such a way that you have multiple consumer threads active for one `@RabbitSubscribe` funciton?

**Comment by WonderPanda** [comment]
I don't think I understand what is being asked here. If this is important to you, can you try to provide some more context as to what you're trying to accomplish and what this would actually look like?

Closing for now as its not actionable
