### ISSUE TITLE
Feature: Exposing private methods like setupQueue from AmqpConnection

### ISSUE THREAD

**Issue by sebsastianek** [golevelup/nestjs#545]
Hello, is it possible we expose some rabbit private methods from AmqpConnection ? 
I need to ensure, and create otherwise, that certain queues exists without a need of registering a consumer.
Basically im writing a test setup script and would like to use your library rather than ie. python or plain amqplib since i have it already integrated in project.

**Comment by underfisk** [comment]
@sebsastianek Feel free to open a PR with the methods you'd like to expose and a bit of context

**Comment by WonderPanda** [comment]
The `AmqpConnection` object exposes the underlying AMQP primitives using the `channel` and `connection` getters.

You should be able to just inject it and then write whatever custom logic you need
