### ISSUE TITLE
Is Their Any Chance for Integrating Hasura Actions 🙏

### ISSUE THREAD

**Issue by LeulAria** [golevelup/nestjs#548]

**Comment by LeulAria** [comment]
Porbably some think like

```ts
@TrackedHasuraActionHandler({
    name: 'login',
    payload: {},
    comment: 'news letter email cron',
  })
  public login() {
        // login logic...
  }
```

their have been new feature in hasura that allow to import api from OpenAPI specs may be can help

**Comment by WonderPanda** [comment]
I don't have plans on spending time on this for the forseeable future. I played around with concepts for this way back in the day but there's a lot of boilerplate of getting the right GraphQL type definitions properly generated and it didn't feel like a great integration.

For my own projects I rather use [Remote Schemas](https://hasura.io/docs/latest/remote-schemas/index) using the @nestjs/graphql package.

If importing from OpenAPI specs is supported now, I'd recommend you go that route instead and just use the Swagger decorators to make it easy to import existing endpoints into Hasura
