### ISSUE TITLE
RabbitMQ stops processing any messages when there are unhandled RPC messages

### ISSUE THREAD

**Issue by car1ot** [golevelup/nestjs#551]
There are microservices architecture. The microservices communicate with each other using RabbitMQ RPC direct messages. However, if one of the microservices crashes or there is another reason for the Rabbit consumer to shut down, messages may become stuck in the queue. In this scenario, approximately 1000 messages are waiting to be delivered.

When there are unhandled messages in the queue, RabbitMQ stops delivering any messages and becomes really stuck. This means that no new messages are being processed! Even if they are not related to the unhandled messages!

Please, help resolving this issue. Do this issue related to RabbitMQ or this lib?

**Comment by SevrainChea** [comment]
Hi, I stumbled accross the same issue and I think you are missing an errorHandler in your RPC handler. Try adding : 

```
import { defaultNackErrorHandler, RabbitRPC } from '@golevelup/nestjs-rabbitmq';
....
  @RabbitRPC({
    queue: process.env.NOTIFICATIONS_DISPATCHER_QUEUE_NAME,
    routingKey: process.env.NOTIFICATIONS_DISPATCHER_QUEUE_NAME,
    errorHandler: defaultNackErrorHandler, // <---- 
  })
```

Hope it helps

**Comment by WonderPanda** [comment]
The correct way to handle this for right now as @SevrainChea has pointed out is to use an `errorHandler`.

Early on in the design of the library I didn't want to assume that people would want automatic Nack behavior in the case of an error being thrown but it definitely seems like a recurring problem that people run into where they're expecting it to happen and not handling the fact that in the absence of an errorHandler the messages will be requeued
