### ISSUE TITLE
How to set StripeModule globally?

### ISSUE THREAD

**Issue by twigs67** [golevelup/nestjs#552]
I can't for the life of me figure out how to set the module globally so I don't have to inject it into every module that uses it?

**Comment by WonderPanda** [comment]
Can you just make your own Module which wraps it and then mark that one as Global?

**Comment by twigs67** [comment]
Ya, that can be done, but I see in the code it accepts `global` as an option. I just can't figure out how to pass it.

**Comment by twigs67** [comment]
That worked.
