### ISSUE TITLE
How to unbind a routing key from the queue?

### ISSUE THREAD

**Issue by xfd1387** [golevelup/nestjs#555]

**Comment by WonderPanda** [comment]
You're free to inject the `AmqpConnection` into your services which gives you full control to to interact with the underlying AMQP Channel and execute whatever custom logic for binding/unbinding you'd like

**Comment by xfd1387** [comment]
I'm afraid that's still not possible even if you inject and use the AmqpConnection. It only provides amqp-connection-manager ChannelWrapper functions which unfortunately misses the unbindQueue function.

**Comment by WonderPanda** [comment]
@xfd1387 You can juse `AmqpConnection.channel`. It returns the raw `Channel` from `amqplib` and has an `unbindQueue` method on it
