### ISSUE TITLE
AmqpConnection publish return type is not a promise

### ISSUE THREAD

**Issue by Nicklason** [golevelup/nestjs#556]
The return type in the typescript definition file is void instead of a promise.

![image](https://user-images.githubusercontent.com/21038945/219391619-e43e7b99-7212-4e55-bb81-f6c4cc88790c.png)

connection.d.ts
![image](https://user-images.githubusercontent.com/21038945/219391680-6d2f6b79-ff39-4379-81c5-d22569e60fbd.png)

connection.ts
https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L539

I am using the latest version but it looks like it has been like this for a while and I only noticed it now.

**Comment by WonderPanda** [comment]
The underlying amqp lib's publish method is void as well. It would be weird to mark our publish as async when it is not awaiting anything inside. Is this causing problems for you?

**Comment by Nicklason** [comment]
> The underlying amqp lib's publish method is void as well. It would be weird to mark our publish as async when it is not awaiting anything inside. Is this causing problems for you?

I am not sure I understand you. This library returns a promise when publishing, but it is typed as a void in the typescript definition. It should be typed as a promise because that is what the function returns. The amqplib library uses callbacks to confirm that a message has been acknowledged.

**Comment by WonderPanda** [comment]
@Nicklason I think that this is addressed now in `@golevelup/nestjs-rabbitmq@3.5.0`.

Can you have a look and see if you're still running into this issue? I'm going to close this for now as the `connection.d.ts` but feel free to re-open if it continues to cause you problems after upgrading

**Comment by Nicklason** [comment]
@WonderPanda Thank you I can see that the type is now updated :-)

**Comment by WonderPanda** [comment]
> @WonderPanda Thank you I can see that the type is now updated :-)

Awesome, glad that its working for you. Sorry for the inconvenience
