### ISSUE TITLE
@golevelup/ts-jest doesn't work with injectGlobals=false

### ISSUE THREAD

**Issue by Yehonal** [golevelup/nestjs#557]
If we use ts-jest createMock together with jest and [injectGlobal:false](https://jestjs.io/docs/configuration#injectglobals-boolean), we have:

```ReferenceError: jest is not defined```

However, jest 29 encourages the usage of `@jest/globals` instead of injecting them.

**Comment by WonderPanda** [comment]
I don't have any intention at the moment of trying to adapt the library to support this. Too many other things on the go for this to be a priority. If you have a suggestion for a fix I'll gladly merge PRs but I'm not planning on doing any development on `@golevelup/ts-jest` for the forseeable future
