### ISSUE TITLE
Intercept handler args values

### ISSUE THREAD

**Issue by sskorol** [golevelup/nestjs#56]
Hi @WonderPanda,

According to docs, a handler is available within `DiscoveredMethod`:
```
export interface DiscoveredMethod {
  handler: (...args: any[]) => any;
  methodName: string;
  parentClass: DiscoveredClass;
}
```
But how we can intercept the actual method's call to access `args` values? The same way plain decorators allow us to do.

**Comment by WonderPanda** [comment]
Hey @sskorol Can you explain your use case a little bit more? I wouldn't expect someone to use the Discovery module to try to intercept method calls, that's the point of some of the existing NestJS components. [Interceptor](https://docs.nestjs.com/interceptors) can do what you're describing

**Comment by sskorol** [comment]
Hey @WonderPanda 
Let's say we want to apply permissions to DAO layer. We can create a custom decorator which defines some rules (e.g. resource / actions). But some arguments likes ids are dynamic. So we need to extract them from method's signature. Yes, we can easily do that via a common technique by accessing descriptor. But in this case we won't be able to use any kind of DI to inject providers into decorator's processor, as it's a plain function which has no idea about Nest context.

Your discovery feature has one big advantage - as you allow working on a class level, we can inject instance providers to apply required permissions' rules. The only blocker that I see now is the inability to override actual handler's behavior. But to achieve that we need to get an access to descriptor.

In regards to interceptors: the main problem here is that it's intended to be used on controller's layer, as well as guards and other cool features. And it was really disappointing to realize that custom decorators created via built-in Nest functionality are useless everywhere except controllers.

**Comment by WonderPanda** [comment]
Your use case sounds interesting. Can you share a snippet (even in pseudo code) of how you would like to apply your interception logic at the discovery layer? It may be possible to wrap and replace the handler with additional logic but I don't yet have a big enough understanding of exactly what functionality you would require.

Interceptors aren't limited to Controllers, you can also put them on Injectable Services. There's an example and tests of using an Interceptor on a Service method connected to RabbitMQ RPC in the repository:

https://github.com/WonderPanda/nestjs-plus/blob/09c493187b79fb4f4bc48eb21ba34002f2c8638c/integration/rabbitmq/src/rpc/rpc.service.ts#L19

https://github.com/WonderPanda/nestjs-plus/blob/09c493187b79fb4f4bc48eb21ba34002f2c8638c/integration/rabbitmq/e2e/rpc.e2e-spec.ts#L40

**Comment by sskorol** [comment]
@WonderPanda it could be something like the following:
```typescript
import { DiscoveredMethodWithMeta, DiscoveryModule, DiscoveryService } from '@nestjs-plus/discovery';
import { Inject, Injectable, Module, OnModuleInit, SetMetadata } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { PermissionDao } from '../permission/Permission.dao';
import { Action, Resource } from '../permission/Permission.entity';
import { User } from '../user/User.entity';

@Module({
  imports: [DiscoveryModule]
})
export class ExampleModule implements OnModuleInit {
  @Inject() private readonly discover!: DiscoveryService;
  @Inject() private readonly permissionDao!: PermissionDao;
  // not sure it'll work on a module level
  @Inject(REQUEST) private readonly request!: Request;

  public async onModuleInit() {
    const providers: Array<
      DiscoveredMethodWithMeta<PermissionDecoratorData>
    > = await this.discover.providerMethodsWithMetaAtKey<PermissionDecoratorData>('permission');
    providers.forEach(provider => {
      // would be nice to have a descriptor here
      const descriptor: PropertyDescriptor = provider.discoveredMethod.descriptor;
      const original: any = descriptor.value;
      const permission: PermissionDecoratorData = provider.meta;
      const checkPermissionsFn = (id: number) =>
        this.permissionDao.checkPermissions(this.request.user.id, permission.action, id);

      if (typeof original === 'function') {
        descriptor.value = function(...args) {
          checkPermissionsFn(args[0]);
          return original.apply(this, args);
        };
      }
    });
  }
}

@Injectable()
export class UserDao {
  @Permission(Resource.USER, Action.CREATE)
  public getUserInfo(id: number): User {
    // perform some DB-related stuff
  }
}

export interface PermissionDecoratorData {
  resource: Resource;
  action: Action;
}

export const Permission = (resource: Resource, action: Action) => SetMetadata('permission', { resource, action });

// Common descriptor's value overriding doesn't work with providers' injection
/*function Permission(resource: Resource, action: Action) {
  return (target, property: string, descriptor: PropertyDescriptor) => {
    const original: any = descriptor.value;

    if (typeof original === 'function') {
      descriptor.value = function(...args) {
        // permissionDao.checkPermissions(...)
        return original.apply(this, args);
      };
    }
  };
}*/
```
However, while writing this sample I realized that I'd also need a user's id which can be retrieved only from request. Moreover, there might be a problem interpreting module's `this` within descriptor's scope. As it'll refer to discovered class.

In regards to interceptors: will take a look at provided examples. Thanks.

**Comment by WonderPanda** [comment]
Yeah I have a strong feeling that what you're trying to accomplish is doable out of the box with Interceptors. I don't even think that you would need to use the Discovery module for this since you have access to the function that the Interceptor is applied to during it's execution. This would allow you to inspect the function to retrieve any decorated based metadata related to your Permissions that have been attached to it and implement your Interceptor logic accordingly.

I'm going to close this for now as I think it's outside of the scope of what the Discovery Module is designed for.
