### ISSUE TITLE
ACK and NACK are asynchronous

### ISSUE THREAD

**Issue by teamIgal** [golevelup/nestjs#565]
Hi I wrote a script that reads a bulk of messages through amqpConnection.channel.get() then I perform a bunch of data manipulation and then I ack or nack the messages with the functions amqpConnection.channel.ack() amqpConnection.channel.nack().

When the script ends and the connection closes and only 30% of the messages are actually acked,
when I add a timeout of a second all of the messages are acked which is probably points on the fact the those functions are asynchronous.

p.s: I know the problem is probably in the amqplib library

Thanks in advance

**Comment by WonderPanda** [comment]
Yeah this is an issue with `amqplib` and not with this library. I suggest you opening an issue on their repo

**Comment by teamIgal** [comment]
shukran ya zalame
