### ISSUE TITLE
Support for Stripe 11.x APIs

### ISSUE THREAD

**Issue by lsacco-nutreense** [golevelup/nestjs#568]
It appears your dev and peer dependencies are pinned to version 10.8.x of the Stripe API. Will there be support for Stripe 11.x APIs soon? They're already at 11.14.x right now.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: payments-service@1.6.1
npm WARN Found: stripe@10.17.0
npm WARN node_modules/stripe
npm WARN   stripe@"^11.14.0" from the root project
npm WARN   1 more (@golevelup/nestjs-stripe)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer stripe@"^10.8.0" from @golevelup/nestjs-stripe@0.6.0
npm WARN node_modules/@golevelup/nestjs-stripe
npm WARN   @golevelup/nestjs-stripe@"^0.6.0" from the root project
```

**Comment by CarsonF** [comment]
Merged 3 weeks ago, just not released. #560

**Comment by underfisk** [comment]
@WonderPanda Can we have a release anytime soon to support this? That would close the issue and provide support for v11

**Comment by underfisk** [comment]
This should be available at `0.6.2`

**Comment by garysb** [comment]
I think we should be looking at Stripe v12 now right?

**Comment by kasparkallas** [comment]
v13 now?

**Comment by lsacco-nutreense** [comment]
@kasparkallas This is an old ticket for v11. You probably want to open a new one for the newer versions. AFAIK, only v11 is currently supported.
