### ISSUE TITLE
why does console.log(myDeepMock) return empty object {}

### ISSUE THREAD

**Issue by laurencefass** [golevelup/nestjs#569]
Hi thanks for this module its brilliant. However I noticed a strange behaviour trying to log deep mocks

This works as expected.

```
import { createMock } from '@golevelup/ts-jest';
import { ExecutionContext } from '@nestjs/common';

describe('Mocked Execution Context', () => {
  it('should have a fully mocked Execution Context', () => {
    const mockExecutionContext = createMock<ExecutionContext>();
    expect(mockExecutionContext.switchToHttp()).toBeDefined();
  });
});
```
However adding  console.log(mockExecutionContext) outputs  => {} and not the object as expected. However intellisense works correctly as do jest assertions.

Sometimes its handy to just see the object in its entirety.

I can log the object using JSON.stringify(mockExecutionContext, null, 2) which does the same thing but the raw object appears to be empty!

Thanks

**Comment by WonderPanda** [comment]
Under the hood it is implemented using JS Proxy objects which act as a dynamic interception mechanism which won't be visible in a console.log. If you want to actually see stuff get printed out you can provide a partial implementation for the fields that actually matter to you
