### ISSUE TITLE
Cannot find module 'amqplib/properties'

### ISSUE THREAD

**Issue by llong2195** [golevelup/nestjs#570]
Thank you for the amazing module. I've encountered some issues while upgrading from 3.4.0 to 3.5.0.

node_modules/@golevelup/nestjs-rabbitmq/lib/amqp/connection.d.ts:3:25 - error TS2307: Cannot find module 'amqplib/properties' or its corresponding type declarations.

import { Replies } from 'amqplib/properties';

**Comment by volk234** [comment]
Same issue on 3.5.0. Installed with PNPM

**Comment by avnigenc** [comment]
Same issue:

node version: v18.14.2

"@nestjs/common": "^9.3.9",
"@nestjs/config": "^2.3.1",
"@nestjs/core": "^9.3.9",
"@nestjs/microservices": "^9.3.9",
"@golevelup/nestjs-rabbitmq": "^3.5.0",

**Comment by asnikitin** [comment]
npm install --save @types/amqplib
