### ISSUE TITLE
How to ack/nack a msg after processing

### ISSUE THREAD

**Issue by mayaank-gupta** [golevelup/nestjs#571]
My usage is very simple

@RabbitSubscribe({
exchange: 'exchange',
routingKey: 'create_payment_key',
queue: 'payment_queue',
})
public async consumer(msg: {}) {
const content = JSON.stringify(msg);
console.log(content);
}

Even I have a error handler configured.
On error my msg keep getting requeued.
I have to ack after successful processing and also ack on error.

**Comment by mayurc137** [comment]
So, the ack should be handled automatically by the library. If you want to ack on both if the tasks complete or if it fails then just put everything in a try-catch and the messages should be acked automatically.  Here is an example 


```
@RabbitSubscribe({
        exchange: 'message.incoming.exchange',
        queue: 'message.incoming.builder.queue',
        routingKey: '',
    })
    async handleIncomingMessage(data: Data) {
        const { type, payload } = data;
        try {
          // your code
        } catch (e) {
            console.log('ERROR', e);
        }
    }
```
