### ISSUE TITLE
Undefined message in rmq if allowNonJsonMessages flag is set to true

### ISSUE THREAD

**Issue by sdomagala** [golevelup/nestjs#574]
Hello,
Before I start I wanted to say this package helped me lots when integrating with RMQ in NestJS, so really appreciate it!

Today I stumbled on a problem that if I don't pass JSON serialisable message, there is no message and it seems that `RabbitPayload()` decorator doesn't work anymore in such case. I was struggling with getting around it until I checked [what happens in the code](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L590)
While I appreciate the type checking, I feel that if the flag `allowNonJsonMessages: true` is provided, the message should be returned as-is, or better yet (in my case), there could be an ability to provide your own parser - by default `JSON.parse` - so in the end it is a valid JS object.

Let me know what you think! If I find some time I could try and implement it

**Comment by WonderPanda** [comment]
This is definitely a stumbling block for a lot of people. We got a ton of issues opening up that are ultimately related to this behavior.

Sadly, I don't use RabbitMQ anymore as part of any development so my desire and mental context to be able to continue to support changes and feature requests for this package are very diminished. If you had an idea for how this could be improved and would like to implement it I would happily get that merged and published for you

**Comment by sdomagala** [comment]
Hey @WonderPanda,
Turns out I didn't look deep enough as custom parsers are already a thing in the code 😄 
I've added some docs to account for that and extended payload a bit, in my scenario I need to understand headers to parse incoming message, I expect it might be the case for other as well.

Please take a look when you have a moment
