### ISSUE TITLE
RabbitMQ: messages sometimes is not being delivered or get reply

### ISSUE THREAD

**Issue by car1ot** [golevelup/nestjs#579]
Hello. I am facing with a problem - sometines messages won't delivered to consumer, or sometimes messages provider didnt get a reply. I am only using direct messages and RabbitRPC. Error message that I get `amqp error Error: Failed to receive response within timeout of ****ms for exchange "****" and routing key "****"`.

At consumer side, I am using this code:
```
  @RabbitRPC({
    exchange: exchangeConst,
    routingKey: routingKeyConst,
    errorHandler: defaultNackErrorHandler,
    queueOptions: {
      durable: false,
      autoDelete: true,
    },
  })
  @UsePipes(ValidationPipe)
  @UseFilters(RpcExceptionFilter)
  async handler(
    @RabbitPayload() payload: DataDto,
  ): Promise<TResDto> {
    return await this.service.call(
      payload
    );
  }
```

At provider side, I am using request of amqpconnection injected to Nestjs service.

Sometimes, messages got delivered, but sometimes not. Data is not changing, nothing changing, there is random moment when some messages didnt delivered and timeout happened. No way. What to do with this problem?

**Comment by WonderPanda** [comment]
Its really impossible to know since this is highly dependent on your actual RabbitMQ infrastructure and the nature of your handlers. It sounds like the requests are timing out. Have you tried increasing the timeout limit to account for the possibility that your handlers take longer?

**Comment by rainerkent** [comment]
Hi @WonderPanda, 

We are also experiencing this issue. Upon trying different versions, we found out that something in version 3.5.0 caused this. We're locking our rabbitmq package version to 3.4.0 in the meantime.

To give context, we only use the `AmqpConnection.request()` method of the rabbitmq package to communicate with non-NestJS services. We confirmed on the consumers side that messages are sometimes not received. The probability of this happening increases when multiple requests are sent at the same time.

**Comment by car1ot** [comment]
Seems like it can cause `request` method in `nestjs/packages/rabbitmq/src/amqp/connection.ts`. The code uses an asynchronous publish operation and an observable `response$` to wait for the response. If there are any synchronization issues between these operations or if they are not properly managed, it could result in delays or inconsistent behavior.

**Comment by car1ot** [comment]
So the issue exists and need to be fixed. @WonderPanda , please, try to double check the code 🙏

**Comment by rainerkent** [comment]
This issue is most likely the same one described in #599.

**Comment by spryce** [comment]
@WonderPanda +1

**Comment by LborV** [comment]
@WonderPanda +1
