### ISSUE TITLE
Using a Config module/service

### ISSUE THREAD

**Issue by ziazon** [golevelup/nestjs#58]
So I tried 

```typescript
    RabbitMQModule.forRootAsync({
      useFactory: (config: ConfigService) => ({
        exchanges: [
          {
            name: config.rmqExchange,
            type: 'topic'
          }
        ],
        uri: config.rmqUrl
      })
    })
```
and at first I got the following error, which was odd because I'm pretty sure this is a bug?
![image](https://user-images.githubusercontent.com/1675902/67828815-3c53fe80-faab-11e9-993d-9432bc9827a5.png)

So then i installed `@nestjs-plus/common` and then i got what looks like an implementation error on my part:

![image](https://user-images.githubusercontent.com/1675902/67829092-33aff800-faac-11e9-87dd-c9e800fcfddd.png)

I'm basically trying to pass in a config from another module (my `ConfigModule` which exposes a `ConfigService`)  Any thoughts?

**Comment by WonderPanda** [comment]
@jubairsaidi Interesting regarding the missing @nestjs-plus/common. It should be installed as dependency of @nestjs-plus/rabbitmq. The TS error you're getting is saying that uri is expecting a single string, but what you're getting back from `config.rmqUrl` is a `string[]`. Are you intending to try and pass multiple URIs?

**Comment by WonderPanda** [comment]
@jubairsaidi You can see examples of different configuration techniques in the test suite that should cover what you're trying to do (once you fix the Type error):
https://github.com/WonderPanda/nestjs-plus/blob/master/integration/rabbitmq/e2e/configuration.e2e-spec.ts

**Comment by ziazon** [comment]
Thanks! that's very helpful!
