### ISSUE TITLE
Registering a single queue to multiple exchanges, only binds to the last registered exchange

### ISSUE THREAD

**Issue by rjpkuyper** [golevelup/nestjs#580]
**Situation:**
We have a use case, where a method has to be bound to multiple exchanges to listen to mutation routingKeys. The routingkeys can contain something like: `.created`, `.updated` or `.deleted`. The method itself, does not need to know anything about the publisher, it should only catch the mutation, and store it in a history table accordingly.

**Current behaviour**
We know that it is possible to bind a queue to multiple exchanges, and we actually see via the RabbitMQ UI, that we can bind a queue to multiple exchanges. But when we try to do it via the package, the binding is overwritten, by the last decorator:

```typescript
@Controller()
export class HistorySubscribers {

  // we expected, registering multiple decorators, would bind to multiple exchanges
  @RabbitSubscribe({
     exchange: 'foo', // exchange A
     queue: 'bar',
     routingKey: ['updated'],
  })
  @RabbitSubscribe({
     exchange: 'bar', // exchange B
     queue: 'bar',
     routingKey: ['updated'],
  })
  async updateHistory(@RabbitPayload() event: HistoryCreate) {
    console.log({ event })
  }

}
```

Doing so, will only take the last bound subscriber, and this bind only to exchange `bar`.

**Expected behaviour**
Subscribing to multiple exchanges, would bind to multiple exchanges, instead of overriding the previous.

**Comment by caminoezequiel** [comment]
@rjpkuyper did you evaluate use the exchange `topic`?

Maybe it can help you if the messages are publishing with a pattern like `[SpecificName].updated`, then you can listen `*.updated` on the exchange `amq.topic`

Here you can see more about topic if you don't have it:
https://www.rabbitmq.com/tutorials/tutorial-five-javascript.html

**Comment by rjpkuyper** [comment]
@caminoezequiel thank you for your comment.

We've refactored it by binding exchanges to other exchanges, and thus this way was not needed anymore: https://www.rabbitmq.com/e2e.html .

**Comment by teddyhendryanto** [comment]
hi @rjpkuyper , i have same goals with you and not able to do it programmatically. i manage to do it by manual setup from rabbitmq ui.
if you dont mind, how you achieve it in nestjs way for exchange to exchange binding, can you show how to do it?
thanks
