### ISSUE TITLE
Send message to a queue. 

### ISSUE THREAD

**Issue by mayaank-gupta** [golevelup/nestjs#585]
I just have a queue name and connection is there any way I can just publish message to a queue. 
queue dont have a routing key. 

is there any function 
publish(queueName, message);

I have my current AmqpConnection.

Thank you.

**Comment by caminoezequiel** [comment]
@mayaank-gupta You need to use the default exchange (it's empty) or maybe using `amq.direct` and use the queue name as `routingKey`

For example:
```
amqpConnection.publish('', 'q.directMessages', {
      prop1: 'testing-1',
      prop2: 'testing-2',
    });
```
