### ISSUE TITLE
Ack queue message on consume

### ISSUE THREAD

**Issue by mayaank-gupta** [golevelup/nestjs#591]
Below is my queue consumer. How can I ack message explicitly? 
  If I have multiple instances of service. How can I ensure only one instance should receive the message and it should ack?

```
 @RabbitSubscribe({
    exchange: envConfig.RABBITMQ_EXCHANGE_NAME,
    routingKey: 'xxxxxxxxxxxx',
    queue: 'xxxxxxx',
    createQueueIfNotExists: true,
    errorHandler: queueErrorHandler,
  })
  public async onEventQueueConsumption(msg: object, amqpMsg: ConsumeMessage) {
    let eventData = JSON.parse(amqpMsg.content.toString());
    await this.service.saveEvent(eventData.payload);
  }
```
  
the queue is of type `direct`

thank you.

**Comment by mayurc137** [comment]
Read more about competing consumers here -> https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#competing-consumers

It should be handled automatically. Make sure you do your processing inside a try-catch for automatic acks
