### ISSUE TITLE
[ts-jest] Support for mocking getters and setters 

### ISSUE THREAD

**Issue by pekunicki** [golevelup/nestjs#592]
👋
I would like to propose adding support for getters and setters for deep mocks. This would simplify unit testing and improve the readability of the code. Prisma is mostly using getters and setters. 

e.g. `jest-mock-extended` supports it pretty well.

**Comment by omermorad** [comment]
Hi @pekunicki,

Could you share some concrete examples or use cases? Seeing how this could play out in real-world scenarios would be helpful.

**Comment by underfisk** [comment]
I'll close this as this looks like a feature request and I'm not sure how would follow up. @pekunicki If you can come with more concrete example of feature(s) that you're looking for we might debate and think about implementing those if possible
