### ISSUE TITLE
Queue not bound to exchange

### ISSUE THREAD

**Issue by DominikusKrueger** [golevelup/nestjs#594]
Maybe someone can help me with this issue. 
I have 2 Microservices. The first one is supposed to publish messages to an exchange and the second one is supposed to react on those messages. The problem I am facing is, that the second one is not getting those messages, unless I manually bind the queue to the exchange. I assume I have done something wrong, but I was not able to figure out, what.

Emitting Service:

```
const RABBIT_MQ_USERNAME = process.env.RABBIT_MQ_USERNAME;
const RABBIT_MQ_PASSWORD = process.env.RABBIT_MQ_PASSWORD;
const RABBIT_MQ_HOST = process.env.RABBIT_MQ_HOST;
const RABBIT_MQ_PORT = process.env.RABBIT_MQ_PORT;

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModule, {
      exchanges: [
        {
          name: Rabbitmq.EXCHANGE_PERSON_DELETED,
          type: 'fanout',
        },
      ],
      uri: `amqp://${RABBIT_MQ_USERNAME}:${RABBIT_MQ_PASSWORD}@${RABBIT_MQ_HOST}:${RABBIT_MQ_PORT}`,
      enableControllerDiscovery: true,
      connectionInitOptions: { wait: false },
    }),
  ],
  providers: [],
  exports: [RabbitMQModule],
})
```

I am publishing to that exchange with `this.ampqConnection.publish(Rabbitmq.EXCHANGE_PERSON_DELETED, '', payload);`

-----

In the subscribing microservice I have the same code inserted into the module file and I am trying to catch the messages with this (in an controller)
```
  @RabbitSubscribe({
    exchange: Rabbitmq.EXCHANGE_PERSON_DELETED,
    queue: Rabbitmq.QUEUE_AUTHORIZATION_SERVICE_PERSON_DELETED,
    queueOptions: {
      durable: true,
      exclusive: false,
      autoDelete: false,
    },
  })
  public async handlePersonGotUpdated(msg: string) {
    console.log(
      `Received update controller message: ${JSON.stringify(msg)}`,
    );
 }
```

When the service is starting I do see the message `[Nest] 26400  - 13.05.2023, 09:18:12     LOG [RabbitMQModule] MyController.handlePersonGotDeleted {subscribe} -> exchange.person.deleted::undefined::queue.authorizationservice.person.deleted` in the log. But when I check the status of the exchange and the queue within rabbitmq, I see this:

![grafik](https://github.com/golevelup/nestjs/assets/32403938/fff44578-4e74-4e52-88d2-66156daf3083)

![grafik](https://github.com/golevelup/nestjs/assets/32403938/95627845-9842-45be-b7e4-faa5ea31d238)

When I manually bind the queue to the exchange in that admin panel the messages from service 1 are caught by service 2. I did assume the binding would have been done automatically by the `@RabbitSubscribe` decorator. But somehow they are not. What did I miss? Thank you very much!

**Comment by DominikusKrueger** [comment]
I did found a workaround for this issue: apparently it is not sufficient to set the properties of exchange and queue in a @RabbitSubscribe decorator. The `routingKey` is mandatory for the binding in the end. So this is resulting in an working mechanism:
```
  @RabbitSubscribe({
    exchange: Rabbitmq.EXCHANGE_PERSON_DELETED,
    routingKey: 'unused-but-mandatory-for-binding-queue-to-exchange',
    queue: Rabbitmq.QUEUE_AUTHORIZATION_SERVICE_PERSON_DELETED,
    queueOptions: {
      durable: true,
      exclusive: false,
      autoDelete: false,
    },
  })
  public async handlePersonGotUpdated(msg: string) {
    console.log(
      `Received update controller message: ${JSON.stringify(msg)}`,
    );
 }
```

**Comment by underfisk** [comment]
@DominikusKrueger I'm happy that you've found out a solution!
