### ISSUE TITLE
Filtering when meta is Nullish

### ISSUE THREAD

**Issue by HmFlashy** [golevelup/nestjs#595]
I try to get  the methods of all my handlers thanks to the metadata key `METHOD_METADATA` but since the methods GET = 0 in the RequestMethod enum
```
export declare enum RequestMethod {
    GET = 0,
    POST = 1,
    PUT = 2,
    DELETE = 3,
    PATCH = 4,
    ALL = 5,
    OPTIONS = 6,
    HEAD = 7
}
```
these methods are filtered

https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/discovery/src/discovery.service.ts#L175

It would be better to do something like this

```
.filter((x) => !isNull(x.meta)); // from lodash 
```

**Comment by WonderPanda** [comment]
Looks good to me. Feel free to open a PR
