### ISSUE TITLE
Ability to access to the consumerTags

### ISSUE THREAD

**Issue by ahdruwa** [golevelup/nestjs#596]
Hi! I ran into a problem that if we don't add a consumer c using the `AmqpConnection.createSubscriber` method, we actually have no way to access our `consumerTag`s. Although it could be useful for example to implement a graceful shutdown mechanism. Perhaps it makes sense to add a little getter that would work something like this?

 ```
 get consumerTags() {
     return Object.keys(this._consumers);
 }
 ```

**Comment by WonderPanda** [comment]
Looks okay to me. Feel free to open a PR
