### ISSUE TITLE
RPC not working on "fast" response

### ISSUE THREAD

**Issue by simonabler** [golevelup/nestjs#599]
Issue was discoverd after 7163ecaf948c96b081b803725c023cd75b99002a

RPC call ist not working correctly: RPCHandler is executed on the desired
function an even return to the main program.
But, the response is observed in the main program function: https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L288

## Problem
Response on direct queue was callbacked before lastValueFrom subscribed to messageSubject https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L348 
Therefore, there is no observer subscribed to
https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L308
...
## Temporarily Solution
I removed the await statement which was addes in  7163ecaf948c96b081b803725c023cd75b99002a https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L327

## Solution approach 
a better approach would be to change the order of the statementes and store the Promis in a Variable, so, no racecondition is violated.
See  https://github.com/simonabler/golevelup-nestjs/tree/fix-racecondition-rpc-request

Edit: c6fd2f3df3b6383c59ab408f95a83f40544a6c11

**Comment by car1ot** [comment]
@WonderPanda

**Comment by car1ot** [comment]
> Issue was discoverd after [7163eca](https://github.com/golevelup/nestjs/commit/7163ecaf948c96b081b803725c023cd75b99002a)
> 
> RPC call ist not working correctly: RPCHandler is executed on the desired function an even return to the main program. But, the response is observed in the main program function:
> 
> https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L288
> 
> ## Problem
> 
> Response on direct queue was callbacked before lastValueFrom subscribed to messageSubject
> 
> https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L348
> 
> Therefore, there is no observer subscribed to
> 
> https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L308
> 
> ...
> 
> ## Temporarily Solution
> 
> I removed the await statement which was addes in [7163eca](https://github.com/golevelup/nestjs/commit/7163ecaf948c96b081b803725c023cd75b99002a)
> 
> https://github.com/golevelup/nestjs/blob/75beb6fff9d60c0480ae7514a16feea8dac1f680/packages/rabbitmq/src/amqp/connection.ts#L327
> 
> ## Solution approach
> 
> a better approach would be to change the order of the statementes and store the Promis in a Variable, so, no racecondition is violated. See https://github.com/simonabler/golevelup-nestjs/tree/fix-racecondition-rpc-request
> 
> Edit: [c6fd2f3](https://github.com/golevelup/nestjs/commit/c6fd2f3df3b6383c59ab408f95a83f40544a6c11)

It seems like owner do not support this repository and it is a little deprecated for now. The issue is critical for my production nestjs software. It would be good if owner apply fixes.

**Comment by WonderPanda** [comment]
I just published this fix in @golevelup/nestjs-rabbitmq@3.6.1
