### ISSUE TITLE
Consuming From An Existing Durable Exchange

### ISSUE THREAD

**Issue by faruk-arslan** [golevelup/nestjs#602]
Hi, I'm trying to connect to an existing exchange and consume a queue. When I run my service, another exchange is created for the same topic and binded to it. All the routing key, queue name, exchange name params are same except the arguments. It does not use the existing one and creates a new exchange with no arguments. I already use `durable: true` for my exchange and queue config but yet still does not use it.
<img width="594" alt="image" src="https://github.com/golevelup/nestjs/assets/29980075/5b1c7aea-782a-45fa-9c58-2d6b4dd74a77">
Eventually I need to use the existing exchange, with the `durable: true` option.  
My config is like below:
`@RabbitSubscribe({
    queue: 'my-queue',
    exchange: 'my-exchange',
    routingKey: 'my-routing-key',
    queueOptions: {
      durable: true,
    },
    errorHandler: ackErrorHandler,
  })`
And for main.ts exchange config:
`exchanges: [
      {
        name: 'my-exchange',
        type: 'x-delayed-message',
        options: {
          durable: true,
        },
      },
    ]`

Using the `"@golevelup/nestjs-rabbitmq": "^3.6.0"`

**Comment by faruk-arslan** [comment]
@WonderPanda can you help with this?

**Comment by underfisk** [comment]
@faruk-arslan Hi, sorry for the late reply. Could you create a repro and post it here? That might be easier to just boot up and see what you're observing
