### ISSUE TITLE
Creating/Checking exchange/queue that already exists with different arguments?

### ISSUE THREAD

**Issue by MPuust** [golevelup/nestjs#605]
`Error: Operation failed: ExchangeDeclare; 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - Existing exchange 'reiterate-topic' declared with other arguments"`

What's the best way to use an already existing exchange/queue if the names are the same but arguments are different. 

Example: In python aio-pika (library for rabbitmq) declare_exchange and declare_queue take as a parameter passive=True, which instead of throwing an error for different arguments, connects to the existing exchange.

The question would be for subscribers and publishers alike.

**Comment by MPuust** [comment]
https://github.com/amqp-node/amqplib/pull/724/files

**Comment by underfisk** [comment]
I'm going to close this issue as that seem related to the underlying lib
