### ISSUE TITLE
feature request: RabbitMQ module support custom logger through DI

### ISSUE THREAD

**Issue by Hareloo** [golevelup/nestjs#607]
Currently, I am not sure if this package supports NestJS v10.
I am seeing one weird behavior which is that every log from the logger within `rabbitmq.module.ts` (`private readonly logger = new Logger(RabbitMQModule.name);` at line 67) seems to not go to the logger instance I passed but rather goes to the default logger of NestJS...

**Comment by underfisk** [comment]
@Hareloo Nestjs is a peer dependency just asking for `>9.x.x` meaning that `v10` is supported
Could you add a repro of what you're seeing, that might be easier to check the issue

**Comment by Hareloo** [comment]
Here's a reproduction: https://github.com/Hareloo/repro270623
Take note that you'll need to manually start up a rabbitmq instance on your local machine for it to run

**Comment by underfisk** [comment]
Thanks, as soon as i can I'll give it a shot and investigate

**Comment by underfisk** [comment]
@Hareloo So it looks like our logger is being created statically, meaning it doesn't rely on the DI logger. I think we would have to support receiving the logger through the constructor so that it could be initialized using the right factory. Right now I don't have enough time to develop such a feature as I'm not also using the rabbitmq module anymore but if you're willing to push such feature I'll be happy to review and push

**Comment by Hareloo** [comment]
Seems like this would be more complicated than you suggested, since all the packages of `@golevelup` are looking for NestJS version 9 exactly, not `> 9.x.x` which means v10 isn't supported.
This means we would have to upgrade all packages of `@golevelup` to support NestJS v10 as well as make sure nothing breaks...

**Comment by underfisk** [comment]
@Hareloo We might have to support v10 then first if you're willing to contribute that otherwise once I have some free time I'll push the peer to support v10

**Comment by underfisk** [comment]
@Hareloo I had some free time and I'm pushing support to v10 #617

**Comment by Hareloo** [comment]
@underfisk Alright, after it's merged I will test again (since when I'm using NestJS v9 my custom logger does work) and see if maybe that was enough to solve this.
If it isn't I will see how I can create a PR about this

**Comment by Hareloo** [comment]
Fixed now, I guess the logger couldn't initialize correctly due to mismatch in nestjs versions.
