### ISSUE TITLE
Can't install with nestjs 10

### ISSUE THREAD

**Issue by diegofaraujo** [golevelup/nestjs#619]
Receiving this error when I run npm install @golevelup/nestjs-rabbitmq

I'm using nestjs 10.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cargo@DEVELOPMENT_VERSION
npm ERR! Found: @nestjs/common@10.0.5
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^9.x" from @golevelup/nestjs-rabbitmq@3.7.0
npm ERR! node_modules/@golevelup/nestjs-rabbitmq
npm ERR!   @golevelup/nestjs-rabbitmq@"^3.6.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by NilsMoller** [comment]
I was able to install it using yarn, but can't start the Nest app. This has started happening to me when upgrading from Nest v9 to v10.

**Comment by newerton** [comment]
Same problem here! With NestJs 10.0.5

**Comment by NilsMoller** [comment]
They pushed Nest v10 support to master about 3 hours ago. Should work now!

**Comment by xfd1387** [comment]
NPM still behind? Is there gonna be a new release?

**Comment by WonderPanda** [comment]
Just published. Please let us know if there are any issues

**Comment by Chessman97** [comment]
![Снимок экрана от 2023-07-19 15-42-21](https://github.com/golevelup/nestjs/assets/47553161/1a402d72-1f11-4fdb-86db-8f478772dc37)

**Comment by diegofaraujo** [comment]
Thank you, works well.
