### ISSUE TITLE
Style swagger webhook endpoint

### ISSUE THREAD

**Issue by jinglestaging** [golevelup/nestjs#620]
Hi!

Does the library support style swagger please?

For example, edit the title, add a description.

Thanks!
<img width="995" alt="Snímek obrazovky 2023-07-12 v 20 49 45" src="https://github.com/golevelup/nestjs/assets/52261075/3cecbf3b-d819-4fe1-83cf-fa37575fb2c9">

**Comment by underfisk** [comment]
@jinglestaging It is possible if we received the document swagger options through module params, if you want to deliver that feature for the Stripe module, I'll be glad to merge it though but as of now i don't have much time to developer such thing
