### ISSUE TITLE
I need help to fix this error, it was working at v3.3.0 but after version update to 3.5.0 didn't

### ISSUE THREAD

**Issue by mohamedkashifaslam** [golevelup/nestjs#621]
Everything is working fine locally however when run in AWS cloud env in docker, it throw the following error

I'm using the package @golevelup/nestjs-rabbitmq (https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#golevelupnestjs-rabbitmq)

Error [ExceptionHandler] Nest can't resolve dependencies of the RabbitMQModule (DiscoveryService, ?, RabbitRpcParamsFactory, AmqpConnectionManager). Please make sure that the argument ExternalContextCreator at index [1] is available in the RabbitMQModule context.

Potential solutions:

If ExternalContextCreator is a provider, is it part of the current RabbitMQModule?
If ExternalContextCreator is exported from a separate @Module, is that module imported within RabbitMQModule?@Module({
imports: [ /* the Module containing ExternalContextCreator */ ]})

**Comment by NilsMoller** [comment]
Same here. Stopped working for me when upgrading from Nest 9 to 10

**Comment by NilsMoller** [comment]
This has started happening to me when upgrading from Nest v9 to v10.

**Comment by underfisk** [comment]
It happens when you have multiple nest versions, you should only run in one and `v10` isn't yet support

**Comment by NilsMoller** [comment]
Do you have an ETA on when v10 will be supported? The migration guide does not have any mention regarding changes in microservices.

EDIT: I see there is a PR for Nest v10 support, fantastic! #617
