### ISSUE TITLE
RabbitMQ: Support for exchange-to-exchange bindings

### ISSUE THREAD

**Issue by theabuitendyk** [golevelup/nestjs#625]
Related to https://github.com/golevelup/nestjs/issues/624

I'd like to add an option for exchange-to-exchange bindings to the config. An example use-case is service A publishes messages to a fanout exchange and service B wants to consume the messages using a consistent hash exchange.

Would there be support for adding something like exchangeBindings?

```ts
{
  exchanges: [
    {
      name: 'original-fanout-exchange',
      type: 'fanout',
    },
    {
      name: 'consistent-hash-exchange',
      type: 'x-consistent-hash',
    }
  ],
  exchangeBindings: [ // <-- addition
    {
      sourceExchange: 'original-fanout-exchange',
      targetExchange: 'consistent-hash-exchange',
      routingKey: '*'
    }
  ]
}
```

**Comment by WonderPanda** [comment]
Hey @theabuitendyk, I haven't been actively using RabbitMQ in quite some time so I don't have capacity to tackle this addition for the forseeable future but I'm definitely open to getting it merged in if you wanted to contribute the functionality

**Comment by theabuitendyk** [comment]
@WonderPanda Thanks for the reply. I'm happy to contribute! I'll get started on a PR.
