### ISSUE TITLE
Failed to connect to a RabbitMQ broker within a timeout of 5000ms

### ISSUE THREAD

**Issue by abduljafars** [golevelup/nestjs#626]
Hi,
If we upgrade node version from 14.21.2 to 18.15 then this package `@golevelup/nestjs-rabbitmq` throws an error : `Failed to connect to a RabbitMQ broker within a timeout of 5000ms`  & `[error]: [undefined] Disconnected from RabbitMQ broker (default)` .

I tried updating the version of @golevelup/nestjs-rabbitmq from 1.18.1 till latest none of them works kindly help.

**Comment by WonderPanda** [comment]
We have Node 18 test coverage in our e2e matrix and it works fine so its hard to help diagnose in issue like this. It seems related to your own code or the combination of other package versions that you ahve

**Comment by kakui-lau** [comment]
Have you solved the same problem？
