### ISSUE TITLE
[nestjs-modules][question] How to access module options during module registration or in forRoot/forRootAsync?

### ISSUE THREAD

**Issue by sheiman-pavlo** [golevelup/nestjs#632]
Hello,

I am struggling with dynamic module implementation. Basically, I need a way to import some other modules conditionally. For example, I want to import either RanbbitMQ  or Redis modules, based on driver property set in module options.

I have tried doing so in @Module decorator, with custom providers and finally by overriding forRoot/forRootAsync methods. Issue is that I can not access/inject module options.

It is completely straightforward for `forRoot` method, since options are passed as parameter. But I can't get my head around `forRootAsync` method. How do I access module options here?

My current module:
```typescript
@Module({})
export class EventBusModule extends createConfigurableDynamicRootModule<
  EventBusModule,
  EventBusModuleOptions
>(EventBusInjectionTokens.EVENT_BUS_MODULE_OPTIONS) {
  public static configuredInstance() {
    return EventBusModule.externallyConfigured(EventBusModule, 60 * 1000);
  }

  public static override forRoot(
    moduleCtor: Type<EventBusModule>,
    moduleConfig: EventBusModuleOptions,
  ): DynamicModule {
    return super.forRoot(moduleCtor, moduleConfig);
  }

  public static override forRootAsync(
    moduleCtor: Type<EventBusModule>,
    asyncModuleConfig: AsyncModuleConfig<EventBusModuleOptions>,
  ): DynamicModule {
    // @todo: need access to module options this module was registered with, 
    // in order to push to imports conditionally.
    return super.forRootAsync(moduleCtor, asyncModuleConfig);
  }
}
```

**Comment by underfisk** [comment]
@sheiman-pavlo I would recommend using the official dynamic module from Nestjs but i have a personal project that has an example on how you can access, let me know if this helps you: https://github.com/underfisk/nestjs-pusher/blob/3ca45bf1adce6e60bf8947e95451f15b526ffc29/src/pusher.module.ts#L41
