### ISSUE TITLE
RabbitSubscribe consume one message at a time

### ISSUE THREAD

**Issue by rebeccamcdougal** [golevelup/nestjs#634]
Is it possible to use RabbitSubscribe but only consume one message at a time? Currently it will receive multiple messages before the first is finished processing which is causing updating issues. I've tried it with and without queue options to specify a channel that has a prefetch count of 1.

**Comment by WonderPanda** [comment]
I believe this should already be working as intended assuming you set the prefetch count to 1. Do you have a reproduction we could look at to try and see if there's something specific about your setup?

**Comment by metalcamp** [comment]
Seconding prefetchCount set to 1.
Minimum reproduction repo would be nice.

**Comment by underfisk** [comment]
Closing until further reproduction is provided
