### ISSUE TITLE
RabbitMq unexpected message routing behaviour

### ISSUE THREAD

**Issue by amroczeK** [golevelup/nestjs#635]
### About
I am upskilling in Event Driven Architecture and created the following [basic ordering system](https://github.com/amroczeK/eda-rabbitmq-nestjs).

In all my services, I am using using [controllers](https://github.com/golevelup/nestjs/tree/master/packages/rabbitmq#usage-with-controllers) and enabled controller discovery.

### Issue
I have noticed that when the Order Service publishes a message to the topic exchange `await this.amqpConnection.publish('shop.topic', 'shop.order.created', orderData,);` with the desired routing key, unexpectidly the incorrect controller/RabbitSubscribe decorator receives the message, even though the decorator is bound with a different routing key. 

But if I swap the position of the controller & decorator, the message is consumed correctly.

```
@Controller()
export class InventoryServiceController {
  private readonly logger = new Logger(InventoryServiceController.name);

  constructor(private readonly inventoryService: InventoryService) {}

  // This controller/decorator is receiving the message instead of handleOrderCreated
  @RabbitSubscribe({
    exchange: 'shop.topic',
    routingKey: 'shop.inventory.update',
    queue: 'inventory',
  })
  async handleUpdateInventory(
    @RabbitPayload() inventoryData: UpdateInventoryDto,
  ): Promise<void> {
    this.logger.log(`Updating product: ${inventoryData.product_name}`);
  }

  @RabbitSubscribe({
    exchange: 'shop.topic',
    routingKey: 'shop.order.created',
    queue: 'inventory',
  })
  async handleOrderCreated(@RabbitPayload() data: any): Promise<void> {
    this.logger.log('handleOrderCreated() received');
    this.inventoryService.updateInventoryFromOrder(data);
  }
....
```

### Steps to reproduce
Simplly clone https://github.com/amroczeK/eda-rabbitmq-nestjs and follow the Installation and Usage steps in the README.

When you make the POST request, you will notice that the docker Logs Explorer extension / inventory service container logs outputs:

`Updating product: undefined` instead of `handleOrderCreated() received` and `Updating inventory based on order: ...`

**Any help and advice would greatily be appreciated! I am going to try and see if the issue is replicated when not using controller discovery and report back.**

**Comment by amroczeK** [comment]
@WonderPanda I have tested if it occurs in the service without enabling controller discovery/using controllers and the same thing occurs. The top level function using the @RabbitSubscribe decorator is always hit first even though the routing key doesn't match.

There is an architecture diagram in the github I linked describing what I am trying to achieve, but the RabbitMq shows a similar implementation in their diagram for the second consumer having two routing keys bound to the same queue.

https://www.rabbitmq.com/tutorials/tutorial-five-python.html

I would expect the rabbit mq package to handle directing the message to the function with the desired decorator.

EDIT:

I just noticed that without making any changes to my code, if I send one POST request from the client the Order service will publish

```
await this.amqpConnection.publish(
        'shop.topic',
        'order.created',
        orderData,
      );
```

Then the inventory service will route the message to the controller with
```
@RabbitSubscribe({
    exchange: 'shop.topic',
    routingKey: 'inventory.update',
    queue: 'inventory',
  })
```

But then when I send it the second time (with no changes), it will route to
```
@RabbitSubscribe({
    exchange: 'shop.topic',
    routingKey: 'order.created',
    queue: 'inventory',
  })
  async handleOrderCreated(@RabbitPayload() data: any): Promise<void> {
    this.logger.log('handleOrderCreated() received');
    this.inventoryService.updateInventoryFromOrder(data);
  }
```

Why are the messages being routed in a 'round-robin' fashion?

**Comment by amroczeK** [comment]
Disregard, this is due to my misunderstanding of RabbitMq and the docs. Seems that I have configured the inventory service to subscribe to the queue twice, creating a competing consumer pattern which would default to round robin.

>In the previous examples, both RPC and Pub/Sub would be using the Competing Consumer pattern by default through >the use of a named queue parameter. If running multiple instances of the application, each instance would bind to the >same named queue and receive the messages in a round robin fashion.

I will have to change it from doing round robin or handle the routing manually.

**Comment by MDalprato** [comment]
I'm having the same issue here.  @amroczeK  How did you fix it ? thanks a lot
