### ISSUE TITLE
Storage Module

### ISSUE THREAD

**Issue by tomerslice** [golevelup/nestjs#640]
Hey,
I saw your pub/sub module, and wanted to ask what about other kind of modules?
Like storage service, that can be gcp/s3/local.
If it is ok, I would like to add some services like those here.

**Comment by underfisk** [comment]
Hi @tomerslice , we currently have no intention of developing a storage module.
If you're willing to develop such module, it would also apply that someone will need to maintain it

**Comment by tomerslice** [comment]
I would like to add, and I can also maintain it.

**Comment by underfisk** [comment]
@tomerslice Feel free to propose a PR and I'll take a look 😄
