### ISSUE TITLE
Cannot disable RabbitMQ heartbeat

### ISSUE THREAD

**Issue by jarpoole** [golevelup/nestjs#647]
Currently `@golevelup/nestjs` uses `amqp-connection-manager` v3.x which has a bug preventing `connectionManagerOptions.heartbeatIntervalInSeconds` from being set to zero. This issue was fixed in 2022 upstream in https://github.com/jwalton/node-amqp-connection-manager/pull/236. This is a major issue because it prevents RabbitMQ from being used with long running jobs because the client will be disconnected. 

There are several candidate PRs for upgrading the dependencies like https://github.com/golevelup/nestjs/pull/601 and the older https://github.com/golevelup/nestjs/pull/459. After reading through the comments it doesn't seem like there are any major issues but if there are I am happy to help out.

As a work around for anyone else having issues with this, see https://github.com/golevelup/nestjs/issues/610 where it is mentioned that you can add `?heartbeat=0` to the end of the AMQP URI to fix the issue. This makes use of the tuning parameters which are documented in https://amqp-node.github.io/amqplib/channel_api.html#tuning-parameters

**Comment by underfisk** [comment]
#677 was merged and soon i a new version v4 will be available and hopefully fixes this issue
I'm closing as there's no action item here except bumping to v4 which is already performed, just waiting for a new release from WonderPanda
