### ISSUE TITLE
Cannot find module '@nestjs-plus/common'

### ISSUE THREAD

**Issue by ziazon** [golevelup/nestjs#65]
![image](https://user-images.githubusercontent.com/1675902/67912883-b050de00-fb61-11e9-887e-47c0b349bbf8.png)

The solution is to just install it, but figured either it should be a dep in this package's `package.json` file or specify in the docs to also install this module.

(originally posted this as a secondary issue in #58)

**Comment by WonderPanda** [comment]
@jubairsaidi What version of @nestjs-plus/rabbitmq are you currently using?

**Comment by WonderPanda** [comment]
@jubairsaidi Thanks for bringing attention to this. I'm surprised that it had gone unnoticed for a while. I've published a new version 1.4.3 of @nestjs-plus/rabbitmq that fixes this issue

**Comment by ziazon** [comment]
awesome! thanks!
