### ISSUE TITLE
createMock return type is object instead of method's return type

### ISSUE THREAD

**Issue by vahidvdn** [golevelup/nestjs#650]
I have this in my testing:

```ts
{
  provide: CheckOpenAlertHandlerService,
  useValue: createMock<CheckOpenAlertHandlerService>(),
},
```

This is my class:

```ts
@Injectable()
export class CheckOpenAlertHandlerService extends AbstractSituationHandler {
  public handle(data: any): boolean {
    console.log('open alert');

    const isOpenAlert = false;
    if (isOpenAlert) {
      return false; // Condition not met, stop processing
    }
    return super.handle(data); // Condition met, pass to the next handler
  }
}
```

As you see, the return type of `handle` is boolean. But in testing:

```ts
checkOpenAlertHandlerService = app.get<CheckOpenAlertHandlerService>(
  CheckOpenAlertHandlerService,
);

// test section
it('should handle situation', () => {
  const res = checkOpenAlertHandlerService.handle(false);
  console.log(res); // result is: {}
});
```

**Comment by vahidvdn** [comment]
I found that I need to specify the return type explicitly:

```ts
useValue: createMock<CheckOpenAlertHandlerService>({
  handle: jest.fn().mockReturnValue(true), // Specify the return type as boolean
}),
```

Is it really needed? Or am I missing something?

**Comment by WonderPanda** [comment]
You shouldn't need to manually put a jest.fn() inside of handle. It should automatically be wrapped for you if you just provide a regular lambda function it should have the right types.

Try this
```
useValue: createMock<CheckOpenAlertHandlerService>({
  handle: () => true
}),
```

**Comment by vahidvdn** [comment]
@WonderPanda My expectation was that the mocked version of `CheckOpenAlertHandlerService` should be the same type (a function called `handle` that has a boolean return type), but it's an object and I need to define it explicitly.

**Comment by WonderPanda** [comment]
> @WonderPanda My expectation was that the mocked version of `CheckOpenAlertHandlerService` should be the same type (a function called `handle` that has a boolean return type), but it's an object and I need to define it explicitly.

This isn't possible because Typescript types aren't known at runtime. The way this library works is that unless you specify a value it will always return `jest.fn` when you access a properly that has not been explicitly mocked.

Its up to you to provide specific behavior for properties and methods that you care about
