### ISSUE TITLE
[RabbitMQ] create queues without consumer

### ISSUE THREAD

**Issue by fermentfan** [golevelup/nestjs#659]
Hi,
I am currently trying to send out messages with a delay by leveraging the TTL + DLQ pattern as described here:

https://github.com/golevelup/nestjs/issues/138#issuecomment-853936061

At the moment I solely rely on queue creation by this dependency, which I really love! But to follow the pattern one must create a queue without any handler added to it where the messages just wait until their TTL hit. Sadly I think this is not possible? I'd have expected that one could define queues with options like DLQ next to the exchanges in the module definition. It would be so cool if that was possible :)

**Comment by WonderPanda** [comment]
It would honestly be pretty easy to get this functionality implemented but I'll be honest I haven't used RabbitMQ in so many years now that I have no motivation. I bet you it could be a really easy contribution for you though and you'll get your face here: https://github.com/golevelup/nestjs#contributors-

**Comment by papalardo** [comment]
My config:

```js

export const dlq = (queue: string) => queue + '.dlq';
export const dlx = (exchange: string) => exchange + '.dlx';

@Global()
@Module({
  providers: [],
  imports: [
    RabbitMQModule.forRootAsync(RabbitMQModule, {
      useFactory: () => ({
        uri,
        exchanges: [
          {
            name: RMQ_EXCHANGES.WORKERS,
            type: 'direct',
          },
          {
            name: dlx(RMQ_EXCHANGES.WORKERS),
            type: 'direct',
          },
        ],
        channels: {
          [RMQ_QUEUES.CAMPAIGN_DISPATCHED]: {
            prefetchCount: 1,
          },
        },
        defaultSubscribeErrorBehavior: MessageHandlerErrorBehavior.NACK,
      }),
    }),
  ],
  exports: [RabbitMQModule],
})
export class RabbitMqModule implements OnModuleInit {
  constructor(private readonly amqpConnection: AmqpConnection) {}

  async onModuleInit() {
    await this.amqpConnection.channel.assertQueue(dlq(RMQ_QUEUES.CAMPAIGN_DISPATCHED), {
      durable: true,
    });

    await this.amqpConnection.channel.bindQueue(
      dlq(RMQ_QUEUES.CAMPAIGN_DISPATCHED),
      dlx(RMQ_EXCHANGES.WORKERS),
      dlq(RMQ_QUEUES.CAMPAIGN_DISPATCHED),
    );
  }
}
```
