### ISSUE TITLE
Error Channel ended, no reply will be forthcoming

### ISSUE THREAD

**Issue by PedroCamargo-dev** [golevelup/nestjs#661]
Hey,
I'm having a problem starting my api, it's giving me the error "Channel ended, no reply will be forthcoming", which appears to be something from amqplib, this lib is out of date in nestjs-rabbitmq
`
service/node_modules/@golevelup/nestjs-rabbitmq/node_modules/amqplib/lib/channel.js:201
    r(new Error("Channel ended, no reply will be forthcoming"));
`

**Comment by metalcamp** [comment]
Experiencing same issue. Can you share your config?

**Comment by PedroCamargo-dev** [comment]
why config?
