### ISSUE TITLE
Multiple Stripe instances with different Webhook endpoints

### ISSUE THREAD

**Issue by soylomass** [golevelup/nestjs#665]
Hi, I'm migrating a customer database from a Stripe account to a new one, but I'll do it in batches. Meanwhile, I want both Stripe accounts to both work, so I need both of them to have a webhook configured on my API.
I tried creating two modules both instancing a StripeModule, with different keys and a different controllerPrefix.
But even if the logs show "Registering webhook" once per each module, only one endpoint is created. It's like only one controllerPrefix is considered.

Is this a bug or a design choice?
Is there any way to achieve what I want?

**Comment by WonderPanda** [comment]
It would definitely be possible to achieve this but I haven't had a lot of free time to work on new features for a while. I'd definitely welcome the contribution though if you want to help implement it
