### ISSUE TITLE
Feature (rabbitmq): persistent reply-to responses

### ISSUE THREAD

**Issue by ilyalatt** [golevelup/nestjs#666]
Hello. [There is no way](https://github.com/golevelup/nestjs/blob/be88a40d5b4c988d2b5e855b446f7a8e3b43b9bf/packages/rabbitmq/src/amqp/connection.ts#L553C25-L553C25) to mark a reply message to be persistent. Looks like it can be fixed with addition of `replyToDeliveryMode` to `MessageHandlerOptions`.

**Comment by underfisk** [comment]
@ilyalatt Would you be able to contribute to that change? I'd be happy to review it!

**Comment by ilyalatt** [comment]
@underfisk Sure!

**Comment by ilyalatt** [comment]
@underfisk https://github.com/golevelup/nestjs/pull/684

**Comment by ilyalatt** [comment]
@underfisk Thank you for the quick review :)
