### ISSUE TITLE
Initializing Rabbit Module creates random queues

### ISSUE THREAD

**Issue by shreyassood** [golevelup/nestjs#667]
On initializing a module with a queue specified, the library creates random queues if `createQueueIfNotExists` is on.

This happens at https://github.com/golevelup/nestjs/blob/be88a40d5b4c988d2b5e855b446f7a8e3b43b9bf/packages/rabbitmq/src/amqp/connection.ts#L304-L305 within the setupQueuesWithBindings method. 

The setupQueue method expects a subscriptionsOptions object of type `MessageHandlerOptions` but is passed in an object of type `RabbitMQQueueConfig`. This object does not have the queue property https://github.com/golevelup/nestjs/blob/be88a40d5b4c988d2b5e855b446f7a8e3b43b9bf/packages/rabbitmq/src/amqp/connection.ts#L671-L672 and causes Rabbit to initialize a queue with a [random name] (https://www.rabbitmq.com/queues.html#server-named-queues).

<img width="964" alt="Screenshot 2023-12-08 at 5 45 28 PM" src="https://github.com/golevelup/nestjs/assets/2962613/9ca0b86c-a724-4dc3-ab07-bf606e1a046f">

Also on a side note: should assertQueue not create a queue at https://github.com/golevelup/nestjs/blob/be88a40d5b4c988d2b5e855b446f7a8e3b43b9bf/packages/rabbitmq/src/amqp/connection.ts#L304-L305 regardless anyway (`createQueueIfNotExists`) in this case shouldn't matter?

**Comment by liudichen** [comment]
I also encountered this issue, and it's not just the queue attribute, but also the queueOptions attribute with different names in the two configurations

maybe should modify this line:
https://github.com/golevelup/nestjs/blob/be88a40d5b4c988d2b5e855b446f7a8e3b43b9bf/packages/rabbitmq/src/amqp/connection.ts#L302

to
```
this.setupQueue({...configuredQueue,queue: configuredQueue.name,queueOptions:configuredQueue.options}, channel)
```

**Comment by underfisk** [comment]
The next version shall include the fix for this, bumping here for @WonderPanda

**Comment by huantaoliu** [comment]
nice

**Comment by shreyassood** [comment]
Awesome, thanks for working on this!

**Comment by underfisk** [comment]
> Awesome, thanks for working on this!

All the merit goes to @ttshivers ! He's doing an amazing job helping out

**Comment by trickaugusto** [comment]
Hello everyone!

I had the same problem, but I used version 5.0.0 and it didn't solve the problem...
Has this gone to production?
