### ISSUE TITLE
Connection retry?

### ISSUE THREAD

**Issue by murbanowicz** [golevelup/nestjs#67]
Hi,
It is a really nice module but it is missing connection retry on init or on error. 
Are you interested in implementing this feature?

**Comment by WonderPanda** [comment]
Hey @murbanowicz I think it makes sense for this to be natively supported by the module. How do you currently implement retry/reconnection behavior in your RabbitMQ connected applications? Maybe if you share a snippet I can use that as a starting point

**Comment by murbanowicz** [comment]
Hi,

I've done it in fairly simple way:

```js
async connectToAmqp(retry = 1): Promise<amqplib.Connection> {
    if (retry > this.config.maxRetries) {
      this.logger.error('Maximum AMQP connection retries reached!');
      throw new Error('Maximum AMQP connection retries reached!');
    }
    this.logger.debug(`Connecting to AMQP. ${retry} try.`);
    try {
      const connection = await amqplib.connect(this.config.uri);
      connection.on('close', async () => {
        this.readiness = false;
        this.logger.warn('AMQP disconnected. Will try to reconnect...');
        this.connection = await this.connectToAmqp();
      });
      this.readiness = true;
      return connection;
    } catch (e) {
      this.logger.debug(`Could not connect to AMQP.`, e);
      await waitFor(this.config.reconnectDelay * retry);
      return this.connectToAmqp(retry + 1);
    }
  }
```

**Comment by WonderPanda** [comment]
Thanks for the example code, I'll try to incorporate improved retry and connection logic into the library in the coming week

**Comment by azuker** [comment]
I recommend you consider incorporating amqp-connection-manager - https://www.npmjs.com/package/amqp-connection-manager

**Comment by azuker** [comment]
I created a PR for that if you're interested - https://github.com/golevelup/nestjs/pull/80

**Comment by WonderPanda** [comment]
Connection management is now possible thanks to amqp-connection-manager and the awesome contributions from @azuker
