### ISSUE TITLE
RabbitMQ publish doesn't take advantage of amqp-connection-manager's reliable publish

### ISSUE THREAD

**Issue by ttshivers** [golevelup/nestjs#673]
The rabbitmq package's `publish` implementation calls `publish` on a raw `ConfirmChannel` instead of the `ChannelWrapper` provided by  `amqp-connection-manager`.

Since it's not using the `ChannelWrapper`, it's missing out on all the reliability features that `amqp-connection-manager` provides for publishing messages.

Was this an intentional decision to not use the `ChannelWrapper` ?

https://github.com/golevelup/nestjs/blob/1891b3286cb620d809e9d00f9a56d7805b846607/packages/rabbitmq/src/amqp/connection.ts#L612-L627

Instead of using `this._channel` there, `this._managedChannel` could be used instead which is the `ChannelWrapper`

**Comment by underfisk** [comment]
@ttshivers If you feel confident about this change and can provide test coverage to assert that it works as intended I'll be happy to review and merge. 
I don't know what the reason was behind not to use `ChannelWrapper` but from your explanation it seems logical to use so

**Comment by ttshivers** [comment]
Fixed by https://github.com/golevelup/nestjs/pull/678
