### ISSUE TITLE
QueryParams are missing AssertQueue options

### ISSUE THREAD

**Issue by elucidsoft** [golevelup/nestjs#69]
The following items should be added to the QueryParams: 

`interface AssertQueue {
        exclusive?: boolean;
        durable?: boolean;
        autoDelete?: boolean;
        arguments?: any;
        messageTtl?: number;
        expires?: number;
        deadLetterExchange?: string;
        deadLetterRoutingKey?: string;
        maxLength?: number;
        maxPriority?: number;
    }`

**Comment by WonderPanda** [comment]
Fixed in `@nestjs-plus/rabbitmq` version 1.4.4
