### ISSUE TITLE
Can not npm install on a new project due to reflect-metadata peerDependency

### ISSUE THREAD

**Issue by ntheofanidis-entropy-studios** [golevelup/nestjs#698]
Can not npm install golevelup/nestjs-rabbitmq on a new project due to reflect-metadata peerDependency not being the one fixed in the github repo, so i end up getting "Could not resolve dependency" Errors, just letting you guys know

**Comment by underfisk** [comment]
@ttshivers Does the PR that i merge regarding support v2 will fix the issue?

**Comment by ntheofanidis-entropy-studios** [comment]
@underfisk https://github.com/golevelup/nestjs/pull/695 is the one that containes the fix and it is already merged, but the change is not on https://www.npmjs.com/package/@golevelup/nestjs-rabbitmq/v/5.0.0

**Comment by underfisk** [comment]
@ntheofanidis-entropy-studios It requires a release to be performed and i don't have the permissions to do so :/

**Comment by ntheofanidis-entropy-studios** [comment]
@underfisk no worries, i just wanted to inform you guys

**Comment by underfisk** [comment]
@WonderPanda Could we have a minor release for rabbitmq which brings #695 ?

**Comment by WonderPanda** [comment]
Just published @golevelup/nestjs-rabbitmq@5.1.0
