### ISSUE TITLE
Return information about the Containing Module from the Discovery Service

### ISSUE THREAD

**Issue by WonderPanda** [golevelup/nestjs#7]
Currently the DiscoveryService provides a convenient API for being able to scan through a NestJS app's dependencies to find matching Controllers/Providers and their method handlers. There are situations where it would be useful to also surface information about the module that these items were discovered inside of.

As part of this change we should also reduce the amount of information being returned from Discovery such that it doesn't expose all the innards of the InstanceWrapper. The API should return:
- handlers
- controllers/providers (both the constructed instance from the DI container and the Constructor Function currently called metatype)
- reflect metadata that was searched for
- the name of the controller/provider

**Comment by WonderPanda** [comment]
Closed by #12

**Comment by victordidenko** [comment]
Thank you!
Also I've created #13 for documentation, I should have look through commits to know, what was changed in new version :)

**Comment by yumauri** [comment]
↑ that is my business account :)
