### ISSUE TITLE
rabbitmq: binding a queue to exchange without a routingKey

### ISSUE THREAD

**Issue by melonges** [golevelup/nestjs#727]
example from rabbitmq library [link](https://www.rabbitmq.com/tutorials/tutorial-three-javascript#bindings)

**Comment by underfisk** [comment]
@melonges Could you provide an example/reproduction? Is this a feature that's missing or an adjust that has to be made?

**Comment by melonges** [comment]
as I understand it, it's the missing of functionality. I can't bind queues to exchanges

**Comment by underfisk** [comment]
I see, if you'd like to contribute with the missing feature I would appreciate :pray:

**Comment by kasir-barati** [comment]
@underfisk I think this should have been already implemented. Related PR and issue:

- https://github.com/golevelup/nestjs/issues/786
- https://github.com/golevelup/nestjs/pull/794

Or am I mistaken @melonges?

**Comment by underfisk** [comment]
@kasir-barati It was implemented but we haven't yet released it. There's a blocked with the pnpm/lerna migration that we're solving to unblock publishing

**Comment by melonges** [comment]
> @underfisk I think this should have been already implemented. Related PR and issue:
> 
> * [`ERROR [AmqpConnection] Received message with invalid routing key:` + headers exchange #786](https://github.com/golevelup/nestjs/issues/786)
> * [fix(rmq): allow pattern to contain empty strings for exact/literal matching  #794](https://github.com/golevelup/nestjs/pull/794)
> 
> Or am I mistaken @melonges?

I didn't describe my issue well and I don't remember the exact problem. But based on the PR description it seems to be done
