### ISSUE TITLE
ts-jest: Cannot create mock of a class which has private dependencies in constructor

### ISSUE THREAD

**Issue by vc-bhanudatsinh** [golevelup/nestjs#728]
Error: Argument of type 'typeof PermissionGuard' is not assignable to parameter of type 'PartialFuncReturn<{ prototype: { readonly reflector: ...; readonly rolePermissionService: ...; canActivate: ...; }; }>'.
  Types of property 'prototype' are incompatible.
    Type 'PermissionGuard' is not assignable to type 'DeepPartial<{ readonly reflector: Reflector; readonly rolePermissionService: RolePermissionService; canActivate: (context: ExecutionContext) => Promise<...>; }>'.
      Property 'reflector' is private in type 'PermissionGuard' but not in type 'DeepPartial<{ readonly reflector: Reflector; readonly rolePermissionService: RolePermissionService; canActivate: (context: ExecutionContext) => Promise<...>; }>'
      
 ```
  @Injectable()
export class PermissionGuard implements CanActivate {
  constructor(
    private readonly reflector: Reflector,
    private readonly rolePermissionService: RolePermissionService
  ) {}
  }
```

![image](https://github.com/golevelup/nestjs/assets/130746446/a4f49677-6f11-43b3-832d-3ffe20285b73)

**Comment by mtander** [comment]
I am getting the same problem.

**Comment by barraponto** [comment]
did you try writing it like this?

```typescript
.useValue(createMock<PermssionGuard>())
```
