### ISSUE TITLE
Stripe Test Webhook

### ISSUE THREAD

**Issue by fermentfan** [golevelup/nestjs#731]
I am currently looking into how one should use the test mode in Stripe for a proper setup, but when configuring it I've spotted that you're only able to configure secrets for the Account & Connect webhooks. Not for a third `test` webhook.

**Comment by matheo** [comment]
This should be closed, thanks for your PR @fermentfan

**Comment by matheo** [comment]
@fermentfan I was able to run my webhook locally but in the Stripe Dashboard the test endpoint seems to return `403`. I imagine it has something to do with the `stripe-signature`, have you experienced some problem with it too?

Edit: nvm, it was a configuration of the devops -_-

**Comment by noook** [comment]
Just a question, as I'm deploying to production right now, I don't understand the use case for this feature.

Are you using a single server instance in order to receive both your live and test events ?

If so, how would you choose the right secret key for test or livemode ?
