### ISSUE TITLE
Stripe v15

### ISSUE THREAD

**Issue by matheo** [golevelup/nestjs#746]
Hi @WonderPanda! First, thanks for the great NestJS stuff!
I wonder how difficult would be to upgrade to [Stripe v15](https://github.com/stripe/stripe-node/releases/tag/v15.0.0) with the changes of the pinned API version to `2024-04-10`.

I want to help with the jump so I wonder if previous upgrades thrown some type errors to fix and that's it?
or it needs deeper checks in the API Upgrade Guide?

Thanks in advance!

**Comment by WonderPanda** [comment]
I haven't been keeping up to date with what's new in the Stripe API so I think it would be awesome if someone could review the upgrade guides and do some local testing to make sure its all working

**Comment by aarmful** [comment]
this definitely needs some work - was trying it today with no luck in terms of making it work. was using a self-made solution prior to this.

**Comment by vinialbano** [comment]
Any updates on this? There's v16 now.

**Comment by underfisk** [comment]
If anyone can help by contributing to the update of Stripe to v15/v16 I'll be happy to review (unfortunately I haven't used the Stripe lib for awhile and don't have proper context).

**Comment by underfisk** [comment]
If @WonderPanda can release a major version, stripe v16 should be included in the next major release.
https://github.com/golevelup/nestjs/pull/796

I have tested it, works fine but I don't have any "good" setup to replicate it. If any issue is encountered I will collect that piece of feedback and eventually add e2e tests to help preventing regressions
