### ISSUE TITLE
ts-vitest: typings are incorrect for vitest 2.x

### ISSUE THREAD

**Issue by JaakkoLipsanen** [golevelup/nestjs#770]
With `vitest` 2.x the types for `DeepMocked` are incorrect.

For example, with `const mockTest: DeepMocked<{ test: () => void }>`, the typeof `mockTest.test` is `any` and there will be no auto-completion for the mock helper functions.

Reason seems to be that signature of `MockInstance` has been changed from `export interface MockInstance<TArgs extends any[] = any[], TReturns = any>` to `export interface MockInstance<T extends Procedure = Procedure>`, see here: https://github.com/vitest-dev/vitest/blob/72d498002c9689a5e557457b0184dd9a7ad5e9b1/docs/guide/migration.md#simplified-generic-types-of-mock-functions-eg-vifnt-mockt

**Comment by underfisk** [comment]
@JaakkoLipsanen Would you be okay on having a PR with the proper fix for ts-vitest?

**Comment by underfisk** [comment]
I have investigated this and we do not support vitest 2.x yet only `1.x.x` 
We'll need to implement it, I don't have the bandwidth now but if you're willing to help I'll happily review the PR
