### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by kdi-1** [golevelup/nestjs#78]
Hi,
It is a really nice lib. Thank you! 

Is it possible to use multiple connections to send/receive  messages? If so I'd appreeciate it isf someone give an example of configuration and using.

**Comment by WonderPanda** [comment]
Hey @kdi-1. There isn't currently an option for managing multiple connections but I can see that being a useful addition to the library. I'll take a look at adding this in a future release.

**Comment by kdi-1** [comment]
Now I solved this by creating a _child class_ based on RabbitMQModule
`class RabbitMQModule1 extends RabbitMQModule  {}`
**feature-1.module.ts**
```
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';

class RabbitMQModuleFeature1 extends RabbitMQModule  {} 

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModuleFeature1, {
      exchanges: [
        {
          name: 'exchange1',
          type: 'topic'
        }
      ],
      uri: 'amqp://rabbitmq:rabbitmq@localhost:5672/vhost1,
      connectionInitOptions: { wait: false }
    })
  ]
})
export class RabbitExampleModule1 {}
```
**feature-2.module.ts**
```
import { RabbitMQModule } from '@golevelup/nestjs-rabbitmq';

class RabbitMQModuleFeature2 extends RabbitMQModule  {} 

@Module({
  imports: [
    RabbitMQModule.forRoot(RabbitMQModuleFeature2, {
      exchanges: [
        {
          name: 'exchange2',
          type: 'topic'
        }
      ],
      uri: 'amqp://rabbitmq:rabbitmq@localhost:15672/vhost2,
      connectionInitOptions: { wait: false }
    })
  ]
})
export class RabbitExampleModule2 {}
```

**Comment by Ponjimon** [comment]
@WonderPanda Has there ever been an update to this? We want to separate workload and thus require having more than one connection. The way @kdi-1 proposed seems a bit too hacky; I'd love to see named connections, similar to how `nestjs-amqp` does it.
