### ISSUE TITLE
[feature request] default handler config

### ISSUE THREAD

**Issue by y-nk** [golevelup/nestjs#782]
I'm having a service which uses only one big queue and exchange, and i'm having a ton of subscribers behind (i can't subscribe to `*` and i want to keep good granularity at subscription)

i'm currently leveraging this:
https://github.com/golevelup/nestjs/blob/eae2431fe2fc6c21eceb89aef494d329e53e025f/packages/rabbitmq/src/rabbitmq.module.ts#L247

as for my config is:

```js
{
  handlers: {
    ['']: {
      exchange: defaultExchange,
      queue: defaultQueue,
      queueOptions: defaultQueueOptions,
    }
  }
}
```

which works ok but feels a little hacky. any change to provide a `defaultHandlerConfigName` prop to have explicit declaration of the name rather than using `''`?

I can propose a PR if necessary

**Comment by WonderPanda** [comment]
Yeah this seems like a good addition. Feel free to submit a PR

**Comment by y-nk** [comment]
@WonderPanda i will provide PRs to my 2 proposals and also a 3rd one. if possible we can wait the 3 PRs to make a release.
