### ISSUE TITLE
[feature request] Subscribe `routingKey` as `string | string[]`

### ISSUE THREAD

**Issue by y-nk** [golevelup/nestjs#783]
We can't do enum/regex based routing in rabbitmq, so we have no choice but to subscribe individually to many events with many subscribers.

I would like to know if we could add the support for `@Subscribe({ routingKey })` to allow multiple routing keys, so that we can eventually compensate the lack of enum based routing in rmq.

I can propose a PR if necessary

**Comment by WonderPanda** [comment]
Contributions are definitely welcome!

**Comment by y-nk** [comment]
I have badly looked at the `routingKey` but it is indeed a `string | string[]` so i'll be closing this issue. @WonderPanda i already have submitted 2 other PRs nonetheless 🙏
