### ISSUE TITLE
`ERROR [AmqpConnection] Received message with invalid routing key:` + headers exchange

### ISSUE THREAD

**Issue by kasir-barati** [golevelup/nestjs#786]
I am getting this weird error message when I am trying to get my app send messages using headers exchange. Do you have any idea why it is happening?

```cmd
ERROR [AmqpConnection] Received message with invalid routing key:
```

[Here is a repo for this issue to reproduce the bug if we can call it a bug](https://github.com/kasir-barati/nestjs-headers-exchange-rabbitmq).

**Comment by kasir-barati** [comment]
I read [this issue](https://github.com/golevelup/nestjs/issues/343) but still I am lost.

**Comment by kasir-barati** [comment]
According to my understanding from your codebase:

1. [Here](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L325) is where you're trying to configure queues.
2. [Here](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L728)  is where you actually are binding queue to the passed configuration. And this is equivalent to [this piece of code in amqplib](https://github.com/amqp-node/amqplib/blob/main/examples/headers.js#L25-L29) and I believe that amqp-connection-manager does it in the same fashion.
3. And finally [here](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L546) is where you're defining how a method annotated with `@RabbitRPC` should be bound to a queue.

And finally I am not sure how but [this helper function](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L566) is returning `false`, thus I get that error which does not make sense to me at all.

**Comment by kasir-barati** [comment]
So after I debugged your lib, it seems that [you've forgotten to check that if pattern is empty string you should not return `false`](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/utils.ts#L5) right away.

![Debugged matchesRoutingKey](https://github.com/user-attachments/assets/9c81ada4-5bef-4d9c-9208-46420675b017)

Maybe first check if the routing is empty string as well, I think this would serve our purpose much much better:

```ts
if (Array.isArray(pattern) && pattern.length === 0) {
  return false;
}
if (pattern === undefined || pattern === null) {
  return false;
}
```

And then the rest of the code would work just fine.

BTW I would be happy to open a PR for this too if you agree with my approach.

> [!NOTE]
> I used the same repo that I shared in the original message to debug this behavior. But I guess at this point it does not make much difference since it is clear why it is happening.
>
> The other note is that according to the RabbitMQ we should not validate routingKey if it is a header exchange:
>
> > Headers exchanges ignore the routing key attribute. &mdash; [Ref](https://www.rabbitmq.com/tutorials/amqp-concepts#exchange-headers)

**Comment by kasir-barati** [comment]
Cannot wait to hear from you back. Share your thoughts and comments on this subject objectively.

**Comment by underfisk** [comment]
@kasir-barati I think you're use-case makes sense where an empty string is provided but I haven't encountered such thing. The helper has the assumption that you either have a key defined or not but maybe we can make it more "bulletproof" by checking its size as you suggest.
Feel free to create a PR with this but also include test coverage as i'd like to be certain that there's no regression

**Comment by underfisk** [comment]
I have provided a fix here, https://github.com/golevelup/nestjs/pull/794
It will be available in the next release

**Comment by kasir-barati** [comment]
Thanks @underfisk. I love that

**Comment by echonabin** [comment]
Is this fixed cause i'm getting the similar issue when working with exchanges and queues. Even if i provide same exchange and routing key like on receiver side 

```typescript
  @RabbitRPC({
    exchange: Exchanges.DIRECT.USER,
    routingKey: UserManagementEvents.RPC_CHECK_USER_EXISTS,
    queue: QueueNames.USER_QUEUE,
  })
```

And on sender side 
```typescript
async checkUserExists(email: string, idempotencyKey: string) {
    return firstValueFrom(
      this.userClient.request<boolean, CheckUserExistsDto & BaseEventDto>(
        Exchanges.DIRECT.USER,
        UserManagementEvents.RPC_CHECK_USER_EXISTS,
        { email, idempotencyKey }
      )
    );
  }
```

receiver is giving me 

`2025-04-11T12:16:53.996Z [AmqpConnection] error: Received message with invalid routing key: get.user.exists`


This is weird cause when i see my exchange it's binding properly with queue as well.

<img width="837" alt="Image" src="https://github.com/user-attachments/assets/aba9b238-ccb7-4261-98e1-098271628f2d" />

Obviously the documentation of this library is poor and literally hard to integrate with.

**Comment by echonabin** [comment]
@kasir-barati did you manage to fix the issue ? Or is there something i should be aware of when dealing with RPC with this library i don't know. I can confirm that messages do reach the service but the `@RabbitRPC` don't seem to recognize it somehow.

Just putting it out there yes i have set 

` enableControllerDiscovery: true`
