### ISSUE TITLE
Automate release of new package versions

### ISSUE THREAD

**Issue by y-nk** [golevelup/nestjs#789]
sorry for adding this here, i tried to ask on discord too.
when can we hope a release for the latest changes? how to make one? thanks a lot.

**Comment by underfisk** [comment]
@WonderPanda Can we have a release?

**Comment by WonderPanda** [comment]
Successfully published:
 - @golevelup/nestjs-rabbitmq@5.5.0
 - @golevelup/ts-jest@0.5.6

I'd love to automate this but haven't had the time to dedicate to setting it up to happen automatically

**Comment by y-nk** [comment]
@WonderPanda i'll see if i can propose a PR for this later on :)
