### ISSUE TITLE
instance properties of discovered controller are undefined

### ISSUE THREAD

**Issue by zarv1k** [golevelup/nestjs#81]
Hi!

Have found such a strange issue: instance properties of discovered controllers are `undefined` in discovery results.

I think that it can happen because controllers discovery is in the discovery service constructor, so it should be delayed at least to the finish of the app bootstraping process. Moreover, discovery process could be implemented in lazy way.

I'll prepare PR for that shortly.

Thanks.

**Comment by WonderPanda** [comment]
This is a great find thanks for taking the time to report and fix!

**Comment by WonderPanda** [comment]
@zarv1k new packages have been published

Changes:
 - @golevelup/nestjs-discovery: 2.2.0 => 2.2.1
 - @golevelup/nestjs-rabbitmq: 1.7.0 => 1.7.1
