### ISSUE TITLE
ts-jest 0.5.1 regression

### ISSUE THREAD

**Issue by JonasFaure** [golevelup/nestjs#843]
I noticed a changed of behaviour when upgrading `@golevelup/ts-jest` from 0.5.0 to 0.5.1

Given the following piece of code 
```js 
import { createMock } from './mocks';

interface TestInterface {
  func: () => Promise<Counter>;
}

type Counter = {
  count: number;
};

describe('regression', () => {
  it('showcases the regression', async () => {
    expect.hasAssertions();
    const testmock = createMock<TestInterface>();

    const c = await testmock.func();
    try {
      c.count < 0;
    } catch (e) {
      if (e instanceof Error)
        expect(e.message).toBe('Cannot convert object to primitive value');
    }
  });
});
```

On version 0.5.0 `c.count < 0` doesn't throw.
<img width="682" alt="Screenshot 2024-10-07 at 13 30 53" src="https://github.com/user-attachments/assets/00ccc326-811d-4b8d-9fd0-a6cb9a4058aa">

Whereas on version 0.5.1 `c.count < 0` throws with a TypeError. This behaviours remains with the latest release as well.
<img width="1037" alt="Screenshot 2024-10-07 at 13 32 09" src="https://github.com/user-attachments/assets/b7bb5bf8-6a5f-4d2f-8617-f63249cbd66f">

Seeing it was introduced through a "patch" bump I wonder if this new behaviour is meant to stay or if it was introduced by mistake ?

**Comment by underfisk** [comment]
@JonasFaure Thanks for reporting this! Unfortunately i don't have that much time to switch contexts and provide a quick fix, if you're able to help us out that would be appreciated :pray:

**Comment by JonasFaure** [comment]
I wanted to have confirmation that it was a change you didn't want to keep before, I'll give it a try 👍

**Comment by underfisk** [comment]
Based on your replication, it would make sense to be able to convert. I don't see why it shouldn't, something was added that provoked this regression.
If we end up having a fix I would kindly request to add test coverage to avoid a regression

**Comment by JonasFaure** [comment]
My understanding so far : 

`createRecursiveMockProxy` used to wrap its returned value in a `jest.fn(()=>proxy)`.
The new implementation returns the proxy straight away, and proxies a `jest.fn()` instance instead of an empty object `{}`.

The previous implementation meant that when 
``` 
interface Foo {
  prop: number 
}
const m = createMock()
m.prop // <- is a jest.fn wrapped Proxy 
m.prop < 0 // <- m.prop gets implicitly casted to a string which is then trivially compared to a number 
``` 

Whereas the one returns a Proxy object which prevents such implicit casts, hence the behaviour changed I noticed.

I'm not too familiar with Proxy and such, so I'm still figuring out why https://github.com/golevelup/nestjs/pull/752/files required this change in the first place so I don't re-create an old issue by addressing this one 🙈

**Comment by JonasFaure** [comment]
version 0.5.0 used to recursively build `new Proxy({}, ...)` objects wrapped in `jest.fn(()=>proxy)`.
we know set a `new Proxy(t, ...)` where `const t = jest.fn()`.

Hence the different I noticed in my example, where `c.count` was either understood as a Proxy on a function, or a function directly.
I'll open a PR to support implicit conversion of proxy object ⏳

**Comment by JonasFaure** [comment]
Hi @underfisk 👋 

I couldn't find information regarding when/how releases are planned, do you know when the change attached to this issue will be published on npm ? 🙏

**Comment by rbnayax** [comment]
Previous behavior was wrong and as such the breaking changes are a result of  bug fix, not regression

**Comment by coler-j** [comment]
Still hitting this error all over the place in `0.6.2`

**Comment by podplatnikm** [comment]
Still an error in 0.6.2

**Comment by froddd** [comment]
Still an issue in `0.7.0`.
