### ISSUE TITLE
binding multiple routing key to one queue by decorating a handler with multiple `@RabbitRPC`

### ISSUE THREAD

**Issue by kasir-barati** [golevelup/nestjs#846]
Hey guys,

I've been trying to come up with a way of doing what the title of this issue says but no luck. In RabbitMQ it works since in RabbitMQ management panel you can literally add more bindings:

![add binding](https://github.com/user-attachments/assets/99326f96-2d6d-4aea-98e5-2d451936b614)

But even though I coded it to bind multiple routing key to the same queue it is not working. You can see reproduce it [here](https://github.com/kasir-barati/docker/tree/main/docker-compose-files/rabbitmq/topic-nestjs).

When you send a delete request to the delete endpoint it just logs "Send parting gift..." and payload, but not "Logging info...". While it works perfectly fine for when I am sending a message with this routing key: `user.created`. It logs "Logging info...", and "Sending email...".

So I am suspecting that it is just ignoring [the rest of `@RabbitRPC` decorators](https://github.com/kasir-barati/docker/blob/main/docker-compose-files/rabbitmq/topic-nestjs/src/rabbitmq/rabbitmq.service.ts#L30-L39). Except the first one of course.

Is it possible to bind multiple routing keys to one queue in topic exchange with `@golevelup/nestjs-rabbitmq`?

**Comment by kasir-barati** [comment]
Here is a working example with pure amqplib: https://github.com/kasir-barati/awesome-js-ts/blob/main/src/rabbitmq/topic-exchange/logger-receiver.ts#L21-L31

As you can see it should have been possible but for some reason this lib cannot do it.

**Comment by WonderPanda** [comment]
This is definitely possible with an update to the library. The decorator most likely needs to be updated to accept a single config or an array of configs in order to make this work. Otherwise the metadata will just be overwritten by subsequent application of the decorator. Are you interested in contributing this functionality?

**Comment by kasir-barati** [comment]
Hmm, yup you're right about that ("metadata will just be overwritten"). BTW I realized that it is already implemented, I just failed to notice it: https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/rabbitmq.interfaces.ts#L90
