### ISSUE TITLE
Handler cannot receive messages published in topic exchange in a microservice architecture

### ISSUE THREAD

**Issue by kasir-barati** [golevelup/nestjs#851]
Hey folks,

I am trying to send a message from driver microservice to audit-log in NestJS with `@golevelup/nestjs-rabbitmq` lib but unfortunately it does not work as it is working when I have everything in a monolithic NestJS app. You can reproduce it here: https://github.com/kasir-barati/rabbitmq-microservice-nestjs-bug

Read the `README.md` carefully and you'll understand my point. Fun fact, when I use a library like amqplib to consume messages published in `audit_log.logs` queue I can receive them :face_holding_back_tears:, I tried to run this code right after I started my backend apps and it was logging the published message:

```ts
import { Channel, connect, Connection } from 'amqplib';
const connection = await connect('amqp://rabbitmq:password@localhost:5672');
const channel = await this.connection.createChannel();

channel.consume(
  'audit_log.logs',
  (message) => {
    console.log(`Message for "${AUDIT_LOG_QUEUE}"`);
    console.log(message?.content?.toString());
  },
  { noAck: false },
);
```

Another note is that when I activate Firehose Tracer it shows that messages are published and delivered to the right queue. My problem is that NestJS is not calling handlers that I've defined.

Any form of help is appreciated :heart:.

**Comment by underfisk** [comment]
@kasir-barati Please try to open this discussions/questions at `Discussions` 
I like to use `Issues` to triage real issue(s)

**Comment by kasir-barati** [comment]
TBH I do not think this is a discussion, but if you say so.

**Comment by underfisk** [comment]
@kasir-barati If you think this is a `bug` feel free to re-open but I think it's just a question/misconfiguration that can be asked in a different forum.

**Comment by kasir-barati** [comment]
I am really puzzled to be frank. But I will try to debug it on my own and see why it is not working and why the monolithic NestJS app works.

They are literally the same. Will reopen it if I gathered more evidence that this is a bug :slightly_smiling_face:.

**Comment by underfisk** [comment]
I appreciate that. If you manage to get a repro on the App that's working and the other that doesn't (monolith vs microservices) feel free to add them as repro's and I'll try to hop onto them. If you include a docker compose, its even easier

**Comment by kasir-barati** [comment]
@underfisk after a close examination and debugging it I realized that my Pipe was throwing a 400 error. But the weird part for me is that I was expecting it to log the error at least in the terminal. Any idea as why it is not?
