### ISSUE TITLE
How can I create RabbitMqModule conditionally?

### ISSUE THREAD

**Issue by ghost** [golevelup/nestjs#866]
Hello! I would like to create this module conditionally based on what is in `ConfigService`.

I have use cases for a service that can have `rabbitmq` connection or not. And most important, the service that publishes to the exchanges is used everywhere in the service. Is the anyone that have done such a dynamic module?

**Comment by underfisk** [comment]
@Andynopol I don't think we have an option to disable the module, if you'd like to contribute I would appreciate that :pray:
