### ISSUE TITLE
RabibtMQ: New URI validation is breaking amqps uri's

### ISSUE THREAD

**Issue by MathiasMonstrey** [golevelup/nestjs#873]
Since the latest version 5.6.0 of the [@golevelup/nestjs-rabbitmq](https://www.npmjs.com/package/@golevelup/nestjs-rabbitmq/v/5.6.0) package, we can no longer connect to our Amazon MQ.
According to the documentation of amazon we need to start our URL with `amqps://` instead of `amqp://`

This has always worked, but the latest version [introduced ](https://github.com/golevelup/nestjs/commit/af3ac52045e6893aa4e82f2a16964d4826641c87#diff-dba83c9f93093f5f8b2d8b1bc2aa654890601a59ad41f5b7f3de460827f632fbR31)a validation of the URL, but is only allowing `amqp` not `amqps`

**Comment by FloEdelmann** [comment]
Also, a trailing slash is not allowed anymore although it always worked fine (it's even used in [mock data](https://github.com/golevelup/nestjs/blob/aa7ef033151857ff147cee8fc04c11c8ff7d2f4c/packages/rabbitmq/src/tests/amqp.connection.spec.ts#L12) in a test file in this repo).
