### ISSUE TITLE
RabibtMQ: New URI validation is breaking uri's with / in the virtual host  

### ISSUE THREAD

**Issue by PavelPashov** [golevelup/nestjs#880]
Related to this [issue](https://github.com/golevelup/nestjs/issues/873).

Our virtual host includes `/` in the name, however the latest version 5.6.0 [introduced](https://github.com/golevelup/nestjs/blob/c47cc5b833c88bbe3d3c8b41e37de2c109603b1f/packages/rabbitmq/src/amqp/utils.ts#L31) a validation of the URL which fails if there's a `/` after the vhost one.

Example URI: `amqp://guest:guest@localhost:5672//my_virtual_host`

**Comment by underfisk** [comment]
@PavelPashov Are you able to help by adding this scenario on the parser/test case? 
This was a long-standing request that I've made initially but I'm pretty sure the vhost slipped :sweat_smile:
