### ISSUE TITLE
Google PubSub

### ISSUE THREAD

**Issue by erickamarante** [golevelup/nestjs#95]
Good morning.

Is the google pubsub project active? 

Tks.

**Comment by WonderPanda** [comment]
Hey @littlepotato86 Thanks for your interest in the library! Things were around 70% complete for Google PubSub integration but then I didn't end up needing it for work which put things on pause for a little bit. If there's an interest from the community I could definitely take a look at continuing development and getting a package published.

Can you share a little bit about what functionality you need to be able to support? Do you just need simple management of Topics and Subscriptions or are there any more advanced patterns that you're hoping to accomplish on top of that?
